---
title: "Trajectory Curves on MCS"
author: "Yira Zhang"
date: '2022-11-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(tidyr)
library(data.table)
library(tidyverse)
library(lavaan)
library(RColorBrewer)
```

## Data
# Load prepared data
```{r}
# Cr. Genie
MCS_autism <- read.csv("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_SDQ_autism.csv") # 188 in total
MCS_sdq_autism <- MCS_autism[,c(1:21,34:39,22:33,40:45)]
MCS_sdq_autism$sex_num <- ifelse(MCS_sdq_autism$Sex =="Male", 1, 0)
MCS_adhd <- read.csv("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_SDQ_adhd.csv") # 89 in total
MCS_sdq_adhd <- MCS_adhd[,c(1:21,34:39,22:33,40:45)]
MCS_autism_adhd_both <- read.csv("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_SDQ_both.csv")
MCS_sdq_both <- MCS_autism_adhd_both[,c(1:21,34:39,22:33,40:45)]
MCS_no_diag <- read.csv("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_SDQ_control.csv") # 6047 in total
MCS_sdq_no_diag <- MCS_no_diag[,c(1:21,34:39,22:33,40:45)]
```

# Load predictors
```{r}
mcs2_parent_interview <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5350-tab/tab/mcs2_parent_interview.tab")
mcs_ID_identifier <- read.csv("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/mcs_ID_identifier.csv")
mcs_ethnicity_mbirth_age <- read.csv("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/mcs_race_mbirthage.csv")
mcs2_ses_identifier <- read.csv("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/mcs_ses_identifier.csv")
mcs2_dep_identifier <- read.csv("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/mcs_deprivation_identifier.csv")
mcs2_family_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5350-tab/tab/mcs2_family_derived.tab")
mcs2_other_ses_identifier <- read.csv("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/mcs_other_ses_identifier.csv")
```


## Autism
# Reshape data to plot-ready form
```{r}
# Group autstic group according to their diagnosis age
# Though some parents provided specific diagnosis age in years, to conform to analysis in other cohorts so that cross-population comparisons could be allowed in the future
# "Early" = first reported diagnosis at w3 (age5) or w4 (age7)
# "Late = first reported diagnosis at w5 (age11) or w6 (age14)

library(plotrix)
MCS_sdq_autism_early <- MCS_sdq_autism %>% filter (ASD.Diagnosis.Age %in% c("at W3","at W4","at W5")) # n = 59
MCS_sdq_autism_late <- MCS_sdq_autism %>% filter (ASD.Diagnosis.Age %in% c("at W6")) # n = 129

```

# SDQ total
```{r}
# Early 
MCS_autism_early_sdq_ttl <- MCS_sdq_autism_early[,c(1,9,15,21,27,33,39,45)]

MCS_autism_early_sdq_ttl_long <- melt(setDT(MCS_autism_early_sdq_ttl), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_autism_early_ttl_summary <- MCS_autism_early_sdq_ttl_long %>%
  dplyr::group_by(sweep) %>%
  dplyr::summarise(
    sd = sd(value),
    ttl_mean = mean(value),
    se = std.error(value)
  )
MCS_autism_early_ttl_summary$group <- "early"

# Late

MCS_autism_late_sdq_ttl <- MCS_sdq_autism_late[,c(1,9,15,21,27,33,39,45)]

MCS_autism_late_sdq_ttl_long <- melt(setDT(MCS_autism_late_sdq_ttl), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_autism_late_ttl_summary <- MCS_autism_late_sdq_ttl_long %>%
   dplyr::group_by(sweep) %>%
   dplyr::summarise(
    sd = sd(value),
    ttl_mean = mean(value),     se = std.error(value)
  )
MCS_autism_late_ttl_summary$group <- "late"

# No diagnosis

MCS_no_diag_sdq_ttl <- MCS_sdq_no_diag[,c(1,9,15,21,27,33,39,42)]

MCS_no_diag_sdq_ttl_long <- melt(setDT(MCS_no_diag_sdq_ttl), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_no_diag_ttl_summary <- MCS_no_diag_sdq_ttl_long %>%
   dplyr::group_by(sweep) %>%
   dplyr::summarise(
    sd = sd(value),
    ttl_mean = mean(value),     se = std.error(value)
  )
MCS_no_diag_ttl_summary$group <- "no diag"
```



```{r, eval=FALSE}
age <- c("3","5","7","11","14","17")
MCS_early_indi_gt <- MCS_autism_early_sdq_ttl_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_early_indi_gt
  
MCS_early_mean_gt <-ggplot(data=MCS_autism_early_ttl_summary, aes(x=sweep, y=ttl_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_early_mean_gt

MCS_early_indi_mean_gt <- MCS_autism_early_sdq_ttl_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_autism_early_ttl_summary, aes(x = sweep , y = ttl_mean, group = 1), colour = "red")
MCS_early_display <- MCS_early_indi_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ ttl score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Total Score of Early Diagnosed Autism")
MCS_early_display


MCS_late_indi_gt <- MCS_autism_late_sdq_ttl_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_late_indi_gt
  
MCS_late_mean_gt <-ggplot(data=MCS_autism_late_ttl_summary, aes(x=sweep, y=ttl_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_late_mean_gt

MCS_late_indi_mean_gt <- MCS_autism_late_sdq_ttl_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_autism_late_ttl_summary, aes(x = sweep , y = ttl_mean, group = 1), colour = "red")
MCS_late_display <- MCS_late_indi_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ ttl score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Total Score of late Diagnosed Autism")
MCS_late_display

MCS_no_diag_indi_gt <- MCS_no_diag_sdq_ttl_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_no_diag_indi_gt
  
MCS_no_diag_mean_gt <-ggplot(data=MCS_no_diag_ttl_summary, aes(x=sweep, y=ttl_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_no_diag_mean_gt

MCS_no_diag_indi_mean_gt <- MCS_no_diag_sdq_ttl_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_no_diag_ttl_summary, aes(x = sweep , y = ttl_mean, group = 1), colour = "red")
MCS_no_diag_display <- MCS_no_diag_indi_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ ttl score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Total Score of No autism Diagnosis")
MCS_no_diag_display

```


```{r}
MCS_autism_early_ttl_summary$lb = MCS_autism_early_ttl_summary$ttl_mean - 1.96*MCS_autism_early_ttl_summary$se
MCS_autism_early_ttl_summary$ub = MCS_autism_early_ttl_summary$ttl_mean + 1.96*MCS_autism_early_ttl_summary$se
MCS_autism_late_ttl_summary$lb = MCS_autism_late_ttl_summary$ttl_mean - 1.96*MCS_autism_late_ttl_summary$se
MCS_autism_late_ttl_summary$ub = MCS_autism_late_ttl_summary$ttl_mean + 1.96*MCS_autism_late_ttl_summary$se
MCS_no_diag_ttl_summary$ub = MCS_no_diag_ttl_summary$ttl_mean + 1.96*MCS_no_diag_ttl_summary$se
MCS_no_diag_ttl_summary$lb = MCS_no_diag_ttl_summary$ttl_mean - 1.96*MCS_no_diag_ttl_summary$se
MCS_sdq_total_mean_full <- full_join(full_join(MCS_autism_early_ttl_summary, MCS_autism_late_ttl_summary), MCS_no_diag_ttl_summary)
MCS_sdq_total_mean_full <- MCS_sdq_total_mean_full %>% mutate(sweep.age = case_when(
  sweep == "BEBDTOT" ~ 3,
  sweep == "CEBDTOT" ~ 5,
  sweep == "DDDEBDTOT" ~ 7,
   sweep == "EEBDTOT" ~ 11,
   sweep == "FEBDTOT" ~ 14,
   sweep == "GEBDTOT" ~ 17,
))

```

```{r}

p <- ggplot(MCS_sdq_total_mean_full, aes(x = as.numeric(sweep.age), y = ttl_mean, colour = group)) + geom_line(data = MCS_sdq_total_mean_full, aes(x = as.numeric(sweep.age), y = ttl_mean, colour = group)) + geom_point() 
p



my_colors <- brewer.pal(12, "Paired")[c(2,8,4)]

MCS_full_ttl_in_display <- p+geom_ribbon(data = MCS_sdq_total_mean_full, aes(x = as.numeric(sweep.age),ymin = lb, ymax = ub), linetype = 2, alpha = 0.2) + scale_x_continuous(breaks = as.numeric(age) ,labels= age) + labs(y = "MCS SDQ Total Score", x = "Age (years)") + theme_classic() + scale_colour_manual(values = my_colors)+ theme(legend.position = "none")



MCS_full_ttl_in_display

```


# Emotional Symptoms
```{r}
# Early 
MCS_autism_early_sdq_emo <- MCS_sdq_autism_early[,c(1,4,10,16,22,28,34,45)]

MCS_autism_early_sdq_emo_long <- melt(setDT(MCS_autism_early_sdq_emo), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_autism_early_emo_summary <- MCS_autism_early_sdq_emo_long %>%
  dplyr::group_by(sweep) %>%
  dplyr::summarise(
    sd = sd(value),
    emo_mean = mean(value),     se = std.error(value)
  )
MCS_autism_early_emo_summary$group <- "early"

# Late

MCS_autism_late_sdq_emo <- MCS_sdq_autism_late[,c(1,4,10,16,22,28,34,45)]

MCS_autism_late_sdq_emo_long <- melt(setDT(MCS_autism_late_sdq_emo), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_autism_late_emo_summary <- MCS_autism_late_sdq_emo_long %>%
  dplyr::group_by(sweep) %>%
  dplyr::summarise(
    sd = sd(value),
    emo_mean = mean(value),     se = std.error(value)
  )
MCS_autism_late_emo_summary$group <- "late"

# No diagnosis

MCS_no_diag_sdq_emo <- MCS_sdq_no_diag[,c(1,4,10,16,22,28,34,42)]

MCS_no_diag_sdq_emo_long <- melt(setDT(MCS_no_diag_sdq_emo), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_no_diag_emo_summary <- MCS_no_diag_sdq_emo_long %>%
 dplyr::group_by(sweep) %>%
  dplyr::summarise(
    sd = sd(value),
    emo_mean = mean(value),     se = std.error(value)
  )
MCS_no_diag_emo_summary$group <- "no diag"
```



```{r,eval = F}

MCS_early_emo_indi_gt <- MCS_autism_early_sdq_emo_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_early_emo_indi_gt
  
MCS_early_mean_gt <-ggplot(data=MCS_autism_early_emo_summary, aes(x=sweep, y=emo_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_early_mean_gt

MCS_early_emo_indi_mean_gt <- MCS_autism_early_sdq_emo_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_autism_early_emo_summary, aes(x = sweep , y = emo_mean, group = 1), colour = "red")
MCS_early_display <- MCS_early_emo_indi_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ emo score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Emotional Score of Early Diagnosed Autism")
MCS_early_display


MCS_late_emo_indi_gt <- MCS_autism_late_sdq_emo_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_late_emo_indi_gt
  
MCS_late_mean_gt <-ggplot(data=MCS_autism_late_emo_summary, aes(x=sweep, y=emo_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_late_mean_gt

MCS_late_emo_indi_mean_gt <- MCS_autism_late_sdq_emo_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_autism_late_emo_summary, aes(x = sweep , y = emo_mean, group = 1), colour = "red")
MCS_late_display <- MCS_late_emo_indi_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ emo score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Emotional Score of late Diagnosed Autism")
MCS_late_display




MCS_no_diag_emo_indi_gt <- MCS_no_diag_sdq_emo_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_no_diag_emo_indi_gt
  
MCS_no_diag_mean_gt <-ggplot(data= MCS_no_diag_emo_summary, aes(x=sweep, y=emo_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_no_diag_mean_gt

MCS_no_diag_emo_indi_mean_gt <- MCS_no_diag_sdq_emo_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_no_diag_emo_summary, aes(x = sweep , y = emo_mean, group = 1), colour = "red")
MCS_no_diag_display <- MCS_no_diag_emo_indi_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ emo score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Emotional Score of No autism Diagnosis")
MCS_no_diag_display

```


```{r}
MCS_autism_early_emo_summary$lb = MCS_autism_early_emo_summary$emo_mean - 1.96*MCS_autism_early_emo_summary$se
MCS_autism_early_emo_summary$ub = MCS_autism_early_emo_summary$emo_mean + 1.96*MCS_autism_early_emo_summary$se
MCS_autism_late_emo_summary$lb = MCS_autism_late_emo_summary$emo_mean - 1.96*MCS_autism_late_emo_summary$se
MCS_autism_late_emo_summary$ub = MCS_autism_late_emo_summary$emo_mean + 1.96*MCS_autism_late_emo_summary$se
MCS_no_diag_emo_summary$ub = MCS_no_diag_emo_summary$emo_mean + 1.96*MCS_no_diag_emo_summary$se
MCS_no_diag_emo_summary$lb = MCS_no_diag_emo_summary$emo_mean - 1.96*MCS_no_diag_emo_summary$se
MCS_sdq_Emotional_mean_full <- full_join(full_join(MCS_autism_early_emo_summary, MCS_autism_late_emo_summary), MCS_no_diag_emo_summary)
MCS_sdq_Emotional_mean_full <- MCS_sdq_Emotional_mean_full %>% mutate(sweep.age = case_when(
  sweep == "BEMOTION" ~ 3,
  sweep == "CEMOTION" ~ 5,
  sweep == "DDEMOTION" ~ 7,
   sweep == "EEMOTION" ~ 11,
   sweep == "FEMOTION" ~ 14,
   sweep == "GEMOTION" ~ 17,
))
```

```{r}

p <- ggplot(MCS_sdq_Emotional_mean_full, aes(x = as.numeric(sweep.age), y = emo_mean, colour = group)) + geom_line(data = MCS_sdq_Emotional_mean_full, aes(x = as.numeric(sweep.age), y = emo_mean, colour = group)) + geom_point() 
p



breaks = seq(min(as.numeric(MCS_no_diag_emo_summary$sweep)),max(as.numeric(MCS_no_diag_emo_summary$sweep)), length.out = 6)

MCS_full_emo_in_display <- p+geom_ribbon(data = MCS_sdq_Emotional_mean_full, aes(x = as.numeric(sweep.age),ymin = lb, ymax = ub), linetype = 2, alpha = 0.2) + scale_x_continuous(breaks = as.numeric(age) ,labels= age) + labs(y = "MCS SDQ Emotional Symptoms Score", x = "Age (years)")  + theme_classic() + scale_colour_manual(values = my_colors)+ theme(legend.position = "none")


MCS_full_emo_in_display

```



# Conduct Problems

```{r}
# Early 
MCS_autism_early_sdq_con <- MCS_sdq_autism_early[,c(1,5,11,17,23,29,35,45)]

MCS_autism_early_sdq_con_long <- melt(setDT(MCS_autism_early_sdq_con), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_autism_early_con_summary <- MCS_autism_early_sdq_con_long %>%
  dplyr::group_by(sweep) %>%
  dplyr::summarise(
    sd = sd(value),
    con_mean = mean(value),     se = std.error(value)
  )
MCS_autism_early_con_summary$group <- "early"

# Late

MCS_autism_late_sdq_con <- MCS_sdq_autism_late[,c(1,5,11,17,23,29,35,45)]

MCS_autism_late_sdq_con_long <- melt(setDT(MCS_autism_late_sdq_con), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_autism_late_con_summary <- MCS_autism_late_sdq_con_long %>%
  dplyr::group_by(sweep) %>%
  dplyr::summarise(
    sd = sd(value),
    con_mean = mean(value),     se = std.error(value)
  )
MCS_autism_late_con_summary$group <- "late"

# No diagnosis

MCS_no_diag_sdq_con <- MCS_sdq_no_diag[,c(1,5,11,17,23,29,35,42)]

MCS_no_diag_sdq_con_long <- melt(setDT(MCS_no_diag_sdq_con), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_no_diag_con_summary <- MCS_no_diag_sdq_con_long %>%
  dplyr::group_by(sweep) %>%
  dplyr::summarise(
    sd = sd(value),
    con_mean = mean(value),     se = std.error(value)
  )
MCS_no_diag_con_summary$group <- "no diag"
```



```{r,eval = F}
age <- c("3","5","7","11","14","17")
MCS_early_conduct_indi_gt <- MCS_autism_early_sdq_con_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_early_conduct_indi_gt
  
MCS_early_conduct_mean_gt <-ggplot(data=MCS_autism_early_con_summary, aes(x=sweep, y=con_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_early_conduct_mean_gt

MCS_early_conduct_indi_conduct_mean_gt <- MCS_autism_early_sdq_con_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_autism_early_con_summary, aes(x = sweep , y = con_mean, group = 1), colour = "red")
MCS_early_display <- MCS_early_conduct_indi_conduct_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ con score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Conduct Score of Early Diagnosed Autism")
MCS_early_display



MCS_late_conduct_indi_gt <- MCS_autism_late_sdq_con_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_late_conduct_indi_gt
  
MCS_late_conduct_mean_gt <-ggplot(data=MCS_autism_late_con_summary, aes(x=sweep, y=con_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_late_conduct_mean_gt

MCS_late_conduct_indi_conduct_mean_gt <- MCS_autism_late_sdq_con_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_autism_late_con_summary, aes(x = sweep , y = con_mean, group = 1), colour = "red")
MCS_late_display <- MCS_late_conduct_indi_conduct_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ con score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Conduct Score of late Diagnosed Autism")
MCS_late_display




MCS_no_diag_conduct_indi_gt <- MCS_no_diag_sdq_con_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_no_diag_conduct_indi_gt
  
MCS_no_diag_conduct_mean_gt <-ggplot(data=MCS_no_diag_con_summary, aes(x=sweep, y=con_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_no_diag_conduct_mean_gt

MCS_no_diag_conduct_indi_conduct_mean_gt <- MCS_no_diag_sdq_con_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_no_diag_con_summary, aes(x = sweep , y = con_mean, group = 1), colour = "red")
MCS_no_diag_display <- MCS_no_diag_conduct_indi_conduct_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ con score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Conduct Score of No autism Diagnosis")
MCS_no_diag_display

```


```{r}
MCS_autism_early_con_summary$lb = MCS_autism_early_con_summary$con_mean - 1.96*MCS_autism_early_con_summary$se
MCS_autism_early_con_summary$ub = MCS_autism_early_con_summary$con_mean + 1.96*MCS_autism_early_con_summary$se
MCS_autism_late_con_summary$lb = MCS_autism_late_con_summary$con_mean - 1.96*MCS_autism_late_con_summary$se
MCS_autism_late_con_summary$ub = MCS_autism_late_con_summary$con_mean + 1.96*MCS_autism_late_con_summary$se
MCS_no_diag_con_summary$ub = MCS_no_diag_con_summary$con_mean + 1.96*MCS_no_diag_con_summary$se
MCS_no_diag_con_summary$lb = MCS_no_diag_con_summary$con_mean - 1.96*MCS_no_diag_con_summary$se
MCS_sdq_Conduct_mean_full <- full_join(full_join(MCS_autism_early_con_summary, MCS_autism_late_con_summary), MCS_no_diag_con_summary)
MCS_sdq_Conduct_mean_full <- MCS_sdq_Conduct_mean_full %>% mutate(sweep.age = case_when(
  sweep == "BCONDUCT" ~ 3,
  sweep == "CCONDUCT" ~ 5,
  sweep == "DDCONDUCT" ~ 7,
   sweep == "ECONDUCT" ~ 11,
   sweep == "FCONDUCT" ~ 14,
   sweep == "GCONDUCT" ~ 17,
))
```

```{r}

p <- ggplot(MCS_sdq_Conduct_mean_full, aes(x = as.numeric(sweep.age), y = con_mean, colour = group)) + geom_line(data = MCS_sdq_Conduct_mean_full, aes(x = as.numeric(sweep.age), y = con_mean, colour = group)) + geom_point() 
p



breaks = seq(min(as.numeric(MCS_no_diag_con_summary$sweep)),max(as.numeric(MCS_no_diag_con_summary$sweep)), length.out = 6)

MCS_full_con_in_display <- p+geom_ribbon(data = MCS_sdq_Conduct_mean_full, aes(x = as.numeric(sweep.age),ymin = lb, ymax = ub), linetype = 2, alpha = 0.2) + scale_x_continuous(breaks = as.numeric(age) ,labels= age) + labs(y = "MCS SDQ Conduct Problems Score", x = "Age (years)") + theme_classic() + scale_colour_manual(values = my_colors)+ theme(legend.position = "none")


MCS_full_con_in_display

```






# Hyperactivity

```{r}
# Early 
MCS_autism_early_sdq_hyp <- MCS_sdq_autism_early[,c(1,6,12,18,24,30,36,45)]

MCS_autism_early_sdq_hyp_long <- melt(setDT(MCS_autism_early_sdq_hyp), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_autism_early_hyp_summary <- MCS_autism_early_sdq_hyp_long %>%
  dplyr::group_by(sweep) %>%
  dplyr::summarise(
    sd = sd(value),
    hyp_mean = mean(value),     se = std.error(value)
  )
MCS_autism_early_hyp_summary$group <- "early"

# Late

MCS_autism_late_sdq_hyp <- MCS_sdq_autism_late[,c(1,6,12,18,24,30,36,45)]

MCS_autism_late_sdq_hyp_long <- melt(setDT(MCS_autism_late_sdq_hyp), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_autism_late_hyp_summary <- MCS_autism_late_sdq_hyp_long %>%
  dplyr::group_by(sweep) %>%
  dplyr::summarise(
    sd = sd(value),
    hyp_mean = mean(value),     se = std.error(value)
  )
MCS_autism_late_hyp_summary$group <- "late"

# No diagnosis

MCS_no_diag_sdq_hyp <- MCS_sdq_no_diag[,c(1,6,12,18,24,30,36,42)]

MCS_no_diag_sdq_hyp_long <- melt(setDT(MCS_no_diag_sdq_hyp), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_no_diag_hyp_summary <- MCS_no_diag_sdq_hyp_long %>%
  dplyr::group_by(sweep) %>%
  dplyr::summarise(
    sd = sd(value),
    hyp_mean = mean(value),     se = std.error(value)
  )
MCS_no_diag_hyp_summary$group <- "no diag"
```



```{r,eval = F}
age <- c("3","5","7","11","14","17")
MCS_early_hyp_indi_gt <- MCS_autism_early_sdq_hyp_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_early_hyp_indi_gt
  
MCS_early_hyp_mean_gt <-ggplot(data=MCS_autism_early_hyp_summary, aes(x=sweep, y=hyp_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_early_hyp_mean_gt

MCS_early_indi_hyp_mean_gt <- MCS_autism_early_sdq_hyp_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_autism_early_hyp_summary, aes(x = sweep , y = hyp_mean, group = 1), colour = "red")
MCS_early_display <- MCS_early_indi_hyp_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ hyp score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ hyperactivity Score of Early Diagnosed Autism")
MCS_early_display


MCS_late_hyp_indi_gt <- MCS_autism_late_sdq_hyp_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_late_hyp_indi_gt
  
MCS_late_hyp_mean_gt <-ggplot(data=MCS_autism_late_hyp_summary, aes(x=sweep, y=hyp_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_late_hyp_mean_gt

MCS_late_indi_hyp_mean_gt <- MCS_autism_late_sdq_hyp_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_autism_late_hyp_summary, aes(x = sweep , y = hyp_mean, group = 1), colour = "red")
MCS_late_display <- MCS_late_indi_hyp_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ hyp score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ hyperactivity Score of late Diagnosed Autism")
MCS_late_display

MCS_no_diag_hyp_indi_gt <- MCS_no_diag_sdq_hyp_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_no_diag_hyp_indi_gt
  
MCS_no_diag_hyp_mean_gt <-ggplot(data=MCS_no_diag_hyp_summary, aes(x=sweep, y=hyp_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_no_diag_hyp_mean_gt

MCS_no_diag_indi_hyp_mean_gt <- MCS_no_diag_sdq_hyp_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_no_diag_hyp_summary, aes(x = sweep , y = hyp_mean, group = 1), colour = "red")
MCS_no_diag_display <- MCS_no_diag_indi_hyp_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ hyp score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ hyperactivity Score of No autism Diagnosis")
MCS_no_diag_display

```


```{r}
MCS_autism_early_hyp_summary$lb = MCS_autism_early_hyp_summary$hyp_mean - 1.96*MCS_autism_early_hyp_summary$se
MCS_autism_early_hyp_summary$ub = MCS_autism_early_hyp_summary$hyp_mean + 1.96*MCS_autism_early_hyp_summary$se
MCS_autism_late_hyp_summary$lb = MCS_autism_late_hyp_summary$hyp_mean - 1.96*MCS_autism_late_hyp_summary$se
MCS_autism_late_hyp_summary$ub = MCS_autism_late_hyp_summary$hyp_mean + 1.96*MCS_autism_late_hyp_summary$se
MCS_no_diag_hyp_summary$ub = MCS_no_diag_hyp_summary$hyp_mean + 1.96*MCS_no_diag_hyp_summary$se
MCS_no_diag_hyp_summary$lb = MCS_no_diag_hyp_summary$hyp_mean - 1.96*MCS_no_diag_hyp_summary$se
MCS_sdq_hyperactivity_mean_full <- full_join(full_join(MCS_autism_early_hyp_summary, MCS_autism_late_hyp_summary), MCS_no_diag_hyp_summary)
MCS_sdq_hyperactivity_mean_full <- MCS_sdq_hyperactivity_mean_full %>% mutate(sweep.age = case_when(
  sweep == "BHYPER" ~ 3,
  sweep == "CHYPER" ~ 5,
  sweep == "DDHYPER" ~ 7,
   sweep == "EHYPER" ~ 11,
   sweep == "FHYPER" ~ 14,
   sweep == "GHYPER" ~ 17,
))

```

```{r}

p <- ggplot(MCS_sdq_hyperactivity_mean_full, aes(x = as.numeric(sweep.age), y = hyp_mean, colour = group)) + geom_line(data = MCS_sdq_hyperactivity_mean_full, aes(x = as.numeric(sweep.age), y = hyp_mean, colour = group)) + geom_point() 
p



breaks = seq(min(as.numeric(MCS_no_diag_hyp_summary$sweep)),max(as.numeric(MCS_no_diag_hyp_summary$sweep)), length.out = 6)

MCS_full_hyp_in_display <- p+geom_ribbon(data = MCS_sdq_hyperactivity_mean_full, aes(x = as.numeric(sweep.age),ymin = lb, ymax = ub), linetype = 2, alpha = 0.2) + scale_x_continuous(breaks = as.numeric(age) ,labels= age) + labs(y = "MCS SDQ Hyperactivity-Inattention Score", x = "Age (years)")  + theme_classic() + scale_colour_manual(values = my_colors)+ theme(legend.position = "none")

MCS_full_hyp_in_display

```



# Peer Relationship

```{r}
# Early 
MCS_autism_early_sdq_peer <- MCS_sdq_autism_early[,c(1,7,13,19,25,31,37,45)]

MCS_autism_early_sdq_peer_long <- melt(setDT(MCS_autism_early_sdq_peer), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_autism_early_peer_summary <- MCS_autism_early_sdq_peer_long %>%
  dplyr::group_by(sweep) %>%
  dplyr::summarise(
    sd = sd(value),
    peer_mean = mean(value),     se = std.error(value)
  )
MCS_autism_early_peer_summary$group <- "early"

# Late

MCS_autism_late_sdq_peer <- MCS_sdq_autism_late[,c(1,7,13,19,25,31,37,45)]

MCS_autism_late_sdq_peer_long <- melt(setDT(MCS_autism_late_sdq_peer), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_autism_late_peer_summary <- MCS_autism_late_sdq_peer_long %>%
  dplyr::group_by(sweep) %>%
  dplyr::summarise(
    sd = sd(value),
    peer_mean = mean(value),     se = std.error(value)
  )
MCS_autism_late_peer_summary$group <- "late"

# No diagnosis

MCS_no_diag_sdq_peer <- MCS_sdq_no_diag[,c(1,7,13,19,25,31,37,42)]

MCS_no_diag_sdq_peer_long <- melt(setDT(MCS_no_diag_sdq_peer), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_no_diag_peer_summary <- MCS_no_diag_sdq_peer_long %>%
  dplyr::group_by(sweep) %>%
  dplyr::summarise(
    sd = sd(value),
    peer_mean = mean(value),     se = std.error(value)
  )
MCS_no_diag_peer_summary$group <- "no diag"
```



```{r,eval = F}
age <- c("3","5","7","11","14","17")
MCS_early_peer_indi_gt <- MCS_autism_early_sdq_peer_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_early_peer_indi_gt
  
MCS_early_peer_mean_gt <-ggplot(data=MCS_autism_early_peer_summary, aes(x=sweep, y=peer_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_early_peer_mean_gt

MCS_early_indi_peer_mean_gt <- MCS_autism_early_sdq_peer_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_autism_early_peer_summary, aes(x = sweep , y = peer_mean, group = 1), colour = "red")
MCS_early_display <- MCS_early_indi_peer_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ peer score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Peer Score of Early Diagnosed Autism")
MCS_early_display


MCS_late_peer_indi_gt <- MCS_autism_late_sdq_peer_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_late_peer_indi_gt
  
MCS_late_peer_mean_gt <-ggplot(data=MCS_autism_late_peer_summary, aes(x=sweep, y=peer_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_late_peer_mean_gt

MCS_late_indi_peer_mean_gt <- MCS_autism_late_sdq_peer_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_autism_late_peer_summary, aes(x = sweep , y = peer_mean, group = 1), colour = "red")
MCS_late_display <- MCS_late_indi_peer_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ peer score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Peer Score of late Diagnosed Autism")
MCS_late_display

MCS_no_diag_peer_indi_gt <- MCS_no_diag_sdq_peer_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_no_diag_peer_indi_gt
  
MCS_no_diag_peer_mean_gt <-ggplot(data=MCS_no_diag_peer_summary, aes(x=sweep, y=peer_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_no_diag_peer_mean_gt

MCS_no_diag_indi_peer_mean_gt <- MCS_no_diag_sdq_peer_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_no_diag_peer_summary, aes(x = sweep , y = peer_mean, group = 1), colour = "red")
MCS_no_diag_display <- MCS_no_diag_indi_peer_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ peer score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Peer Score of No autism Diagnosis")
MCS_no_diag_display

```


```{r}
MCS_autism_early_peer_summary$lb = MCS_autism_early_peer_summary$peer_mean - 1.96*MCS_autism_early_peer_summary$se
MCS_autism_early_peer_summary$ub = MCS_autism_early_peer_summary$peer_mean + 1.96*MCS_autism_early_peer_summary$se
MCS_autism_late_peer_summary$lb = MCS_autism_late_peer_summary$peer_mean - 1.96*MCS_autism_late_peer_summary$se
MCS_autism_late_peer_summary$ub = MCS_autism_late_peer_summary$peer_mean + 1.96*MCS_autism_late_peer_summary$se
MCS_no_diag_peer_summary$ub = MCS_no_diag_peer_summary$peer_mean + 1.96*MCS_no_diag_peer_summary$se
MCS_no_diag_peer_summary$lb = MCS_no_diag_peer_summary$peer_mean - 1.96*MCS_no_diag_peer_summary$se
MCS_sdq_peer_mean_full <- full_join(full_join(MCS_autism_early_peer_summary, MCS_autism_late_peer_summary), MCS_no_diag_peer_summary)
MCS_sdq_peer_mean_full <- MCS_sdq_peer_mean_full %>% mutate(sweep.age = case_when(
sweep == "BPEER" ~ 3,
  sweep == "CPEER" ~ 5,
  sweep == "DDPEER" ~ 7,
   sweep == "EPEER" ~ 11,
   sweep == "FPEER" ~ 14,
   sweep == "GPEER" ~ 17
))
```

```{r}

p <- ggplot(MCS_sdq_peer_mean_full, aes(x = as.numeric(sweep.age), y = peer_mean, colour = group)) + geom_line(data = MCS_sdq_peer_mean_full, aes(x = as.numeric(sweep.age), y = peer_mean, colour = group)) + geom_point() 
p



breaks = seq(min(as.numeric(MCS_no_diag_peer_summary$sweep)),max(as.numeric(MCS_no_diag_peer_summary$sweep)), length.out = 6)

MCS_full_peer_in_display <- p+geom_ribbon(data = MCS_sdq_peer_mean_full, aes(x = as.numeric(sweep.age),ymin = lb, ymax = ub), linetype = 2, alpha = 0.2) + scale_x_continuous(breaks = as.numeric(age) ,labels= age) + labs(y = "MCS SDQ Peer Relationship Problems Score", x = "Age (years)")  + theme_classic() + scale_colour_manual(values = my_colors)+ theme(legend.position = "none")


MCS_full_peer_in_display

```




# Prosocialness


```{r}
# Early 
MCS_autism_early_sdq_pro <- MCS_sdq_autism_early[,c(1,8,14,20,26,32,38,45)]

MCS_autism_early_sdq_pro_long <- melt(setDT(MCS_autism_early_sdq_pro), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_autism_early_pro_summary <- MCS_autism_early_sdq_pro_long %>%
   dplyr::group_by(sweep) %>%
   dplyr::summarise(
    sd = sd(value),
    pro_mean = mean(value),     se = std.error(value)
  )
MCS_autism_early_pro_summary$group <- "early"

# Late

MCS_autism_late_sdq_pro <- MCS_sdq_autism_late[,c(1,8,14,20,26,32,38,45)]

MCS_autism_late_sdq_pro_long <- melt(setDT(MCS_autism_late_sdq_pro), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_autism_late_pro_summary <- MCS_autism_late_sdq_pro_long %>%
   dplyr::group_by(sweep) %>%
   dplyr::summarise(
    sd = sd(value),
    pro_mean = mean(value),     se = std.error(value)
  )
MCS_autism_late_pro_summary$group <- "late"

# No diagnosis

MCS_no_diag_sdq_pro <- MCS_sdq_no_diag[,c(1,8,14,20,26,32,38,42)]

MCS_no_diag_sdq_pro_long <- melt(setDT(MCS_no_diag_sdq_pro), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_no_diag_pro_summary <- MCS_no_diag_sdq_pro_long %>%
   dplyr::group_by(sweep) %>%
   dplyr::summarise(
    sd = sd(value),
    pro_mean = mean(value),     se = std.error(value)
  )
MCS_no_diag_pro_summary$group <- "no diag"
```



```{r,eavl = F}
age <- c("3","5","7","11","14","17")
MCS_early_pro_indi_gt <- MCS_autism_early_sdq_pro_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_early_pro_indi_gt
  
MCS_early_pro_mean_gt <-ggplot(data=MCS_autism_early_pro_summary, aes(x=sweep, y=pro_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_early_pro_mean_gt

MCS_early_indi_pro_mean_gt <- MCS_autism_early_sdq_pro_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_autism_early_pro_summary, aes(x = sweep , y = pro_mean, group = 1), colour = "red")
MCS_early_display <- MCS_early_indi_pro_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ pro score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Prosocial Score of Early Diagnosed Autism")
MCS_early_display


MCS_late_pro_indi_gt <- MCS_autism_late_sdq_pro_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_late_pro_indi_gt
  
MCS_late_pro_mean_gt <-ggplot(data=MCS_autism_late_pro_summary, aes(x=sweep, y=pro_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_late_pro_mean_gt

MCS_late_indi_pro_mean_gt <- MCS_autism_late_sdq_pro_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_autism_late_pro_summary, aes(x = sweep , y = pro_mean, group = 1), colour = "red")
MCS_late_display <- MCS_late_indi_pro_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ pro score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Prosocial Score of late Diagnosed Autism")
MCS_late_display

MCS_no_diag_pro_indi_gt <- MCS_no_diag_sdq_pro_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")
MCS_no_diag_pro_indi_gt
  
MCS_no_diag_pro_mean_gt <-ggplot(data=MCS_no_diag_pro_summary, aes(x=sweep, y=pro_mean, group=1)) +
  geom_line(color="red")+
  geom_point()

MCS_no_diag_pro_mean_gt

MCS_no_diag_indi_pro_mean_gt <- MCS_no_diag_sdq_pro_long %>%
  ggplot(aes(x=sweep, value)) + geom_line(aes(group=MCSID), colour = "grey")+
  geom_line(data = MCS_no_diag_pro_summary, aes(x = sweep , y = pro_mean, group = 1), colour = "red")
MCS_no_diag_display <- MCS_no_diag_indi_pro_mean_gt + scale_x_discrete(labels= age) + labs(y = "SDQ pro score", x = "age(years)") +ggtitle("MCS Indi. and GMean Growth Curve of SDQ Prosocial Score of No autism Diagnosis")
MCS_no_diag_display

```


```{r}
MCS_autism_early_pro_summary$lb = MCS_autism_early_pro_summary$pro_mean - 1.96*MCS_autism_early_pro_summary$se
MCS_autism_early_pro_summary$ub = MCS_autism_early_pro_summary$pro_mean + 1.96*MCS_autism_early_pro_summary$se
MCS_autism_late_pro_summary$lb = MCS_autism_late_pro_summary$pro_mean - 1.96*MCS_autism_late_pro_summary$se
MCS_autism_late_pro_summary$ub = MCS_autism_late_pro_summary$pro_mean + 1.96*MCS_autism_late_pro_summary$se
MCS_no_diag_pro_summary$ub = MCS_no_diag_pro_summary$pro_mean + 1.96*MCS_no_diag_pro_summary$se
MCS_no_diag_pro_summary$lb = MCS_no_diag_pro_summary$pro_mean - 1.96*MCS_no_diag_pro_summary$se
MCS_sdq_prosocial_mean_full <- full_join(full_join(MCS_autism_early_pro_summary, MCS_autism_late_pro_summary), MCS_no_diag_pro_summary)
MCS_sdq_prosocial_mean_full <- MCS_sdq_prosocial_mean_full %>% mutate(sweep.age = case_when(sweep == "BPROSOC" ~ 3,
  sweep == "CPROSOC" ~ 5,
  sweep == "DDPROSOC" ~ 7,
   sweep == "EPROSOC" ~ 11,
   sweep == "FPROSOC" ~ 14,
   sweep == "GPROSOC" ~ 17
                                                                                ))


```

```{r}

p <- ggplot(MCS_sdq_prosocial_mean_full, aes(x = as.numeric(sweep.age), y = pro_mean, colour = group)) + geom_line(data = MCS_sdq_prosocial_mean_full, aes(x = as.numeric(sweep.age), y = pro_mean, colour = group)) + geom_point() 
p



breaks = seq(min(as.numeric(MCS_no_diag_pro_summary$sweep)),max(as.numeric(MCS_no_diag_pro_summary$sweep)), length.out = 6)

MCS_full_pro_in_display <- p+geom_ribbon(data = MCS_sdq_prosocial_mean_full, aes(x = as.numeric(sweep.age),ymin = lb, ymax = ub), linetype = 2, alpha = 0.2) + scale_x_continuous(breaks = as.numeric(age) ,labels= age) + labs(y = "MCS SDQ Prosocial Behavioural Score", x = "Age (years)")  + theme_classic() + scale_colour_manual(values = my_colors)+ theme(legend.position = "none")


MCS_full_pro_in_display

```

```{r}
pdf("/Users/zhangxinhe/Documents/who recieves a diagnosis/Figures FINAL/MCS_SDQ_n_subscales_traj_diag_age.pdf", width = 10,height = 6)
print(MCS_full_ttl_in_display) 
print(MCS_full_emo_in_display) 
print(MCS_full_con_in_display)
print(MCS_full_hyp_in_display)
print(MCS_full_peer_in_display)
print(MCS_full_pro_in_display)
dev.off()
```



