---
title: "mcs_adhd_gmm"
author: "Yira Zhang"
date: "2023-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages
```{r}

library(knitr)
library(markdown)
library(tidyverse)
library(ggplot2)
library(tidyr)
library(data.table)
library(lcmm)
library(lavaan)
library(stringr)
```

## Load data
```{r}
MCS_adhd <- read.csv("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_SDQ_adhd.csv") # 89 in total
MCS_sdq_adhd <- MCS_adhd[,c(1:21,34:39,22:33,40:45)]
MCS_sdq_adhd<- dplyr::mutate(MCS_sdq_adhd, numericID = row_number())
MCS_autism_adhd_both <- read.csv("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_SDQ_both.csv")
MCS_sdq_both <- MCS_autism_adhd_both[,c(1:21,34:39,22:33,40:45)]
MCS_sdq_both <- dplyr::mutate(MCS_sdq_both, numericID = row_number())
```

# ADHD
## Reshape data
```{r}
MCS_sdq_adhd <- MCS_sdq_adhd %>%
  mutate(diag.age = case_when(
    ADHD.Diagnosis.Age == "at W3" ~ 5,
    ADHD.Diagnosis.Age == "at W4" ~ 7,
    ADHD.Diagnosis.Age == "at W5" ~ 11,
    ADHD.Diagnosis.Age == "at W6" ~ 14)
    )
MCS_adhd_wide_sdq_total <- MCS_sdq_adhd[,c("numericID","MCSID","Sex","diag.age","BEBDTOT","CEBDTOT", "DDDEBDTOT" ,"EEBDTOT","FEBDTOT","GEBDTOT")]
MCS_adhd_long_sdq_total <- melt(setDT(MCS_adhd_wide_sdq_total), id.vars = c("numericID","MCSID","Sex","diag.age"), variable.name = "sweep")
MCS_adhd_long_sdq_total <- MCS_adhd_long_sdq_total %>%
  mutate(Sweep.age = case_when(
    sweep == "BEBDTOT" ~ 3,
    sweep == "CEBDTOT" ~ 5,
    sweep == "DDDEBDTOT" ~ 7,
    sweep == "EEBDTOT" ~ 11,
    sweep == "FEBDTOT" ~ 14,
    sweep == "GEBDTOT" ~ 17)
    )


MCS_adhd_wide_sdq_emo <- MCS_sdq_adhd[,c("numericID","MCSID","Sex","diag.age","BEMOTION","CEMOTION", "DDEMOTION","EEMOTION","FEMOTION","GEMOTION")]
MCS_adhd_long_sdq_emo <- melt(setDT(MCS_adhd_wide_sdq_emo), id.vars = c("numericID","MCSID","Sex","diag.age"), variable.name = "sweep")
MCS_adhd_long_sdq_emo <- MCS_adhd_long_sdq_emo %>%
  mutate(Sweep.age = case_when(
    sweep == "BEMOTION" ~ 3,
    sweep == "CEMOTION" ~ 5,
    sweep == "DDEMOTION" ~ 7,
    sweep == "EEMOTION" ~ 11,
    sweep == "FEMOTION" ~ 14,
    sweep == "GEMOTION" ~ 17)
    )


MCS_adhd_wide_sdq_con <- MCS_sdq_adhd[,c("numericID","MCSID","Sex","diag.age","BCONDUCT","CCONDUCT","DDCONDUCT","ECONDUCT","FCONDUCT","GCONDUCT")]
MCS_adhd_long_sdq_con <- melt(setDT(MCS_adhd_wide_sdq_con), id.vars = c("numericID","MCSID","Sex","diag.age"), variable.name = "sweep")
MCS_adhd_long_sdq_con <- MCS_adhd_long_sdq_con %>%
  mutate(Sweep.age = case_when(
    sweep == "BCONDUCT" ~ 3,
    sweep == "CCONDUCT" ~ 5,
    sweep == "DDCONDUCT" ~ 7,
    sweep == "ECONDUCT" ~11,
    sweep == "FCONDUCT" ~ 14,
    sweep == "GCONDUCT" ~ 17)
    )


MCS_adhd_wide_sdq_hyp <- MCS_sdq_adhd[,c("numericID","MCSID","Sex","diag.age","BHYPER","CHYPER","DDHYPER","EHYPER","FHYPER","GHYPER")]
MCS_adhd_long_sdq_hyp <- melt(setDT(MCS_adhd_wide_sdq_hyp), id.vars = c("numericID","MCSID","Sex","diag.age"), variable.name = "sweep")
MCS_adhd_long_sdq_hyp <- MCS_adhd_long_sdq_hyp %>%
  mutate(Sweep.age = case_when(
    sweep == "BHYPER" ~ 3,
    sweep == "CHYPER" ~ 5,
    sweep == "DDHYPER" ~ 7,
    sweep == "EHYPER" ~ 11,
    sweep == "FHYPER" ~ 14,
    sweep == "GHYPER" ~ 17)
    )


MCS_adhd_wide_sdq_peer <- MCS_sdq_adhd[,c("numericID","MCSID","Sex","diag.age","BPEER","CPEER","DDPEER","EPEER","FPEER","GPEER")]
MCS_adhd_long_sdq_peer <- melt(setDT(MCS_adhd_wide_sdq_peer), id.vars = c("numericID","MCSID","Sex","diag.age"), variable.name = "sweep")
MCS_adhd_long_sdq_peer <- MCS_adhd_long_sdq_peer %>%
  mutate(Sweep.age = case_when(
    sweep == "BPEER" ~ 3,
    sweep == "CPEER" ~ 5,
    sweep == "DDPEER" ~ 7,
    sweep == "EPEER" ~ 11,
    sweep == "FPEER" ~ 14,
    sweep == "GPEER" ~ 17)
    )


MCS_adhd_wide_sdq_pro <- MCS_sdq_adhd[,c("numericID","MCSID","Sex","diag.age","BPROSOC","CPROSOC","DDPROSOC","EPROSOC","FPROSOC","GPROSOC")]
MCS_adhd_long_sdq_pro <- melt(setDT(MCS_adhd_wide_sdq_pro), id.vars = c("numericID","MCSID","Sex","diag.age"), variable.name = "sweep")
MCS_adhd_long_sdq_pro <- MCS_adhd_long_sdq_pro %>%
  mutate(Sweep.age = case_when(
    sweep == "BPROSOC" ~ 3,
    sweep == "CPROSOC" ~ 5,
    sweep == "DDPROSOC" ~ 7,
    sweep == "EPROSOC" ~ 11,
    sweep == "FPROSOC" ~ 14,
    sweep == "GPROSOC" ~ 17)
    )
age <- c("3","5","7","11","14","17")
```

# GMM
## SDQ total
```{r}
mcs_adhd_ttl_gmm1 <- hlme(value ~ Sweep, subject = "numericID", random=~1, ng = 1, data =
MCS_adhd_long_sdq_total)
summary(mcs_adhd_ttl_gmm1)


mcs_adhd_ttl_gmm2 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 2, data = MCS_adhd_long_sdq_total, mixture = ~ Sweep, classmb =~ diag.age,
nwg=T, B = mcs_adhd_ttl_gmm1)
summary(mcs_adhd_ttl_gmm2)


mcs_adhd_ttl_gmm3 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 3, data = MCS_adhd_long_sdq_total, mixture = ~ Sweep,classmb =~ diag.age,
nwg=T, B = mcs_adhd_ttl_gmm1)
summary(mcs_adhd_ttl_gmm3)


mcs_adhd_ttl_gmm4 <- hlme(value ~ Sweep, subject = "numericID", random=~1,ng = 4, data = MCS_adhd_long_sdq_total, mixture = ~ Sweep,classmb =~ diag.age, nwg=T, B = mcs_adhd_ttl_gmm1)
summary(mcs_adhd_ttl_gmm4)
fit_ind_ttl <- summarytable(mcs_adhd_ttl_gmm1, mcs_adhd_ttl_gmm2, mcs_adhd_ttl_gmm3, mcs_adhd_ttl_gmm4,which = c("AIC","BIC","SABIC","entropy","%class","npm","loglik"))

 
#fit_ind <- summarytable(mcs_adhd_ttl_gmm1, mcs_adhd_ttl_gmm2, mcs_adhd_ttl_gmm3)

```

## total graphs
```{r}
age <- c("3","5","7","11","14","17")

MCS_adhd_long_sdq_total$numericID <- as.character(MCS_adhd_long_sdq_total$numericID)
mcs_adhd_ttl_people2 <- as.data.frame(mcs_adhd_ttl_gmm2$pprob[,1:2])
MCS_adhd_long_sdq_total$class <- factor(mcs_adhd_ttl_people2$class[sapply(MCS_adhd_long_sdq_total$numericID, function(x) which(mcs_adhd_ttl_people2$numericID==x))])
my_colors <- brewer.pal(12, "Paired")[c(4,10)]
breaks = seq(min(as.numeric(MCS_adhd_long_sdq_total$Sweep)),max(as.numeric(MCS_adhd_long_sdq_total$Sweep)), length.out = 6)
p_mcs_adhd_ttl_gmm2 <- ggplot(MCS_adhd_long_sdq_total , aes(x = as.numeric(Sweep.age), y = value, group=numericID, colour=class)) + geom_line(size = 0.1) + geom_smooth(aes(group=class), method="loess", size=2, se=T)  + scale_y_continuous(limits = c(0,40)) + scale_x_continuous(breaks = as.numeric(age),labels = age) + labs(x="Age(years)",y="SDQ Total Score",colour="Latent Class") +scale_colour_manual(values = my_colors)+ theme_classic() +theme(legend.position = "none")
suppressWarnings(print(p_mcs_adhd_ttl_gmm2))



```





```{r}
my_colors_stack <- brewer.pal(12, "Paired")[c(3,4,9,10)]
legend_labels <- c("Class 1-Male", "Class 1-Female", "Class 2-Male", "Class 2-Female")

adhd_ttl_stack <- ggplot(MCS_adhd_long_sdq_total,  aes(x = factor(diag.age), fill = interaction(Sex,class))) +
  geom_bar(position="fill") + scale_y_continuous(labels = scales::percent) +
  labs(x = "Diagnosis Age", y = "Percentage") + scale_fill_manual(values = my_colors_stack, labels = legend_labels, name = "Class - Sex")+
  theme_minimal() + theme(legend.position = "none")

adhd_ttl_stack

```


## Emotional symptoms GMM

```{r}
mcs_adhd_emo_gmm1 <- hlme(value ~ Sweep, subject = "numericID", random=~1, ng = 1, data =
MCS_adhd_long_sdq_emo)
#summary(mcs_adhd_emo_gmm1)


mcs_adhd_emo_gmm2 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 2, data = MCS_adhd_long_sdq_emo, mixture = ~ Sweep, classmb =~ diag.age,
nwg=T, B = mcs_adhd_emo_gmm1)
#summary(mcs_adhd_emo_gmm2)


mcs_adhd_emo_gmm3 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 3, data = MCS_adhd_long_sdq_emo, mixture = ~ Sweep,classmb =~ diag.age,
nwg=T, B = mcs_adhd_emo_gmm1)
#summary(mcs_adhd_emo_gmm3)
# fit_ind <- summarytable(mcs_adhd_emo_gmm1, mcs_adhd_emo_gmm2, mcs_adhd_emo_gmm3)
mcs_adhd_emo_gmm4 <- hlme(value ~ Sweep, subject = "numericID", random=~1,ng = 4, data = MCS_adhd_long_sdq_emo, mixture = ~ Sweep,classmb =~ diag.age, nwg=T, B = mcs_adhd_emo_gmm1)
summary(mcs_adhd_emo_gmm4)
fit_ind_emo <- summarytable(mcs_adhd_emo_gmm1, mcs_adhd_emo_gmm2, mcs_adhd_emo_gmm3, mcs_adhd_emo_gmm4,which = c("AIC","BIC","SABIC","entropy","%class","npm","loglik"))
# loglik -1088.291  npm 19 BIC 2261.867  %c1 32.58427 %c2 42.69663 %c3  15.730337  %c4 8.988764, worse fit than gmm3, so it's omitted
```




## emo graphs
```{r}
MCS_adhd_long_sdq_emo$numericID <- as.character(MCS_adhd_long_sdq_emo$numericID)
mcs_adhd_emo_people2 <- as.data.frame(mcs_adhd_emo_gmm2$pprob[,1:2])
MCS_adhd_long_sdq_emo$class <- factor(mcs_adhd_emo_people2$class[sapply(MCS_adhd_long_sdq_emo$numericID, function(x) which(mcs_adhd_emo_people2$numericID==x))])
my_colors <- brewer.pal(12, "Paired")[c(4,10)]

p_mcs_adhd_emo_gmm2 <- ggplot(MCS_adhd_long_sdq_emo , aes(x = as.numeric(Sweep.age), y = value, group=numericID, colour=class)) + geom_line(size = 0.1) + geom_smooth(aes(group=class), method="loess", size=2, se=T)  + scale_y_continuous(limits = c(0,10)) + scale_x_continuous(breaks = as.numeric(age),labels = age) + labs(x="Age(years)",y="Emotional Symptoms Score",colour="Latent Class") +scale_colour_manual(values = my_colors)+ theme_classic() +theme(legend.position = "none")
suppressWarnings(print(p_mcs_adhd_emo_gmm2))
```

```{r}
my_colors_stack <- brewer.pal(12, "Paired")[c(3,4,9,10)]
legend_labels <- c("Class 1-Male", "Class 1-Female", "Class 2-Male", "Class 2-Female")

adhd_emo_stack <- ggplot(MCS_adhd_long_sdq_emo,  aes(x = factor(diag.age), fill = interaction(Sex,class))) +
  geom_bar(position="fill") + scale_y_continuous(labels = scales::percent) +
  labs(x = "Diagnosis Age", y = "Percentage") + scale_fill_manual(values = my_colors_stack, labels = legend_labels, name = "Class - Sex")+
  theme_minimal() + theme(legend.position = "none")

adhd_emo_stack

```

```{r}
mcs_emo_people3 <- as.data.frame(mcs_adhd_emo_gmm3$pprob[,1:2])
MCS_adhd_long_sdq_emo$group_mcs_adhd_emo_gmm3 <- factor(mcs_emo_people3$class[sapply(MCS_adhd_long_sdq_emo$numericID, function(x) which(mcs_emo_people3$numericID==x))])
p_mcs_adhd_emo_gmm3 <- ggplot(MCS_adhd_long_sdq_emo , aes(Sweep, value, group=numericID, colour=group_mcs_adhd_emo_gmm3)) + geom_line(alpha = 0.2) + geom_smooth(aes(group=group_mcs_adhd_emo_gmm3), method="loess", size=2.5, se=F, alpha = 0.9)  + scale_y_continuous(limits = c(0,10)) + scale_x_continuous(labels = age) + labs(x="Age(years)",y="SDQ_emo",colour="Latent Class") 
p_mcs_adhd_emo_gmm3_s <- ggplot(MCS_adhd_long_sdq_emo , aes(Sweep, value, group=numericID, colour=group_mcs_adhd_emo_gmm3)) + geom_smooth(aes(group=numericID, colour=group_mcs_adhd_emo_gmm3),size=0.5, se=F) + geom_smooth(aes(group=group_mcs_adhd_emo_gmm3), method="loess", size=2, se=T)  + scale_y_continuous(limits = c(0,10)) + scale_x_continuous(labels = age) + labs(x="Age(years)",y="SDQ_emo",colour="Latent Class") 

suppressWarnings(print(p_mcs_adhd_emo_gmm3))
suppressWarnings(print(p_mcs_adhd_emo_gmm3_s))


```



## Conduct problems GMM
```{r}
mcs_adhd_con_gmm1 <- hlme(value ~ Sweep, subject = "numericID", random=~1, ng = 1, data =
MCS_adhd_long_sdq_con)
summary(mcs_adhd_con_gmm1)


mcs_adhd_con_gmm2 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 2, data = MCS_adhd_long_sdq_con, mixture = ~ Sweep, classmb =~ diag.age,
nwg=T, B = mcs_adhd_con_gmm1)
summary(mcs_adhd_con_gmm2)


mcs_adhd_con_gmm3 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 3, data = MCS_adhd_long_sdq_con, mixture = ~ Sweep,classmb =~ diag.age,
nwg=T, B = mcs_adhd_con_gmm1)
summary(mcs_adhd_con_gmm3)
#fit_ind <- summarytable(mcs_adhd_con_gmm1, mcs_adhd_con_gmm2, mcs_adhd_con_gmm3)
mcs_adhd_con_gmm4 <- hlme(value ~ Sweep, subject = "numericID", random=~1,ng = 4, data = MCS_adhd_long_sdq_con, mixture = ~ Sweep,classmb =~ diag.age, nwg=T, B = mcs_adhd_con_gmm1)
summary(mcs_adhd_con_gmm4)
fit_ind_con <- summarytable(mcs_adhd_con_gmm1, mcs_adhd_con_gmm2, mcs_adhd_con_gmm3, mcs_adhd_con_gmm4,which = c("AIC","BIC","SABIC","entropy","%class","npm","loglik"))

```


## con graphs
```{r}
MCS_adhd_long_sdq_con$numericID <- as.character(MCS_adhd_long_sdq_con$numericID)
mcs_adhd_con_people2 <- as.data.frame(mcs_adhd_con_gmm2$pprob[,1:2])
MCS_adhd_long_sdq_con$class <- factor(mcs_adhd_con_people2$class[sapply(MCS_adhd_long_sdq_con$numericID, function(x) which(mcs_adhd_con_people2$numericID==x))])

my_colors <- brewer.pal(12, "Paired")[c(4,10)]

p_mcs_adhd_con_gmm2 <- ggplot(MCS_adhd_long_sdq_con , aes(x = as.numeric(Sweep.age), y = value, group=numericID, colour=class)) + geom_line(size = 0.1) + geom_smooth(aes(group=class), method="loess", size=2, se=T)  + scale_y_continuous(limits = c(0,10)) + scale_x_continuous(breaks = as.numeric(age),labels = age) + labs(x="Age(years)",y="Conduct Problems Score",colour="Latent Class") +scale_colour_manual(values = my_colors)+ theme_classic() +theme(legend.position = "none")
suppressWarnings(print(p_mcs_adhd_con_gmm2))
```
```{r}
#MCS_adhd_long_sdq_con$numericID <- as.character(MCS_adhd_long_sdq_con$numericID)
mcs_adhd_con_people3 <- as.data.frame(mcs_adhd_con_gmm3$pprob[,1:2])
MCS_adhd_long_sdq_con$class3 <- factor(mcs_adhd_con_people3$class[sapply(MCS_adhd_long_sdq_con$numericID, function(x) which(mcs_adhd_con_people3$numericID==x))])

my_colors <- brewer.pal(12, "Paired")[c(1,4,10)]

p_mcs_adhd_con_gmm3 <- ggplot(MCS_adhd_long_sdq_con , aes(x = as.numeric(Sweep.age), y = value, group=numericID, colour=class)) + geom_line(size = 0.1) + geom_smooth(aes(group=class), method="loess", size=2, se=T)  + scale_y_continuous(limits = c(0,10)) + scale_x_continuous(breaks = as.numeric(age),labels = age) +labs(x="Age(years)",y="Conduct Problems Score",colour="Latent Class") +scale_colour_manual(values = my_colors)+ theme_classic() +theme(legend.position = "none")
suppressWarnings(print(p_mcs_adhd_con_gmm3))
```

```{r}
my_colors_stack <- brewer.pal(12, "Paired")[c(3,4,9,10)]
legend_labels <- c("Class 1-Male", "Class 1-Female", "Class 2-Male", "Class 2-Female")

adhd_con_stack <- ggplot(MCS_adhd_long_sdq_con,  aes(x = factor(diag.age), fill = interaction(Sex,class))) +
  geom_bar(position="fill") + scale_y_continuous(labels = scales::percent) +
  labs(x = "Diagnosis Age", y = "Percentage") + scale_fill_manual(values = my_colors_stack, labels = legend_labels, name = "Class - Sex")+
  theme_minimal() + theme(legend.position = "none")

adhd_con_stack

```


## Hyperactivity and inattention GMM

```{r}
library(lcmm)
mcs_adhd_hyp_gmm1 <- hlme(value ~ Sweep, subject = "numericID", random=~1, ng = 1, data =
MCS_adhd_long_sdq_hyp)
summary(mcs_adhd_hyp_gmm1)


mcs_adhd_hyp_gmm2 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 2, data = MCS_adhd_long_sdq_hyp, mixture = ~ Sweep, classmb =~ diag.age,
nwg=T, B = mcs_adhd_hyp_gmm1)
summary(mcs_adhd_hyp_gmm2)


mcs_adhd_hyp_gmm3 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 3, data = MCS_adhd_long_sdq_hyp, mixture = ~ Sweep,classmb =~ diag.age,
nwg=T, B = mcs_adhd_hyp_gmm1)
summary(mcs_adhd_hyp_gmm3)
#fit_ind <- summarytable(mcs_adhd_hyp_gmm1, mcs_adhd_hyp_gmm2, mcs_adhd_hyp_gmm3)
 mcs_adhd_hyp_gmm4 <- hlme(value ~ Sweep, subject = "numericID", random=~1,ng = 4, data = MCS_adhd_long_sdq_hyp, mixture = ~ Sweep,classmb =~ diag.age, nwg=T, B = mcs_adhd_hyp_gmm1)
summary(mcs_adhd_hyp_gmm4)
fit_ind_hyp <- summarytable(mcs_adhd_hyp_gmm1, mcs_adhd_hyp_gmm2, mcs_adhd_hyp_gmm3, mcs_adhd_hyp_gmm4,which = c("AIC","BIC","SABIC","entropy","%class","npm","loglik"))

```


## hyp graphs
```{r}
MCS_adhd_long_sdq_hyp$numericID <- as.character(MCS_adhd_long_sdq_hyp$numericID)
mcs_adhd_hyp_people2 <- as.data.frame(mcs_adhd_hyp_gmm2$pprob[,1:2])
MCS_adhd_long_sdq_hyp$class <- factor(mcs_adhd_hyp_people2$class[sapply(MCS_adhd_long_sdq_hyp$numericID, function(x) which(mcs_adhd_hyp_people2$numericID==x))])
my_colors <- brewer.pal(12, "Paired")[c(4,10)]

p_mcs_adhd_hyp_gmm2 <- ggplot(MCS_adhd_long_sdq_hyp ,aes(x = as.numeric(Sweep.age), y = value, group=numericID, colour=class)) + geom_line(size = 0.1) + geom_smooth(aes(group=class), method="loess", size=2, se=T)  + scale_y_continuous(limits = c(0,10)) + scale_x_continuous(breaks = as.numeric(age),labels = age) + labs(x="Age(years)",y="Hyperactivity/Inattention Score",colour="Latent Class") +scale_colour_manual(values = my_colors)+ theme_classic() +theme(legend.position = "none")
suppressWarnings(print(p_mcs_adhd_hyp_gmm2))
```

```{r}
my_colors_stack <- brewer.pal(12, "Paired")[c(3,4,9,10)]
legend_labels <- c("Class 1-Male", "Class 1-Female", "Class 2-Male", "Class 2-Female")

adhd_hyp_stack <- ggplot(MCS_adhd_long_sdq_hyp,  aes(x = factor(diag.age), fill = interaction(Sex,class))) +
  geom_bar(position="fill") + scale_y_continuous(labels = scales::percent) +
  labs(x = "Diagnosis Age", y = "Percentage") + scale_fill_manual(values = my_colors_stack, labels = legend_labels, name = "Class - Sex")+
  theme_minimal() + theme(legend.position = "none")

adhd_hyp_stack

```


## Peer relationship problems GMM

```{r}
mcs_adhd_peer_gmm1 <- hlme(value ~ Sweep, subject = "numericID", random=~1, ng = 1, data =
MCS_adhd_long_sdq_peer)
summary(mcs_adhd_peer_gmm1)


mcs_adhd_peer_gmm2 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 2, data = MCS_adhd_long_sdq_peer, mixture = ~ Sweep, classmb =~ diag.age,
nwg=T, B = mcs_adhd_peer_gmm1)
summary(mcs_adhd_peer_gmm2)


mcs_adhd_peer_gmm3 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 3, data = MCS_adhd_long_sdq_peer, mixture = ~ Sweep,classmb =~ diag.age,
nwg=T, B = mcs_adhd_peer_gmm1)
summary(mcs_adhd_peer_gmm3)
#fit_ind <- summarytable(mcs_adhd_peer_gmm1, mcs_adhd_peer_gmm2, mcs_adhd_peer_gmm3)
mcs_adhd_peer_gmm4 <- hlme(value ~ Sweep, subject = "numericID", random=~1,ng = 4, data = MCS_adhd_long_sdq_peer, mixture = ~ Sweep,classmb =~ diag.age, nwg=T, B = mcs_adhd_peer_gmm1)
summary(mcs_adhd_peer_gmm4)
fit_ind_peer <- summarytable(mcs_adhd_peer_gmm1, mcs_adhd_peer_gmm2, mcs_adhd_peer_gmm3, mcs_adhd_peer_gmm4, which = c("AIC","BIC","SABIC","entropy","%class"))

```


## peer graphs
```{r}
MCS_adhd_long_sdq_peer$numericID <- as.character(MCS_adhd_long_sdq_peer$numericID)
mcs_adhd_peer_people2 <- as.data.frame(mcs_adhd_peer_gmm2$pprob[,1:2])
MCS_adhd_long_sdq_peer$class <- factor(mcs_adhd_peer_people2$class[sapply(MCS_adhd_long_sdq_peer$numericID, function(x) which(mcs_adhd_peer_people2$numericID==x))])
my_colors <- brewer.pal(12, "Paired")[c(4,10)]

p_mcs_adhd_peer_gmm2 <- ggplot(MCS_adhd_long_sdq_peer , aes(x = as.numeric(Sweep.age), y = value, group=numericID, colour=class)) + geom_line(size = 0.1) + geom_smooth(aes(group=class), method="loess", size=2, se=T)  + scale_y_continuous(limits = c(0,10)) + scale_x_continuous(breaks = as.numeric(age),labels = age) + labs(x="Age(years)",y="Peer Relationship Problems Score",colour="Latent Class") +scale_colour_manual(values = my_colors)+ theme_classic() +theme(legend.position = "none")
suppressWarnings(print(p_mcs_adhd_peer_gmm2))
```

```{r}
my_colors_stack <- brewer.pal(12, "Paired")[c(3,4,9,10)]
legend_labels <- c("Class 1-Male", "Class 1-Female", "Class 2-Male", "Class 2-Female")

adhd_peer_stack <- ggplot(MCS_adhd_long_sdq_peer,  aes(x = factor(diag.age), fill = interaction(Sex,class))) +
  geom_bar(position="fill") + scale_y_continuous(labels = scales::percent) +
  labs(x = "Diagnosis Age", y = "Percentage") + scale_fill_manual(values = my_colors_stack, labels = legend_labels, name = "Class - Sex")+
  theme_minimal() + theme(legend.position = "none")

adhd_peer_stack

```

## Prosocial behaviour GMM

```{r}
mcs_adhd_pro_gmm1 <- hlme(value ~ Sweep, subject = "numericID", random=~1, ng = 1, data =
MCS_adhd_long_sdq_pro)
summary(mcs_adhd_pro_gmm1)


mcs_adhd_pro_gmm2 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 2, data = MCS_adhd_long_sdq_pro, mixture = ~ Sweep, classmb =~ diag.age,
nwg=T, B = mcs_adhd_pro_gmm1)
summary(mcs_adhd_pro_gmm2)


mcs_adhd_pro_gmm3 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 3, data = MCS_adhd_long_sdq_pro, mixture = ~ Sweep,classmb =~ diag.age,
nwg=T, B = mcs_adhd_pro_gmm1)
summary(mcs_adhd_pro_gmm3)
#fit_ind <- summarytable(mcs_adhd_pro_gmm1, mcs_adhd_pro_gmm2, mcs_adhd_pro_gmm3)
mcs_adhd_pro_gmm4 <- hlme(value ~ Sweep, subject = "numericID", random=~1,ng = 4, data = MCS_adhd_long_sdq_pro, mixture = ~ Sweep,classmb =~ diag.age, nwg=T, B = mcs_adhd_pro_gmm1)
summary(mcs_adhd_pro_gmm4)
fit_ind_pro <- summarytable(mcs_adhd_pro_gmm1, mcs_adhd_pro_gmm2, mcs_adhd_pro_gmm3, mcs_adhd_pro_gmm4, which = c("AIC","BIC","SABIC","entropy","%class"))

```
```{r}
MCS_adhd_long_sdq_pro$numericID <- as.character(MCS_adhd_long_sdq_pro$numericID)
mcs_adhd_pro_people2 <- as.data.frame(mcs_adhd_pro_gmm2$pprob[,1:2])
MCS_adhd_long_sdq_pro$class <- factor(mcs_adhd_pro_people2$class[sapply(MCS_adhd_long_sdq_pro$numericID, function(x) which(mcs_adhd_pro_people2$numericID==x))])
my_colors <- brewer.pal(12, "Paired")[c(4,10)]

p_mcs_adhd_pro_gmm2 <- ggplot(MCS_adhd_long_sdq_pro ,aes(x = as.numeric(Sweep.age), y = value, group=numericID, colour=class)) + geom_line(size = 0.1) + geom_smooth(aes(group=class), method="loess", size=2, se=T)  + scale_y_continuous(limits = c(0,10)) + scale_x_continuous(breaks = as.numeric(age),labels = age) + labs(x="Age(years)",y="Prosocial Behaviours Score",colour="Latent Class") +scale_colour_manual(values = my_colors)+ theme_classic() +theme(legend.position = "none")
suppressWarnings(print(p_mcs_adhd_pro_gmm2))


```

```{r}

legend_labels <- c("Class 1-Male", "Class 1-Female", "Class 2-Male", "Class 2-Female")

adhd_pro_stack <- ggplot(MCS_adhd_long_sdq_pro,  aes(x = factor(diag.age), fill = interaction(Sex,class))) +
  geom_bar(position="fill") + scale_y_continuous(labels = scales::percent) +
  labs(x = "Diagnosis Age", y = "Percentage") + scale_fill_manual(values = my_colors_stack, labels = legend_labels, name = "Class - Sex")+
  theme_minimal() + theme(legend.position = "none")

adhd_pro_stack

```

```{r}
fit_ind_ttl
fit_ind_emo
fit_ind_con
fit_ind_hyp
fit_ind_peer
fit_ind_pro

```


```{r}
pdf("/Users/zhangxinhe/Documents/who recieves a diagnosis/Figures FINAL/MCS_adhd_SDQ_gmm_latent_groups.pdf", width = 10,height = 6)
print(p_mcs_adhd_ttl_gmm2) 
print(p_mcs_adhd_emo_gmm2) 
print(p_mcs_adhd_con_gmm2) 
print(p_mcs_adhd_hyp_gmm2) 
print(p_mcs_adhd_peer_gmm2) 
print(p_mcs_adhd_pro_gmm2) 

dev.off()
```

```{r}
pdf("/Users/zhangxinhe/Documents/who recieves a diagnosis/Figures FINAL/MCS_adhd_SDQ_gmm_stack_bar.pdf", width = 10,height = 6)
print(adhd_ttl_stack) 
print(adhd_emo_stack) 
print(adhd_con_stack) 
print(adhd_hyp_stack) 
print(adhd_peer_stack) 
print(adhd_pro_stack) 

dev.off()
```
# Group membership
```{r}
MCS_adhd_wide_sdq_emo$numericID <- as.character(MCS_adhd_wide_sdq_emo$numericID)
mcs_adhd_ttl_people2$numericID <- as.character(mcs_adhd_ttl_people2$numericID)
mcs_adhd_emo_people2$numericID <- as.character(mcs_adhd_emo_people2$numericID)
mcs_adhd_con_people2$numericID <- as.character(mcs_adhd_con_people2$numericID)
mcs_adhd_hyp_people2$numericID <- as.character(mcs_adhd_hyp_people2$numericID)
mcs_adhd_peer_people2$numericID <- as.character(mcs_adhd_peer_people2$numericID)
mcs_adhd_pro_people2$numericID <- as.character(mcs_adhd_pro_people2$numericID)
mcs_adhd_group_df_list_2 <- list(MCS_adhd_wide_sdq_emo[,c("numericID","diag.age","Sex")], mcs_adhd_ttl_people2,mcs_adhd_emo_people2,mcs_adhd_con_people2,mcs_adhd_hyp_people2, mcs_adhd_peer_people2, mcs_adhd_pro_people2)

mcs_adhd_group_membership_2 <- mcs_adhd_group_df_list_2 %>% reduce(full_join, by= 'numericID') 

colnames(mcs_adhd_group_membership_2)[4:9] <- c("ttl","emo","con","hyp","peer","pro")
mcs_adhd_group_membership_2$Sex <- ifelse(mcs_adhd_group_membership_2$Sex=="Male", 1, 2)
```



```{r}
mcs_adhd_ttl_gmm_stack <- ggplot(mcs_adhd_group_membership_2,  aes(x = factor(diag.age), fill = factor(ttl))) +
  geom_bar(position="fill") + scale_y_continuous(labels = scales::percent) +
  labs(x = "diagnosis age", y = "percentage", title = "distribution of latent group membership of ttl score by diagnosis ages") + scale_fill_brewer(labels=c('decreasing difficulties', 'increasing difficulties'), name = "latent group membership", palette = "Pastel1")

mcs_adhd_ttl_gmm_stack
```


```{r}
mcs_adhd_emo_gmm_stack <- ggplot(mcs_adhd_group_membership_2,  aes(x = factor(diag.age), fill = factor(emo))) +
  geom_bar(position="fill") + scale_y_continuous(labels = scales::percent) +
  labs(x = "diagnosis age", y = "percentage", title = "distribution of latent group membership of emo score by diagnosis ages") + scale_fill_brewer(labels=c('decreasing difficulties', 'increasing difficulties'), name = "latent group membership", palette = "Pastel1")
```


```{r}
mcs_adhd_con_gmm_stack <- ggplot(mcs_adhd_group_membership_2,  aes(x = factor(diag.age), fill = factor(con))) +
  geom_bar(position="fill") + scale_y_continuous(labels = scales::percent) +
  labs(x = "diagnosis age", y = "percentage", title = "distribution of latent group membership of con score by diagnosis ages") + scale_fill_brewer(labels=c('decreasing difficulties', 'increasing difficulties'), name = "latent group membership", palette = "Pastel1")
```


```{r}
mcs_adhd_hyp_gmm_stack <- ggplot(mcs_adhd_group_membership_2,  aes(x = factor(diag.age), fill = factor(hyp))) +
  geom_bar(position="fill") + scale_y_continuous(labels = scales::percent) +
  labs(x = "diagnosis age", y = "percentage", title = "distribution of latent group membership of hyp score by diagnosis ages") + scale_fill_brewer(labels=c('decreasing difficulties', 'increasing difficulties'), name = "latent group membership", palette = "Pastel1")
mcs_adhd_hyp_gmm_stack
```


```{r}
mcs_adhd_peer_gmm_stack <- ggplot(mcs_adhd_group_membership_2,  aes(x = factor(diag.age), fill = factor(peer))) +
  geom_bar(position="fill") + scale_y_continuous(labels = scales::percent) +
  labs(x = "diagnosis age", y = "percentage", title = "distribution of latent group membership of peer score by diagnosis ages") + scale_fill_brewer(labels=c('decreasing difficulties', 'increasing difficulties'), name = "latent group membership", palette = "Pastel1")
mcs_adhd_peer_gmm_stack 
```


```{r}
mcs_adhd_pro_gmm_stack <- ggplot(mcs_adhd_group_membership_2,  aes(x = factor(diag.age), fill = factor(pro))) +
  geom_bar(position="fill") + scale_y_continuous(labels = scales::percent) +
  labs(x = "diagnosis age", y = "percentage", title = "distribution of latent group membership of pro score by diagnosis ages") + scale_fill_brewer(labels=c('decreasing prosocialness', 'increasing prosocialness'), name = "latent group membership", palette = "Pastel1")
mcs_adhd_pro_gmm_stack
```

```{r}
pdf("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_adhd_SDQ_n_subscales_gmm_diag_age_stacked.pdf")
print(mcs_adhd_ttl_gmm_stack) 
print(mcs_adhd_emo_gmm_stack) 
print(mcs_adhd_con_gmm_stack) 
print(mcs_adhd_hyp_gmm_stack) 
print(mcs_adhd_peer_gmm_stack) 
print(mcs_adhd_pro_gmm_stack) 

dev.off()
```


# Both autism and adhd
## Reshape data
```{r}
MCS_sdq_both <- MCS_sdq_both %>%
  mutate(asd.diag.age = case_when(
    ASD.Diagnosis.Age == "at W3" ~ 5,
    ASD.Diagnosis.Age == "at W4" ~ 7,
    ASD.Diagnosis.Age == "at W5" ~ 11,
    ASD.Diagnosis.Age == "at W6" ~ 14)
    )

MCS_sdq_both <- MCS_sdq_both %>%
  mutate(adhd.diag.age = case_when(
    ADHD.Diagnosis.Age == "at W3" ~ 5,
    ADHD.Diagnosis.Age == "at W4" ~ 7,
    ADHD.Diagnosis.Age == "at W5" ~ 11,
    ADHD.Diagnosis.Age == "at W6" ~ 14)
    )
MCS_both_wide_sdq_total <- MCS_sdq_both[,c("numericID","MCSID","Sex","asd.diag.age","adhd.diag.age","BEBDTOT","CEBDTOT", "DDDEBDTOT" ,"EEBDTOT","FEBDTOT","GEBDTOT")]
MCS_both_long_sdq_total <- melt(setDT(MCS_both_wide_sdq_total), id.vars = c("numericID","MCSID","Sex","asd.diag.age","adhd.diag.age"), variable.name = "sweep")

MCS_both_long_sdq_total <- MCS_both_long_sdq_total %>%
  mutate(Sweep = case_when(
    sweep == "BEBDTOT" ~ 2,
    sweep == "CEBDTOT" ~ 3,
    sweep == "DDDEBDTOT" ~ 4,
    sweep == "EEBDTOT" ~ 5,
    sweep == "FEBDTOT" ~ 6,
    sweep == "GEBDTOT" ~ 7)
    )


MCS_both_wide_sdq_emo <- MCS_sdq_both[,c("numericID","MCSID","Sex","asd.diag.age","adhd.diag.age","BEMOTION","CEMOTION", "DDEMOTION","EEMOTION","FEMOTION","GEMOTION")]
MCS_both_long_sdq_emo <- melt(setDT(MCS_both_wide_sdq_emo), id.vars = c("numericID","MCSID","Sex","diag.age"), variable.name = "sweep")
MCS_both_long_sdq_emo <- MCS_both_long_sdq_emo %>%
  mutate(Sweep = case_when(
    sweep == "BEMOTION" ~ 2,
    sweep == "CEMOTION" ~ 3,
    sweep == "DDEMOTION" ~ 4,
    sweep == "EEMOTION" ~ 5,
    sweep == "FEMOTION" ~ 6,
    sweep == "GEMOTION" ~ 7)
    )


MCS_both_wide_sdq_con <- MCS_sdq_both[,c("numericID","MCSID","Sex","asd.diag.age","adhd.diag.age","BCONDUCT","CCONDUCT","DDCONDUCT","ECONDUCT","FCONDUCT","GCONDUCT")]
MCS_both_long_sdq_con <- melt(setDT(MCS_both_wide_sdq_con), id.vars = c("numericID","MCSID","Sex","diag.age"), variable.name = "sweep")
MCS_both_long_sdq_con <- MCS_both_long_sdq_con %>%
  mutate(Sweep = case_when(
    sweep == "BCONDUCT" ~ 2,
    sweep == "CCONDUCT" ~ 3,
    sweep == "DDCONDUCT" ~ 4,
    sweep == "ECONDUCT" ~ 5,
    sweep == "FCONDUCT" ~ 6,
    sweep == "GCONDUCT" ~ 7)
    )


MCS_both_wide_sdq_hyp <- MCS_sdq_both[,c("numericID","MCSID","Sex","asd.diag.age","adhd.diag.age","BHYPER","CHYPER","DDHYPER","EHYPER","FHYPER","GHYPER")]
MCS_both_long_sdq_hyp <- melt(setDT(MCS_both_wide_sdq_hyp), id.vars = c("numericID","MCSID","Sex","diag.age"), variable.name = "sweep")
MCS_both_long_sdq_hyp <- MCS_both_long_sdq_hyp %>%
  mutate(Sweep = case_when(
    sweep == "BHYPER" ~ 2,
    sweep == "CHYPER" ~ 3,
    sweep == "DDHYPER" ~ 4,
    sweep == "EHYPER" ~ 5,
    sweep == "FHYPER" ~ 6,
    sweep == "GHYPER" ~ 7)
    )


MCS_both_wide_sdq_peer <- MCS_sdq_both[,c("numericID","MCSID","Sex","asd.diag.age","adhd.diag.age","BPEER","CPEER","DDPEER","EPEER","FPEER","GPEER")]
MCS_both_long_sdq_peer <- melt(setDT(MCS_both_wide_sdq_peer), id.vars = c("numericID","MCSID","Sex","diag.age"), variable.name = "sweep")
MCS_both_long_sdq_peer <- MCS_both_long_sdq_peer %>%
  mutate(Sweep = case_when(
    sweep == "BPEER" ~ 2,
    sweep == "CPEER" ~ 3,
    sweep == "DDPEER" ~ 4,
    sweep == "EPEER" ~ 5,
    sweep == "FPEER" ~ 6,
    sweep == "GPEER" ~ 7)
    )


MCS_both_wide_sdq_pro <- MCS_sdq_both[,c("numericID","MCSID","Sex","asd.diag.age","adhd.diag.age","BPROSOC","CPROSOC","DDPROSOC","EPROSOC","FPROSOC","GPROSOC")]
MCS_both_long_sdq_pro <- melt(setDT(MCS_both_wide_sdq_pro), id.vars = c("numericID","MCSID","Sex","diag.age"), variable.name = "sweep")
MCS_both_long_sdq_pro <- MCS_both_long_sdq_pro %>%
  mutate(Sweep = case_when(
    sweep == "BPROSOC" ~ 2,
    sweep == "CPROSOC" ~ 3,
    sweep == "DDPROSOC" ~ 4,
    sweep == "EPROSOC" ~ 5,
    sweep == "FPROSOC" ~ 6,
    sweep == "GPROSOC" ~ 7)
    )
age <- c("3","5","7","11","14","17")
```