

## Loading data

library(dplyr)
aus_b1 <- read_dta("/Users/General Release/Survey data/STATA/lsacgrb0.dta")
aus_b2 <- read_dta("/Users/General Release/Survey data/STATA/lsacgrb2.dta")
aus_b3 <- read_dta("/Users/General Release/Survey data/STATA/lsacgrb4.dta")
aus_b4 <- read_dta("/Users/General Release/Survey data/STATA/lsacgrb6.dta")
aus_b5 <- read_dta("/Users/General Release/Survey data/STATA/lsacgrb8.dta")
aus_b6 <- read_dta("/Users/General Release/Survey data/STATA/lsacgrb10.dta")
aus_b_no_autism <- read.csv("/Users/aus_b_no_autism.csv")
aus_b_autism_early <- read.csv("/Users/aus_b_autism_early.csv")
aus_b_autism_late <- read.csv("/Users/aus_b_autism_late.csv")




# Cognitive abilities

# wave 2: Drawn from the MacArthur-Bates Communicative Development Inventories-III shortened version [MCDI-III] (Fenson et al., 2007).: the higher the score the higher cognitive abilities indicated
#aus_b2_autism <- aus_b2 %>% filter(hicid %in% c(aus_b_autism_early$hicid,aus_b_autism_late$hicid))
aus_b2_iq <- aus_b2 %>% dplyr::select(hicid,bvocab,bgrammrk)
aus_b2_iq[aus_b2_iq <= 0] <- NA
#wave 3 PPVT,who am I
#aus_b3_autism <- aus_b3 %>% filter(hicid %in% c(aus_b_autism_early$hicid,aus_b_autism_late$hicid))

aus_b3_iq <- aus_b3 %>% dplyr::select(hicid,cppvt2,cwai2)
aus_b3_iq[aus_b3_iq <= 0] <- NA


#aus_b4_autism <- aus_b4 %>% filter(hicid %in% c(aus_b_autism_early$hicid,aus_b_autism_late$hicid))
#aus_b5_autism <- aus_b5 %>% filter(hicid %in% c(aus_b_autism_early$hicid,aus_b_autism_late$hicid))
#aus_b6_autism <- aus_b6 %>% filter(hicid %in% c(aus_b_autism_early$hicid,aus_b_autism_late$hicid))
#aus_b7_autism <- aus_b7 %>% filter(hicid %in% c(aus_b_autism_early$hicid,aus_b_autism_late$hicid))



aus_b4_iq <- aus_b4 %>% dplyr::select(hicid,dppvt2,dmatreas,dtlitr,dlc08a1a,dlc08a2a,dlc08a3a)
aus_b4_iq[aus_b4_iq <= 0] <- NA
aus_b4_iq_rc <- aus_b4_iq %>% mutate_at(vars(dlc08a1a,dlc08a2a,dlc08a3a),funs(6-.))


# dmrraw,dmrrawi, 8 participants used imputed scores
aus_b5_iq <- aus_b5 %>% dplyr::select(hicid,eppvt2,ematreas,etlitcr,etmathcr,elc08t1b,elc08t2b,elc08t3b)
aus_b6_iq <- aus_b6 %>% dplyr::select(hicid,fmatreas,ftlitcr,ftmathcr,flc08t1b,flc08t2b,flc08t3b)
aus_b7_iq <- aus_b7 %>% dplyr::select(hicid,gtlitcr,glc08t1b)
aus_b4_iq[aus_b4_iq <= 0] <- NA
aus_b5_iq[aus_b5_iq <= 0] <- NA
aus_b6_iq[aus_b6_iq <= 0] <- NA
aus_b7_iq[aus_b7_iq <= 0] <- NA


library(corrplot)
aus_b_iq_list <- list(aus_b2_iq,aus_b3_iq,aus_b4_iq_rc,aus_b5_iq,aus_b6_iq,aus_b7_iq)
aus_b_iq_sum <- aus_b_iq_list %>% reduce(full_join, by= c('hicid')) 

aus_b_iq_complete_case <- colSums(!is.na(aus_b_iq_sum))
aus_b_iq_complete_case




cor(aus_b_iq_sum[2:26], use = "complete.obs")
aus_b_iq_corrplot <- corrplot.mixed(cor(aus_b_iq_sum[2:26], use = "complete.obs"), upper = 'circle', 
                            lower = "number",
                            tl.pos = "lt", 
                            tl.col = "black",
                            tl.cex = 0.8,
                            addCoefasPercent = TRUE,
                            number.cex=0.8)
# multicollinearity: pairs of variables with correlations higher than 0.7, we remove those with less complete cases within the pairs.
# bvocab,bgrammrk: remove bgrammrk
# bvocab, dtlitr: remove dtlitr
# etmathcr,etlitcr, elc08t1b elc08t3b,elc08t2b: remove etlitcr
# dmatreas,ematreas :remove dmatreas
# flc08t1b, ftlitcr:remove ftlitcr
# flc08t3b,dmatreas:remove flc08t3b
# flc08t3b,flc08t1b,flc08t2b,ftmathcr
# gtlitcr glc08t1b : remove glc08t1b




columns_to_remove <- c("bgrammrk","dtlitr","etlitcr","dlc08a1a", "dlc08a2a","elc08t2b","elc08t3b","etmathcr","dmatreas","ftlitcr","flc08t2b", "flc08t3b","glc08t1b","ftmathcr")
aus_b_iq_mcrm <- aus_b_iq_sum %>% dplyr::select(-all_of(columns_to_remove))
aus_b_iq_corrplot_mcrm <- corrplot.mixed(cor(aus_b_iq_mcrm[2:12], use = "complete.obs"), upper = 'circle', 
                            lower = "number",
                            tl.pos = "lt", 
                            tl.col = "black",
                            tl.cex = 0.8,
                            addCoefasPercent = TRUE,
                            number.cex=0.8)
#remove bgrammrk
# bvocab, dtlitr: remove dtlitr
# etmathcr,etlitcr, elc08t1b elc08t3b,elc08t2b: remove etlitcr
# dmatreas,ematreas :remove dmatreas
# flc08t1b, ftlitcr:remove ftlitcr
# flc08t3b,dmatreas:remove flc08t3b
# flc08t3b,flc08t1b,flc08t2b,ftmathcr
# gtlitcr glc08t1b : remove glc08t1b





aus_b_iq_mcrm_complete <- aus_b_iq_mcrm %>% na.omit


aus_b_pc <- prcomp(aus_b_iq_mcrm_complete[2:12], center = TRUE, scale = TRUE)
aus_b_summary_pc <- summary(aus_b_pc)
aus_b_iq_pca_summary <- as.data.frame(aus_b_summary_pc$importance)
#view(aus_b_summary_pc$rotation) # PC1 proportion of variance: 0.372680
aus_b_iq_pc_score <- as.data.frame(aus_b_summary_pc$x)


aus_b_iq_pca <- cbind(aus_b_iq_mcrm_complete$hicid,aus_b_iq_pc_score)
colnames(aus_b_iq_pca)[1]  <- "hicid"
aus_b_iq_autism <- aus_b_iq_pca %>% filter(hicid %in% c(aus_b_autism_early$hicid,aus_b_autism_late$hicid))






aus_b_eth <- aus_b1 %>% select(hicid,zf02m1,zf09am,af11am,zf12am,zf09af,af11af,zf12af,af11m1)
aus_country <- read.csv("/Users/Country.csv")
merged_df <- merge(aus_b_eth, aus_country, by.x = "zf09am", by.y = "Code", all.x = TRUE)
merged_df <- merge(merged_df, aus_country, by.x = "zf09af", by.y = "Code", all.x = TRUE, suffixes = c("_mother", "_father"))



autism_country <- merged_df %>% filter(hicid %in% c(aus_b_autism_early$hicid, aus_b_autism_late$hicid))
mother_country <- as.data.frame(table(merged_df$Country_father))
father_country <- as.data.frame(table(merged_df$Country_mother))



aus_b_country_autism_early <- merged_df %>% filter(hicid %in% aus_b_autism_early$hicid)
aus_b_country_autism_late <- merged_df %>% filter(hicid %in% aus_b_autism_late$hicid)
early_mother_country <- as.data.frame(table(aus_b_country_autism_early$Country_father))
early_father_country <- as.data.frame(table(aus_b_country_autism_early$Country_mother))
late_mother_country <- as.data.frame(table(aus_b_country_autism_late$Country_father))
late_father_country <- as.data.frame(table(aus_b_country_autism_late$Country_mother))




# Eth: 1- Australian (not Indigenous);2-Anglo/European; 3-Visible Minority; 4-Indigenous (Aboriginal or Torres Strait Islander) 
# https://acamh.onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2Fjcpp.13410&file=jcpp13410-sup-0001-Supinfo.pdf 
# https://acamh.onlinelibrary.wiley.com/doi/full/10.1111/jcpp.13410
# based on where parents were born, what languages they speak at home/
# top-down approach: one parent’s minority status ‘trumped’ the other parents’ majority status where applicable
aus_b_eth <- read.csv("/Users/ethnicity_coding.csv")


# "age when giving birth"

# There is no mother's age at giving birth question, but there is a question on mother's age last birthday at B1 and K1, which could reflect the distribution of mothers' ages in the cohort
aus_b_ma <- aus_b1 %>% select(hicid, af03am)
aus_b_eth_ma <- merge(aus_b_eth, aus_b_ma, by = "hicid")


#cf03cm (K cohort)



# SES

aus_b1_ses <- aus_b1 %>% dplyr::select(hicid,afd08a1,afd08a3a,afd08b1,afd08b3a,apw02a1,apw02a2,apw02b1,apw02b2,afn05,anpeople)

aus_b1_ses <- aus_b1_ses %>%
  mutate(afn05 = ifelse(afn05 == -99, 99, afn05))

aus_b1_ses[aus_b1_ses <= 0] <- NA

aus_b1_ses <- aus_b1_ses %>% mutate(afn_num = case_when(afn05 == 1 ~ 2400,
            afn05 == 2 ~ 2200,
            afn05 == 3 ~ 2000,
            afn05 == 4 ~ 1500,
            afn05 == 5 ~ 1000,
            afn05 == 6 ~ 800,
            afn05 == 7 ~ 700,
            afn05 == 8 ~ 600,
            afn05 == 9 ~ 500,
            afn05 == 10 ~ 400,
            afn05 == 11 ~ 300,
            afn05 == 12 ~ 200,
            afn05 == 13 ~ 100,
            afn05 == 14 ~ 50,
            afn05 == 15 ~ 1,
            afn05 == 0 ~ 0,
            afn05 == 99 ~ -1))
aus_b1_ses <- aus_b1_ses %>% 
  mutate(afn_percap = afn_num/anpeople)




aus_b1_ses <- aus_b1_ses %>%
  mutate(p1_edu = ifelse(afd08a3a == 6|is.na(afd08a3a),
    ifelse(afd08a1 == 1, 6,
      ifelse(afd08a1 %in% c(2, 3, 4, 5, 7), 7,
        ifelse(afd08a1 == 6, 8, NA)
      )
    ),
    afd08a3a
  ))
aus_b1_ses <- aus_b1_ses %>%
  mutate(p2_edu = ifelse(afd08b3a == 6|is.na(afd08b3a),
    ifelse(afd08b1 == 1, 6,
      ifelse(afd08b1 %in% c(2, 3, 4, 5, 7), 7,
        ifelse(afd08b1 == 6, 8, NA)
      )
    ),
    afd08b3a
  ))
# coded highest educational qualification


aus_b1_ses <- aus_b1_ses %>%
  mutate(parent_edu = 9 - pmin(p1_edu, p2_edu))

# recoded (9-x) to let higher value represent higher qualification
# 1- never attended school; 2- below high school; 3- completed high school; 4- certificate; 5- Advanced diploma/diploma; 6- Bachelor degree;7- Graduate diploma/certificate; 8- Postgraduate degree






aus_b1_ses <- aus_b1_ses %>% mutate(p1_work= case_when
                                    (apw02a1==1|apw02a2==1 ~ 1,
                                    apw02a1==2&apw02a2==2 ~ 2,
                                    apw02a1 %in% c(3,4) | apw02a2 == 4 ~ 3,
                                      TRUE ~ NA
                                    ))


aus_b1_ses <- aus_b1_ses %>% mutate(p2_work= case_when
                                    (apw02b1==1|apw02b2==1 ~ 1,
                                    apw02b1==2&apw02b2==2 ~ 2,
                                    apw02b1 %in% c(3,4) | apw02b2 == 4 ~ 3,
                                      TRUE ~ NA
                                    ))
aus_b1_ses <- aus_b1_ses %>% mutate(p_work = ifelse(
                                    p1_work == 1 | p2_work == 1, 2,
                                    1
))

# 1 - both parents unemployed or out of labour force; 2- at least one parent employed



aus_b1_ses_final <- aus_b1_ses %>% dplyr::select(hicid,afn_percap,parent_edu,p_work)
cor(aus_b1_ses_final[2:4], use = "complete.obs")
aus_b1_ses_corrplot <- corrplot.mixed(cor(aus_b1_ses_final[2:4], use = "complete.obs"), upper = 'circle', 
                            lower = "number",
                            tl.pos = "lt", 
                            tl.col = "black",
                            tl.cex = 0.8,
                            addCoefasPercent = TRUE,
                            number.cex=0.8)


aus_b_ses_complete <- aus_b1_ses_final %>% na.omit


aus_b_ses_pc <- prcomp(aus_b_ses_complete[2:4], center = TRUE, scale = TRUE)
aus_b_ses_summary_pc <- summary(aus_b_ses_pc)
aus_b_ses_pca_summary <- as.data.frame(aus_b_ses_summary_pc$importance)
#view(aus_b_ses_summary_pc$rotation) # PC1 proportion of variance: 0.496000
aus_b_ses_pc_score <- as.data.frame(aus_b_ses_summary_pc$x)


aus_b_ses_pca <- cbind(aus_b_ses_complete$hicid,aus_b_ses_pc_score)
colnames(aus_b_ses_pca)[1]  <- "hicid"
aus_b_ses_autism <- aus_b_ses_pca %>% filter(hicid %in% c(aus_b_autism_early$hicid,aus_b_autism_late$hicid))


# Deprivation


# MCS: income, health, educationtraining, employment
# Hardship and homelessness
# vergtable/fruid supply, 
# victimisation and bullying!?, regular school absence, homelessness 
# https://www.aracy.org.au/publications-resources/command/download_file/id/384/filename/ARACY_Measuring_child_deprivation_and_opportunity_in_Australia.pdf
# only used scales at the first wave they were used to maintain a large sample
aus_b4_dep <- aus_b4 %>% select(hicid,dhshipb,dhb21a1a1,dhb21a1b1,dhb21a1c1,dpc48a1a)
aus_b5_dep <- aus_b5 %>% select(hicid,evictim,ebully,eho11p1)
aus_b_dep <- merge(aus_b4_dep, aus_b5_dep, by = "hicid")
aus_b_dep[aus_b_dep < 0] <- NA


aus_b_dep <- aus_b_dep %>% mutate_at(vars(dhb21a1a1,dhb21a1b1,dhb21a1c1), funs(4-.))
aus_b_dep$eho11p1[aus_b_dep$eho11p1 == 2] <- 0







cor(aus_b_dep[2:9], use = "complete.obs")
aus_b_dep_corrplot <- corrplot.mixed(cor(aus_b_dep[2:9], use = "complete.obs"), upper = 'circle', 
                            lower = "number",
                            tl.pos = "lt", 
                            tl.col = "black",
                            tl.cex = 0.8,
                            addCoefasPercent = TRUE,
                            number.cex=0.8)




aus_b_dep_complete <- aus_b1_ses %>% na.omit


aus_b_dep_pc <- prcomp(aus_b_dep_complete[2:4], center = TRUE, scale = TRUE)
aus_b_dep_summary_pc <- summary(aus_b_dep_pc)
dep_pca_summary <- as.data.frame(aus_b_dep_summary_pc$importance)
#view(aus_b_dep_summary_pc$rotation) # PC1 proportion of variance: 0.636090
aus_b_dep_pc_score <- as.data.frame(aus_b_dep_summary_pc$x)


aus_b_dep_pca <- cbind(aus_b_dep_complete$hicid,aus_b_dep_pc_score)
colnames(aus_b_dep_pca)[1]  <- "hicid"
aus_b_dep_autism <- aus_b_dep_pca %>% filter(hicid %in% c(aus_b_autism_early$hicid,aus_b_autism_late$hicid))



aus_b_autism_tip <- merge(aus_b_eth_ma,aus_b_ses_autism, by = "hicid")

write.csv(aus_b_autism_tip,file = "/Users/aus_b_ses_eth.csv")


