
# Loading required packages

library(lme4)
library(lavaan)
library(data.table)
library(ggplot2)
library(haven)
library(tidyverse)
library(lcmm)

## Data


aus_k1 <- read_dta("/Users/General Release/Survey data/STATA/lsacgrk4.dta")
aus_k2 <- read_dta("/Users/General Release/Survey data/STATA/lsacgrk6.dta")
aus_k3 <- read_dta("/Users/General Release/Survey data/STATA/lsacgrk8.dta")
aus_k4 <- read_dta("/Users/General Release/Survey data/STATA/lsacgrk10.dta")
aus_k5 <- read_dta("/Users/General Release/Survey data/STATA/lsacgrk12.dta")
aus_k6 <- read_dta("/Users/General Release/Survey data/STATA/lsacgrk14.dta")
aus_k7 <- read_dta("/Users/General Release/Survey data/STATA/lsacgrk16.dta")

aus_k_consistent_ID <- unique(aus_k7$hicid[aus_k7$hicid%in%aus_k6$hicid[aus_k6$hicid%in% aus_k5$hicid[aus_k5$hicid %in% aus_k4$hicid[aus_k4$hicid %in% aus_k3$hicid [aus_k3$hicid %in% aus_k2$hicid [aus_k2$hicid %in% aus_k1$hicid]]]]]])
aus_consistent_k1 <- as.data.frame(aus_k1 %>% filter(hicid %in% aus_k_consistent_ID)) 
aus_consistent_k2 <- as.data.frame(aus_k2 %>% filter(hicid %in% aus_k_consistent_ID))  
aus_consistent_k3 <- as.data.frame(aus_k3 %>% filter(hicid %in% aus_k_consistent_ID))  
aus_consistent_k4 <- as.data.frame(aus_k4 %>% filter(hicid %in% aus_k_consistent_ID))  
aus_consistent_k5 <- as.data.frame(aus_k5 %>% filter(hicid %in% aus_k_consistent_ID))  
aus_consistent_k6 <- as.data.frame(aus_k6 %>% filter(hicid %in% aus_k_consistent_ID))  
aus_consistent_k7 <- as.data.frame(aus_k7 %>% filter(hicid %in% aus_k_consistent_ID))  




# Extract variables of interest

aus_k1_rc <- aus_consistent_k1 %>%
  mutate(across(starts_with("cse03a"), as.numeric)) %>%
  mutate(across(starts_with("cse03a"), ~recode(., '1' = 0, '2' = 1, '3' = 2)))

aus_k2_rc <- aus_consistent_k2 %>%  
  mutate(across(starts_with("dse03a"), as.numeric)) %>% 
  mutate(across(starts_with("dse03a"), ~recode(., '1' = 0, '2' = 1, '3' = 2)))

aus_k3_rc <- aus_consistent_k3 %>%  
  mutate(across(starts_with("ese03a"), as.numeric)) %>% 
  mutate(across(starts_with("ese03a"), ~recode(., '1' = 0, '2' = 1, '3' = 2)))

aus_k4_rc <- aus_consistent_k4 %>%  
  mutate(across(starts_with("fse03a"), as.numeric)) %>% 
  mutate(across(starts_with("fse03a"), ~recode(., '1' = 0, '2' = 1, '3' = 2)))

aus_k5_rc <- aus_consistent_k5 %>%  
  mutate(across(starts_with("gse03a"), as.numeric)) %>% 
  mutate(across(starts_with("gse03a"), ~recode(., '1' = 0, '2' = 1, '3' = 2)))

aus_k6_rc <- aus_consistent_k6 %>%  
  mutate(across(starts_with("hse03a"), as.numeric)) %>% 
  mutate(across(starts_with("hse03a"), ~recode(., '1' = 0, '2' = 1, '3' = 2)))

aus_k7_rc <- aus_consistent_k7 %>%  
  mutate(across(starts_with("ise03a"), as.numeric)) %>% 
  mutate(across(starts_with("ise03a"), ~recode(., '1' = 0, '2' = 1, '3' = 2)))





aus_k1_sdq <- aus_k1_rc %>% transmute(hicid, zf02m1, 
                                                  caemot_sum = rowSums(across(starts_with('cse03a3')), na.rm = TRUE), 
                                                  cacondb_sum = rowSums(across(starts_with('cse03a4')), na.rm = TRUE), 
                                                  cahypr_sum = rowSums(across(starts_with('cse03a2')), na.rm = TRUE), 
                                                  capeer_sum = rowSums(across(starts_with('cse03a5')), na.rm = TRUE), 
                                                  capsoc_sum = rowSums(across(starts_with('cse03a1')), na.rm = TRUE),
                                                  k1sdqttl = caemot_sum + cacondb_sum + cahypr_sum + capeer_sum) %>% filter_at(vars(1:8), all_vars(. >=0))


aus_k2_sdq <- aus_k2_rc %>% transmute(hicid,  zf02m1, 
                                                  daemot_sum = rowSums(across(starts_with('dse03a3')), na.rm = TRUE), 
                                                  dacondb_sum = rowSums(across(starts_with('dse03a4')), na.rm = TRUE), 
                                                  dahypr_sum = rowSums(across(starts_with('dse03a2')), na.rm = TRUE), 
                                                  dapeer_sum = rowSums(across(starts_with('dse03a5')), na.rm = TRUE), 
                                                  dapsoc_sum = rowSums(across(starts_with('dse03a1')), na.rm = TRUE),
                                                  k2sdqttl = daemot_sum + dacondb_sum + dahypr_sum + dapeer_sum) %>% filter_at(vars(1:8), all_vars(. >=0))

aus_k3_sdq <- aus_k3_rc %>% transmute(hicid,zf02m1,
                                                  eaemot_sum = rowSums(across(starts_with('ese03a3')), na.rm = TRUE), 
                                                  eacondb_sum = rowSums(across(starts_with('ese03a4')), na.rm = TRUE), 
                                                  eahypr_sum = rowSums(across(starts_with('ese03a2')), na.rm = TRUE), 
                                                  eapeer_sum = rowSums(across(starts_with('ese03a5')), na.rm = TRUE), 
                                                  eapsoc_sum = rowSums(across(starts_with('ese03a1')), na.rm = TRUE),
                                                  k3sdqttl = eaemot_sum + eacondb_sum + eahypr_sum + eapeer_sum) %>% filter_at(vars(1:8), all_vars(. >=0)) 




aus_k4_autism <- aus_k4_rc %>%  transmute(hicid, zf02m1, fhs17w, fhs17w2, fhs17w3, fhs17w4,
                                                  faemot_sum = rowSums(across(starts_with('fse03a3')), na.rm = TRUE), 
                                                  facondb_sum = rowSums(across(starts_with('fse03a4')), na.rm = TRUE), 
                                                  fahypr_sum = rowSums(across(starts_with('fse03a2')), na.rm = TRUE), 
                                                  fapeer_sum = rowSums(across(starts_with('fse03a5')), na.rm = TRUE), 
                                                  fapsoc_sum = rowSums(across(starts_with('fse03a1')), na.rm = TRUE),
                                                  k4sdqttl = faemot_sum + facondb_sum + fahypr_sum + fapeer_sum) %>% filter_at(vars(1,7:12), all_vars(. >=0)) 

aus_k4_autism$fhs17w4 <- ifelse(aus_k4_autism$fhs17w3 == 1, aus_k4_autism$fhs17w4 %/% 12, aus_k4_autism$fhs17w4)





aus_k5_autism <- aus_k5_rc %>%  transmute(hicid, zf02m1, ghs17w, ghs17w2, ghs17w3, ghs17w4,
                                                  gaemot_sum = rowSums(across(starts_with('gse03a3')), na.rm = TRUE), 
                                                  gacondb_sum = rowSums(across(starts_with('gse03a4')), na.rm = TRUE), 
                                                  gahypr_sum = rowSums(across(starts_with('gse03a2')), na.rm = TRUE), 
                                                  gapeer_sum = rowSums(across(starts_with('gse03a5')), na.rm = TRUE), 
                                                  gapsoc_sum = rowSums(across(starts_with('gse03a1')), na.rm = TRUE),
                                                  k5sdqttl = gaemot_sum + gacondb_sum + gahypr_sum + gapeer_sum) %>% filter_at(vars(1,7:12), all_vars(. >=0)) 

aus_k5_autism$ghs17w4 <- ifelse(aus_k5_autism$ghs17w3 == 1, aus_k5_autism$ghs17w4 %/% 12, aus_k5_autism$ghs17w4)





aus_k6_autism <- aus_k6_rc %>%  transmute(hicid, zf02m1, hhs17w, hhs17w2, hhs17w3, hhs17w4,
                                                  haemot_sum = rowSums(across(starts_with('hse03a3')), na.rm = TRUE), 
                                                  hacondb_sum = rowSums(across(starts_with('hse03a4')), na.rm = TRUE), 
                                                  hahypr_sum = rowSums(across(starts_with('hse03a2')), na.rm = TRUE), 
                                                  hapeer_sum = rowSums(across(starts_with('hse03a5')), na.rm = TRUE), 
                                                  hapsoc_sum = rowSums(across(starts_with('hse03a1')), na.rm = TRUE),
                                                  k6sdqttl = haemot_sum + hacondb_sum + hahypr_sum + hapeer_sum) %>% filter_at(vars(1,7:12), all_vars(. >=0)) 
aus_k6_autism$hhs17w4 <- ifelse(aus_k6_autism$hhs17w3 == 1, aus_k6_autism$hhs17w4 %/% 12, aus_k6_autism$hhs17w4)





aus_k7_autism <- aus_k7_rc %>%  transmute(hicid, zf02m1, ihs17w, ihs17w2, ihs17w3, ihs17w4,
                                                  iaemot_sum = rowSums(across(starts_with('ise03a3')), na.rm = TRUE), 
                                                  iacondb_sum = rowSums(across(starts_with('ise03a4')), na.rm = TRUE), 
                                                  iahypr_sum = rowSums(across(starts_with('ise03a2')), na.rm = TRUE), 
                                                  iapeer_sum = rowSums(across(starts_with('ise03a5')), na.rm = TRUE), 
                                                  iapsoc_sum = rowSums(across(starts_with('ise03a1')), na.rm = TRUE),
                                                  k7sdqttl = iaemot_sum + iacondb_sum + iahypr_sum + iapeer_sum) %>% filter_at(vars(1,7:12), all_vars(. >=0)) 

aus_k7_autism$ihs17w4 <- ifelse(aus_k7_autism$ihs17w3 == 1, aus_k7_autism$ihs17w4 %/% 12, aus_k7_autism$ihs17w4)




# Create wide data for LGCM

aus_k_autism_wide <- list(aus_k1_sdq,aus_k2_sdq, aus_k3_sdq,aus_k4_autism, aus_k5_autism, aus_k6_autism, aus_k7_autism) %>% reduce(full_join, by = c("hicid","zf02m1"))

aus_k_autism_wide <- aus_k_autism_wide[complete.cases(aus_k_autism_wide[c(3:20,25:30,35:40,45:50,55:60)]),]



aus_k_no_autism <- filter(aus_k_autism_wide, hhs17w != 1 & ihs17w != 1 & fhs17w != 1 & ghs17w != 1)
aus_k_diag_autism <- filter(aus_k_autism_wide, hhs17w == 1|ihs17w == 1|fhs17w == 1|ghs17w == 1) 
aus_k_diag_autism <- aus_k_diag_autism %>%
  mutate_all(~ ifelse(. == -9, NA, .))



selected_columns <- c("fhs17w", "ghs17w","hhs17w","ihs17w")

# Create a new column with values from selected columns joined by a dash
aus_k_diag_autism$autism_pattern <- do.call(paste, c(aus_k_diag_autism[selected_columns], sep = "-"))
find_first_one_position <- function(pattern) {
  pattern_digits <- unlist(strsplit(pattern, "-"))
  first_one_position <- which(pattern_digits == "1")[1]
  return(first_one_position)
}

# Apply the function to each row in the dataframe and create a new column
aus_k_diag_autism$first_diag <- sapply(aus_k_diag_autism$autism_pattern, find_first_one_position)



# to filter those diagnosed before or at age 9 (the first sweep in aus_k with autism diagnosis record is sweep 10-11)
aus_k_autism_early_filter <- aus_k_diag_autism  %>% dplyr::select(hicid,fhs17w4,ghs17w4,hhs17w4,ihs17w4,autism_pattern,first_diag)



aus_k_diag_autism  <- aus_k_diag_autism %>%
mutate(diag.age = case_when(
  first_diag =="1" ~ 11,
  first_diag == "2" ~ 13,
  first_diag == "3"~ 15,
  first_diag == "4"~ 17))

aus_k_diag_autism <- aus_k_diag_autism %>% 
filter(!hicid == 51301356)
# in sweep 2 this child had all 0s in SDQ
aus_k_autism_early <- filter(aus_k_diag_autism, diag.age == 11)
aus_k_autism_late <- filter(aus_k_diag_autism, diag.age > 11)
aus_k_diag_autism$group <- ifelse(aus_k_diag_autism$diag.age == 11, "early", "late")



aus_k_autism_early$group<- 1
aus_k_autism_late$group <-2
aus_k_no_autism$group <-3
aus_k_all <- rbind(aus_k_autism_early[,c(1:60,64)],aus_k_autism_late[,c(1:60,64)],aus_k_no_autism)
aus_k_autism <- rbind(aus_k_autism_early,aus_k_autism_late)



sex_ratio_diag_age <- aus_k_diag_autism %>%
  group_by(diag.age, zf02m1) %>%
  dplyr::summarize(count = n())
sex_ratio_diag_age

# LGCM
# covariates

aus_k_autism_tip <- read.csv("/Users/aus_k_covariates.csv")
# See aus_k_covariates.Rmd


aus_k_tip_early <- merge(aus_k_autism_early,aus_k_autism_tip, by = c("hicid","zf02m1"))
aus_k_tip_early$group <- 1
aus_k_tip_late <- merge(aus_k_autism_late,aus_k_autism_tip, by = c("hicid","zf02m1"))
aus_k_tip_late$group <-2
aus_k_autism_tip <- rbind(aus_k_tip_early,aus_k_tip_late)
aus_k_autism_tip$eth <- ifelse(aus_k_autism_tip$Eth %in% c(1,2),0,1)

## SDQ total score

aus_k_lgm_simple_ttl <- "

         int.sdq =~ 1*k1sdqttl + 1*k2sdqttl + 1*k3sdqttl + 1*k4sdqttl + 1*k5sdqttl + 1*k6sdqttl + 1*k7sdqttl
         slp.sdq =~ 0*k1sdqttl + 1*k2sdqttl + 2*k3sdqttl + 3*k4sdqttl + 4*k5sdqttl + 5*k6sdqttl + 6*k7sdqttl
          slp.sdq ~~ 1*slp.sdq
         "
# Constraint is applied to correct Heywood cases

aus_k_simple_lgm_fit_ttl <- growth(aus_k_lgm_simple_ttl, 
                           data = aus_k_all,group = "group",
                           missing = "fiml",
                           estimator = "ml", 
                           fixed.x = FALSE
                )

summary(aus_k_simple_lgm_fit_ttl)


## Sex stratified

aus_k_sexstr_ttl <- "

         int.sdq =~ 1*k1sdqttl + 1*k2sdqttl + 1*k3sdqttl + 1*k4sdqttl + 1*k5sdqttl + 1*k6sdqttl + 1*k7sdqttl
         slp.sdq =~ 0*k1sdqttl + 1*k2sdqttl + 2*k3sdqttl + 3*k4sdqttl + 4*k5sdqttl + 5*k6sdqttl + 6*k7sdqttl
        
         "

aus_k_sexstr_ttl_fit <- growth(aus_k_sexstr_ttl, 
                           data = aus_k_autism,group = "zf02m1",
                           missing = "fiml",
                           estimator = "ml", fixed.x = FALSE
                )

#summary(aus_k_sexstr_ttl_fit)
aus_k_asd_ttl_fit <- growth(aus_k_sexstr_ttl, data = aus_k_diag_autism, missing = "fiml",
                            estimator = "ml", fixed.x = F)
aus_k_agestr_ttl_fit <- growth(aus_k_sexstr_ttl, data = aus_k_diag_autism,
                               group = "group",missing = "fiml",
                            estimator = "ml", fixed.x = F)

ausk_ttl_anova_sex <- anova(aus_k_asd_ttl_fit,aus_k_sexstr_ttl_fit)
ausk_ttl_anova_age <- anova(aus_k_asd_ttl_fit,aus_k_agestr_ttl_fit)
ausk_anova_ttl_age_results<- data.frame(ausk_ttl_anova_age)
ausk_anova_ttl_sex_results<- data.frame(ausk_ttl_anova_sex)
ausk_anova_ttl <- rbind(ausk_anova_ttl_age_results,ausk_anova_ttl_sex_results)
ausk_anova_ttl


# Emotional symptoms
## diag age group stratified

aus_k_agestr_emot <- "

         int.sdq =~  1*caemot_sum + 1*daemot_sum + 1*eaemot_sum + 1*faemot_sum + 1*gaemot_sum + 1*haemot_sum + 1*iaemot_sum
         slp.sdq =~  0*caemot_sum + 1*daemot_sum + 2*eaemot_sum + 3*faemot_sum + 4*gaemot_sum + 5*haemot_sum + 6*iaemot_sum
         
         "

aus_k_agestr_fit_emot <- growth(aus_k_agestr_emot, 
                           data = aus_k_all,group = "group",
                           missing = "fiml",
                           estimator = "ml", fixed.x = FALSE
                )

summary(aus_k_agestr_fit_emot)


## Sex stratified

aus_k_sexstr_emot <- "

         int.sdq =~  1*caemot_sum + 1*daemot_sum + 1*eaemot_sum + 1*faemot_sum + 1*gaemot_sum + 1*haemot_sum + 1*iaemot_sum
         slp.sdq =~  0*caemot_sum + 1*daemot_sum + 2*eaemot_sum + 3*faemot_sum + 4*gaemot_sum + 5*haemot_sum + 6*iaemot_sum
         
         "

aus_k_sexstr_emot_fit <- growth(aus_k_sexstr_emot, 
                           data = aus_k_autism,group = "zf02m1",
                           missing = "fiml",
                           estimator = "ml", fixed.x = FALSE
                )

#summary(aus_k_sexstr_fit_emot)
aus_k_asd_emot_fit <- growth(aus_k_sexstr_emot, data = aus_k_diag_autism, missing = "fiml",
                            estimator = "ml", fixed.x = F)
aus_k_agestr_emot_fit <- growth(aus_k_sexstr_emot, data = aus_k_diag_autism,
                               group = "group",missing = "fiml",
                            estimator = "ml", fixed.x = F)

ausk_emot_anova_sex <- anova(aus_k_asd_emot_fit,aus_k_sexstr_emot_fit)
ausk_emot_anova_age <- anova(aus_k_asd_emot_fit,aus_k_agestr_emot_fit)
ausk_anova_emot_age_results<- data.frame(ausk_emot_anova_age)
ausk_anova_emot_sex_results<- data.frame(ausk_emot_anova_sex)
ausk_anova_emot <- rbind(ausk_anova_emot_age_results,ausk_anova_emot_sex_results)
ausk_anova_emot


# Conduct problems
## diag.age stratified

aus_k_agestr_condb <- "

         int.sdq =~  1*cacondb_sum + 1*dacondb_sum + 1*eacondb_sum + 1*facondb_sum + 1*gacondb_sum + 1*hacondb_sum + 1*iacondb_sum
         slp.sdq =~  0*cacondb_sum + 1*dacondb_sum + 2*eacondb_sum + 3*facondb_sum + 4*gacondb_sum + 5*hacondb_sum + 6*iacondb_sum
        
         "

aus_k_agestr_condb_fit <- growth(aus_k_agestr_condb, 
                           data = aus_k_all,group = "group",
                           missing = "fiml",
                           estimator = "ml", fixed.x = FALSE
                )

summary(aus_k_agestr_condb_fit)


## Sex stratified

aus_k_sexstr_condb <- "

         int.sdq =~  1*cacondb_sum + 1*dacondb_sum + 1*eacondb_sum + 1*facondb_sum + 1*gacondb_sum + 1*hacondb_sum + 1*iacondb_sum
         slp.sdq =~  0*cacondb_sum + 1*dacondb_sum + 2*eacondb_sum + 3*facondb_sum + 4*gacondb_sum + 5*hacondb_sum + 6*iacondb_sum
        
         "

aus_k_sexstr_condb_fit <- growth(aus_k_sexstr_condb, 
                           data = aus_k_autism,group = "zf02m1",
                           missing = "fiml",
                           estimator = "ml", fixed.x = FALSE
                )

#summary(aus_k_sexstr_condb_fit)

aus_k_asd_condb_fit <- growth(aus_k_sexstr_condb, data = aus_k_diag_autism, missing = "fiml",
                            estimator = "ml", fixed.x = F)
aus_k_agestr_condb_fit <- growth(aus_k_sexstr_condb, data = aus_k_diag_autism,
                               group = "group",missing = "fiml",
                            estimator = "ml", fixed.x = F)

ausk_condb_anova_sex <- anova(aus_k_asd_condb_fit,aus_k_sexstr_condb_fit)
ausk_condb_anova_age <- anova(aus_k_asd_condb_fit,aus_k_agestr_condb_fit)
ausk_anova_condb_age_results<- data.frame(ausk_condb_anova_age)
ausk_anova_condb_sex_results<- data.frame(ausk_condb_anova_sex)
ausk_anova_condb <- rbind(ausk_anova_condb_age_results,ausk_anova_condb_sex_results)
ausk_anova_condb


# Hyperactivity
## diagnosis age stratified

aus_k_agestr_hypr <- "

         int.sdq =~  1*cahypr_sum + 1*dahypr_sum + 1*eahypr_sum + 1*fahypr_sum + 1*gahypr_sum + 1*hahypr_sum + 1*iahypr_sum
         slp.sdq =~  0*cahypr_sum + 1*dahypr_sum + 2*eahypr_sum + 3*fahypr_sum + 4*gahypr_sum + 5*hahypr_sum + 6*iahypr_sum
         
         "

aus_k_agestr_fit_hypr <- growth(aus_k_agestr_hypr, 
                           data = aus_k_all,group = "group",
                           missing = "fiml",
                           estimator = "ml", fixed.x = FALSE
                )

summary(aus_k_agestr_fit_hypr)


## sex stratified

aus_k_sexstr_hypr <- "

         int.sdq =~  1*cahypr_sum + 1*dahypr_sum + 1*eahypr_sum + 1*fahypr_sum + 1*gahypr_sum + 1*hahypr_sum + 1*iahypr_sum
         slp.sdq =~  0*cahypr_sum + 1*dahypr_sum + 2*eahypr_sum + 3*fahypr_sum + 4*gahypr_sum + 5*hahypr_sum + 6*iahypr_sum
         
         "

aus_k_sexstr_hypr_fit <- growth(aus_k_sexstr_hypr, 
                           data = aus_k_autism,group = "zf02m1",
                           missing = "fiml",
                           estimator = "ml", fixed.x = FALSE
                )

#summary(aus_k_sexstr_fit_hypr)
aus_k_asd_hypr_fit <- growth(aus_k_sexstr_hypr, data = aus_k_diag_autism, missing = "fiml",
                            estimator = "ml", fixed.x = F)
aus_k_agestr_hypr_fit <- growth(aus_k_sexstr_hypr, data = aus_k_diag_autism,
                               group = "group",missing = "fiml",
                            estimator = "ml", fixed.x = F)

ausk_hypr_anova_sex <- anova(aus_k_asd_hypr_fit,aus_k_sexstr_hypr_fit)
ausk_hypr_anova_age <- anova(aus_k_asd_hypr_fit,aus_k_agestr_hypr_fit)
ausk_anova_hypr_age_results<- data.frame(ausk_hypr_anova_age)
ausk_anova_hypr_sex_results<- data.frame(ausk_hypr_anova_sex)
ausk_anova_hypr <- rbind(ausk_anova_hypr_age_results,ausk_anova_hypr_sex_results)
ausk_anova_hypr


# Peer relationship problems
## diag.age stratified

aus_k_agestr_peer <- "

         int.sdq =~  1*capeer_sum + 1*dapeer_sum + 1*eapeer_sum + 1*fapeer_sum + 1*gapeer_sum + 1*hapeer_sum + 1*iapeer_sum
         slp.sdq =~  0*capeer_sum + 1*dapeer_sum + 2*eapeer_sum + 3*fapeer_sum + 4*gapeer_sum + 5*hapeer_sum + 6*iapeer_sum
         
         "

aus_k_agestr_fit_peer <- growth(aus_k_agestr_peer, 
                           data = aus_k_all,group = "group",
                           missing = "fiml",
                           estimator = "ml", fixed.x = FALSE
                )

summary(aus_k_agestr_fit_peer)


est_aus_k_agestr_fit_peer <- parameterEstimates(aus_k_agestr_fit_peer) %>% filter(grepl("int|slp",lhs) & op == "~1")
results_aus_k_agestr_fit_peer <-  est_aus_k_agestr_fit_peer %>%
  dplyr::select(lhs, group,est, ci.lower, ci.upper, pvalue) %>%
 mutate(Estimates = sprintf("%.2f [%0.2f, %0.2f]", est, ci.lower, ci.upper),
         p_value = sprintf("%.3f", pvalue)) %>%
  dplyr::select(lhs,group,Estimates, p_value)
results_aus_k_agestr_fit_peer


## sex stratified


aus_k_sexstr_peer <- "

         int.sdq =~  1*capeer_sum + 1*dapeer_sum + 1*eapeer_sum + 1*fapeer_sum + 1*gapeer_sum + 1*hapeer_sum + 1*iapeer_sum
         slp.sdq =~  0*capeer_sum + 1*dapeer_sum + 2*eapeer_sum + 3*fapeer_sum + 4*gapeer_sum + 5*hapeer_sum + 6*iapeer_sum
         
         "

aus_k_sexstr_peer_fit <- growth(aus_k_sexstr_peer, 
                           data = aus_k_autism,group = "zf02m1",
                           missing = "fiml",
                           estimator = "ml", fixed.x = FALSE
                )

#summary(aus_k_sexstr_fit_peer)
aus_k_asd_peer_fit <- growth(aus_k_sexstr_peer, data = aus_k_diag_autism, missing = "fiml",
                            estimator = "ml", fixed.x = F)
aus_k_agestr_peer_fit <- growth(aus_k_sexstr_peer, data = aus_k_diag_autism,
                               group = "group",missing = "fiml",
                            estimator = "ml", fixed.x = F)

ausk_peer_anova_sex <- anova(aus_k_asd_peer_fit,aus_k_sexstr_peer_fit)
ausk_peer_anova_age <- anova(aus_k_asd_peer_fit,aus_k_agestr_peer_fit)
ausk_anova_peer_age_results<- data.frame(ausk_peer_anova_age)
ausk_anova_peer_sex_results<- data.frame(ausk_peer_anova_sex)
ausk_anova_peer <- rbind(ausk_anova_peer_age_results,ausk_anova_peer_sex_results)
ausk_anova_peer


# Prosocialness
## Age stratified

aus_k_agestr_psoc <- "

         int.sdq =~  1*capsoc_sum + 1*dapsoc_sum + 1*eapsoc_sum + 1*fapsoc_sum + 1*gapsoc_sum + 1*hapsoc_sum + 1*iapsoc_sum
         slp.sdq =~  0*capsoc_sum + 1*dapsoc_sum + 2*eapsoc_sum + 3*fapsoc_sum + 4*gapsoc_sum + 5*hapsoc_sum + 6*iapsoc_sum
         
         "

aus_k_agestr_fit_psoc <- growth(aus_k_agestr_psoc, 
                           data = aus_k_all,group = "group",
                           missing = "fiml",
                           estimator = "ml", fixed.x = FALSE
                )

summary(aus_k_agestr_fit_psoc)


## sexstr 

aus_k_sexstr_psoc <- "

         int.sdq =~  1*capsoc_sum + 1*dapsoc_sum + 1*eapsoc_sum + 1*fapsoc_sum + 1*gapsoc_sum + 1*hapsoc_sum + 1*iapsoc_sum
         slp.sdq =~  0*capsoc_sum + 1*dapsoc_sum + 2*eapsoc_sum + 3*fapsoc_sum + 4*gapsoc_sum + 5*hapsoc_sum + 6*iapsoc_sum
         
         "

aus_k_sexstr_psoc_fit <- growth(aus_k_sexstr_psoc, 
                           data = aus_k_autism,group = "zf02m1",
                           missing = "fiml",
                           estimator = "ml", fixed.x = FALSE
                )

#summary(aus_k_sexstr_fit_psoc)

aus_k_asd_psoc_fit <- growth(aus_k_sexstr_psoc, data = aus_k_diag_autism, missing = "fiml",
                            estimator = "ml", fixed.x = F)
aus_k_agestr_psoc_fit <- growth(aus_k_sexstr_psoc, data = aus_k_diag_autism,
                               group = "group",missing = "fiml",
                            estimator = "ml", fixed.x = F)

ausk_psoc_anova_sex <- anova(aus_k_asd_psoc_fit,aus_k_sexstr_psoc_fit)
ausk_psoc_anova_age <- anova(aus_k_asd_psoc_fit,aus_k_agestr_psoc_fit)
ausk_anova_psoc_age_results<- data.frame(ausk_psoc_anova_age)
ausk_anova_psoc_sex_results<- data.frame(ausk_psoc_anova_sex)
ausk_anova_psoc <- rbind(ausk_anova_psoc_age_results,ausk_anova_psoc_sex_results)
ausk_anova_psoc

=======================================================
## LGCM mean trajectories
## Total

library(plotrix)
early_aus_k_autism_sdq_ttl <- aus_k_autism_early[,c(1:2,8,14,20,30,40,50,60)]
colnames(early_aus_k_autism_sdq_ttl)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
early_aus_k_autism_sdq_ttl_long <- melt(setDT(early_aus_k_autism_sdq_ttl), id.vars = c("hicid","zf02m1"), variable.name = "sweep")

early_aus_k_ttl_summary <- early_aus_k_autism_sdq_ttl_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    ttl_mean = mean(value), se = std.error(value)
  )
early_aus_k_ttl_summary

early_aus_k_ttl_summary$group <- "early"

early_aus_k_ttl_summary <- early_aus_k_ttl_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17
    ))

late_aus_k_autism_sdq_ttl <- aus_k_autism_late[,c(1:2,8,14,20,30,40,50,60)]
colnames(late_aus_k_autism_sdq_ttl)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
late_aus_k_autism_sdq_ttl_long <- melt(setDT(late_aus_k_autism_sdq_ttl), id.vars = c("hicid","zf02m1"), variable.name = "sweep")


late_aus_k_ttl_summary <- late_aus_k_autism_sdq_ttl_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    ttl_mean = mean(value), 
  se = std.error(value)
  )
late_aus_k_ttl_summary

late_aus_k_ttl_summary <- late_aus_k_ttl_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17)
    )
late_aus_k_ttl_summary$group <- "late"

no_diag_aus_k_sdq_ttl <- aus_k_no_autism[,c(1:2,8,14,20,30,40,50,60)]
colnames(no_diag_aus_k_sdq_ttl)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
no_diag_aus_k_sdq_ttl_long <- melt(setDT(no_diag_aus_k_sdq_ttl), id.vars = c("hicid","zf02m1"), variable.name = "sweep")


no_diag_aus_k_ttl_summary <- no_diag_aus_k_sdq_ttl_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    ttl_mean = mean(value), se = std.error(value)
  )
no_diag_aus_k_ttl_summary

no_diag_aus_k_ttl_summary <- no_diag_aus_k_ttl_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17)
    )
no_diag_aus_k_ttl_summary$group <- "no_diag"



early_aus_k_ttl_summary$lb = early_aus_k_ttl_summary$ttl_mean - 1.96*early_aus_k_ttl_summary$se
early_aus_k_ttl_summary$ub = early_aus_k_ttl_summary$ttl_mean + 1.96*early_aus_k_ttl_summary$se
late_aus_k_ttl_summary$lb = late_aus_k_ttl_summary$ttl_mean - 1.96*late_aus_k_ttl_summary$se
late_aus_k_ttl_summary$ub = late_aus_k_ttl_summary$ttl_mean + 1.96*late_aus_k_ttl_summary$se
no_diag_aus_k_ttl_summary$lb = no_diag_aus_k_ttl_summary$ttl_mean - 1.96*no_diag_aus_k_ttl_summary$se
no_diag_aus_k_ttl_summary$ub = no_diag_aus_k_ttl_summary$ttl_mean + 1.96*no_diag_aus_k_ttl_summary$se
aus_k_sdq_total_mean_full <- full_join(full_join(early_aus_k_ttl_summary, late_aus_k_ttl_summary),no_diag_aus_k_ttl_summary)
aus_k_sdq_total_mean_full



## Emotional symptoms



early_aus_k_autism_sdq_emot <- aus_k_autism_early[,c(1:2,3,9,15,25,35,45,55)]
colnames(early_aus_k_autism_sdq_emot)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
early_aus_k_autism_sdq_emot_long <- melt(setDT(early_aus_k_autism_sdq_emot), id.vars = c("hicid","zf02m1"), variable.name = "sweep")

early_aus_k_emot_summary <- early_aus_k_autism_sdq_emot_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    emot_mean = mean(value), se = std.error(value)
  )
early_aus_k_emot_summary

early_aus_k_emot_summary$group <- "early"

early_aus_k_emot_summary <- early_aus_k_emot_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17
    ))

late_aus_k_autism_sdq_emot <- aus_k_autism_late[,c(1:2,3,9,15,25,35,45,55)]
colnames(late_aus_k_autism_sdq_emot)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
late_aus_k_autism_sdq_emot_long <- melt(setDT(late_aus_k_autism_sdq_emot), id.vars = c("hicid","zf02m1"), variable.name = "sweep")


late_aus_k_emot_summary <- late_aus_k_autism_sdq_emot_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    emot_mean = mean(value), se = std.error(value)
  )
late_aus_k_emot_summary

late_aus_k_emot_summary <- late_aus_k_emot_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17)
    )
late_aus_k_emot_summary$group <- "late"

no_diag_aus_k_sdq_emot <- aus_k_no_autism[,c(1:2,3,9,15,25,35,45,55)]
colnames(no_diag_aus_k_sdq_emot)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
no_diag_aus_k_sdq_emot_long <- melt(setDT(no_diag_aus_k_sdq_emot), id.vars = c("hicid","zf02m1"), variable.name = "sweep")


no_diag_aus_k_emot_summary <- no_diag_aus_k_sdq_emot_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    emot_mean = mean(value), se = std.error(value)
  )
no_diag_aus_k_emot_summary

no_diag_aus_k_emot_summary <- no_diag_aus_k_emot_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17)
    )
no_diag_aus_k_emot_summary$group <- "no_diag"


early_aus_k_emot_summary$lb = early_aus_k_emot_summary$emot_mean - 1.96*early_aus_k_emot_summary$se
early_aus_k_emot_summary$ub = early_aus_k_emot_summary$emot_mean + 1.96*early_aus_k_emot_summary$se
late_aus_k_emot_summary$lb = late_aus_k_emot_summary$emot_mean - 1.96*late_aus_k_emot_summary$se
late_aus_k_emot_summary$ub = late_aus_k_emot_summary$emot_mean + 1.96*late_aus_k_emot_summary$se
no_diag_aus_k_emot_summary$lb = no_diag_aus_k_emot_summary$emot_mean - 1.96*no_diag_aus_k_emot_summary$se
no_diag_aus_k_emot_summary$ub = no_diag_aus_k_emot_summary$emot_mean + 1.96*no_diag_aus_k_emot_summary$se
aus_k_sdq_emot_mean_full <- full_join(full_join(early_aus_k_emot_summary, late_aus_k_emot_summary),no_diag_aus_k_emot_summary)
aus_k_sdq_emot_mean_full


## Conduct problems

early_aus_k_autism_sdq_condb <- aus_k_autism_early[,c(1:2,4,10,16,26,36,46,56)]
colnames(early_aus_k_autism_sdq_condb)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
early_aus_k_autism_sdq_condb_long <- melt(setDT(early_aus_k_autism_sdq_condb), id.vars = c("hicid","zf02m1"), variable.name = "sweep")

early_aus_k_condb_summary <- early_aus_k_autism_sdq_condb_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    condb_mean = mean(value), se = std.error(value)
  )
early_aus_k_condb_summary

early_aus_k_condb_summary$group <- "early"

early_aus_k_condb_summary <- early_aus_k_condb_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17
    ))

late_aus_k_autism_sdq_condb <- aus_k_autism_late[,c(1:2,4,10,16,26,36,46,56)]
colnames(late_aus_k_autism_sdq_condb)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
late_aus_k_autism_sdq_condb_long <- melt(setDT(late_aus_k_autism_sdq_condb), id.vars = c("hicid","zf02m1"), variable.name = "sweep")


late_aus_k_condb_summary <- late_aus_k_autism_sdq_condb_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    condb_mean = mean(value), se = std.error(value)
  )
late_aus_k_condb_summary

late_aus_k_condb_summary <- late_aus_k_condb_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17)
    )
late_aus_k_condb_summary$group <- "late"

no_diag_aus_k_sdq_condb <- aus_k_no_autism[,c(1:2,4,10,16,26,36,46,56)]
colnames(no_diag_aus_k_sdq_condb)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
no_diag_aus_k_sdq_condb_long <- melt(setDT(no_diag_aus_k_sdq_condb), id.vars = c("hicid","zf02m1"), variable.name = "sweep")


no_diag_aus_k_condb_summary <- no_diag_aus_k_sdq_condb_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    condb_mean = mean(value),
    se = std.error(value)
  )
no_diag_aus_k_condb_summary

no_diag_aus_k_condb_summary <- no_diag_aus_k_condb_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17)
    )
no_diag_aus_k_condb_summary$group <- "no_diag"


early_aus_k_condb_summary$lb = early_aus_k_condb_summary$condb_mean - 1.96*early_aus_k_condb_summary$se
early_aus_k_condb_summary$ub = early_aus_k_condb_summary$condb_mean + 1.96*early_aus_k_condb_summary$se
late_aus_k_condb_summary$lb = late_aus_k_condb_summary$condb_mean - 1.96*late_aus_k_condb_summary$se
late_aus_k_condb_summary$ub = late_aus_k_condb_summary$condb_mean + 1.96*late_aus_k_condb_summary$se
no_diag_aus_k_condb_summary$lb = no_diag_aus_k_condb_summary$condb_mean - 1.96*no_diag_aus_k_condb_summary$se
no_diag_aus_k_condb_summary$ub = no_diag_aus_k_condb_summary$condb_mean + 1.96*no_diag_aus_k_condb_summary$se
aus_k_sdq_condb_mean_full <- full_join(full_join(early_aus_k_condb_summary, late_aus_k_condb_summary),no_diag_aus_k_condb_summary)
aus_k_sdq_condb_mean_full


## Hyperactivity


early_aus_k_autism_sdq_hypr <- aus_k_autism_early[,c(1:2,5,11,17,27,37,47,57)]
colnames(early_aus_k_autism_sdq_hypr)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
early_aus_k_autism_sdq_hypr_long <- melt(setDT(early_aus_k_autism_sdq_hypr), id.vars = c("hicid","zf02m1"), variable.name = "sweep")

early_aus_k_hypr_summary <- early_aus_k_autism_sdq_hypr_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    hypr_mean = mean(value), se = std.error(value)
  )
early_aus_k_hypr_summary

early_aus_k_hypr_summary$group <- "early"

early_aus_k_hypr_summary <- early_aus_k_hypr_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17
    ))

late_aus_k_autism_sdq_hypr <- aus_k_autism_late[,c(1:2,5,11,17,27,37,47,57)]
colnames(late_aus_k_autism_sdq_hypr)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
late_aus_k_autism_sdq_hypr_long <- melt(setDT(late_aus_k_autism_sdq_hypr), id.vars = c("hicid","zf02m1"), variable.name = "sweep")


late_aus_k_hypr_summary <- late_aus_k_autism_sdq_hypr_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    hypr_mean = mean(value), se = std.error(value)
  )
late_aus_k_hypr_summary

late_aus_k_hypr_summary <- late_aus_k_hypr_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17)
    )
late_aus_k_hypr_summary$group <- "late"

no_diag_aus_k_sdq_hypr <- aus_k_no_autism[,c(1:2,5,11,17,27,37,47,57)]
colnames(no_diag_aus_k_sdq_hypr)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
no_diag_aus_k_sdq_hypr_long <- melt(setDT(no_diag_aus_k_sdq_hypr), id.vars = c("hicid","zf02m1"), variable.name = "sweep")


no_diag_aus_k_hypr_summary <- no_diag_aus_k_sdq_hypr_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    hypr_mean = mean(value), se = std.error(value)
  )
no_diag_aus_k_hypr_summary

no_diag_aus_k_hypr_summary <- no_diag_aus_k_hypr_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17)
    )
no_diag_aus_k_hypr_summary$group <- "no_diag"



early_aus_k_hypr_summary$lb = early_aus_k_hypr_summary$hypr_mean - 1.96*early_aus_k_hypr_summary$se
early_aus_k_hypr_summary$ub = early_aus_k_hypr_summary$hypr_mean + 1.96*early_aus_k_hypr_summary$se
late_aus_k_hypr_summary$lb = late_aus_k_hypr_summary$hypr_mean - 1.96*late_aus_k_hypr_summary$se
late_aus_k_hypr_summary$ub = late_aus_k_hypr_summary$hypr_mean + 1.96*late_aus_k_hypr_summary$se
no_diag_aus_k_hypr_summary$lb = no_diag_aus_k_hypr_summary$hypr_mean - 1.96*no_diag_aus_k_hypr_summary$se
no_diag_aus_k_hypr_summary$ub = no_diag_aus_k_hypr_summary$hypr_mean + 1.96*no_diag_aus_k_hypr_summary$se
aus_k_sdq_hypr_mean_full <- full_join(full_join(early_aus_k_hypr_summary, late_aus_k_hypr_summary),no_diag_aus_k_hypr_summary)
aus_k_sdq_hypr_mean_full



## Peer



early_aus_k_autism_sdq_peer <- aus_k_autism_early[,c(1:2,6,12,18,28,38,48,58)]
colnames(early_aus_k_autism_sdq_peer)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
early_aus_k_autism_sdq_peer_long <- melt(setDT(early_aus_k_autism_sdq_peer), id.vars = c("hicid","zf02m1"), variable.name = "sweep")

early_aus_k_peer_summary <- early_aus_k_autism_sdq_peer_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    peer_mean = mean(value), se = std.error(value)
  )
early_aus_k_peer_summary

early_aus_k_peer_summary$group <- "early"

early_aus_k_peer_summary <- early_aus_k_peer_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17
    ))

late_aus_k_autism_sdq_peer <- aus_k_autism_late[,c(1:2,6,12,18,28,38,48,58)]
colnames(late_aus_k_autism_sdq_peer)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
late_aus_k_autism_sdq_peer_long <- melt(setDT(late_aus_k_autism_sdq_peer), id.vars = c("hicid","zf02m1"), variable.name = "sweep")


late_aus_k_peer_summary <- late_aus_k_autism_sdq_peer_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    peer_mean = mean(value), se = std.error(value)
  )
late_aus_k_peer_summary

late_aus_k_peer_summary <- late_aus_k_peer_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17)
    )
late_aus_k_peer_summary$group <- "late"

no_diag_aus_k_sdq_peer <- aus_k_no_autism[,c(1:2,6,12,18,28,38,48,58)]
colnames(no_diag_aus_k_sdq_peer)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
no_diag_aus_k_sdq_peer_long <- melt(setDT(no_diag_aus_k_sdq_peer), id.vars = c("hicid","zf02m1"), variable.name = "sweep")


no_diag_aus_k_peer_summary <- no_diag_aus_k_sdq_peer_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    peer_mean = mean(value), se = std.error(value)
  )
no_diag_aus_k_peer_summary

no_diag_aus_k_peer_summary <- no_diag_aus_k_peer_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17)
    )
no_diag_aus_k_peer_summary$group <- "no_diag"



early_aus_k_peer_summary$lb = early_aus_k_peer_summary$peer_mean - 1.96*early_aus_k_peer_summary$se
early_aus_k_peer_summary$ub = early_aus_k_peer_summary$peer_mean + 1.96*early_aus_k_peer_summary$se
late_aus_k_peer_summary$lb = late_aus_k_peer_summary$peer_mean - 1.96*late_aus_k_peer_summary$se
late_aus_k_peer_summary$ub = late_aus_k_peer_summary$peer_mean + 1.96*late_aus_k_peer_summary$se
no_diag_aus_k_peer_summary$lb = no_diag_aus_k_peer_summary$peer_mean - 1.96*no_diag_aus_k_peer_summary$se
no_diag_aus_k_peer_summary$ub = no_diag_aus_k_peer_summary$peer_mean + 1.96*no_diag_aus_k_peer_summary$se
aus_k_sdq_peer_mean_full <- full_join(full_join(early_aus_k_peer_summary, late_aus_k_peer_summary),no_diag_aus_k_peer_summary)
aus_k_sdq_peer_mean_full


## Prosocialness


early_aus_k_autism_sdq_psoc <- aus_k_autism_early[,c(1:2,7,13,19,29,39,49,59)]
colnames(early_aus_k_autism_sdq_psoc)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
early_aus_k_autism_sdq_psoc_long <- melt(setDT(early_aus_k_autism_sdq_psoc), id.vars = c("hicid","zf02m1"), variable.name = "sweep")

early_aus_k_psoc_summary <- early_aus_k_autism_sdq_psoc_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    psoc_mean = mean(value), se = std.error(value)
  )
early_aus_k_psoc_summary

early_aus_k_psoc_summary$group <- "early"

early_aus_k_psoc_summary <- early_aus_k_psoc_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17
    ))

late_aus_k_autism_sdq_psoc <- aus_k_autism_late[,c(1:2,7,13,19,29,39,49,59)]
colnames(late_aus_k_autism_sdq_psoc)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
late_aus_k_autism_sdq_psoc_long <- melt(setDT(late_aus_k_autism_sdq_psoc), id.vars = c("hicid","zf02m1"), variable.name = "sweep")


late_aus_k_psoc_summary <- late_aus_k_autism_sdq_psoc_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    psoc_mean = mean(value), se = std.error(value)
  )
late_aus_k_psoc_summary

late_aus_k_psoc_summary <- late_aus_k_psoc_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17)
    )
late_aus_k_psoc_summary$group <- "late"

no_diag_aus_k_sdq_psoc <- aus_k_no_autism[,c(1:2,7,13,19,29,39,49,59)]
colnames(no_diag_aus_k_sdq_psoc)[3:9] <- c("k1","k2","k3","k4","k5","k6","k7")
no_diag_aus_k_sdq_psoc_long <- melt(setDT(no_diag_aus_k_sdq_psoc), id.vars = c("hicid","zf02m1"), variable.name = "sweep")


no_diag_aus_k_psoc_summary <- no_diag_aus_k_sdq_psoc_long %>%
  group_by(sweep) %>%
  summarise(
    sd = sd(value),
    psoc_mean = mean(value), se = std.error(value)
  )
no_diag_aus_k_psoc_summary

no_diag_aus_k_psoc_summary <- no_diag_aus_k_psoc_summary %>%
  mutate(Age = case_when(
    sweep == "k1" ~ 5,
    sweep == "k2" ~ 7,
    sweep == "k3" ~ 9,
    sweep == "k4" ~ 11,
    sweep == "k5" ~ 13,
    sweep == "k6" ~ 15,
    sweep == "k7" ~ 17)
    )
no_diag_aus_k_psoc_summary$group <- "no_diag"

early_aus_k_psoc_summary$lb = early_aus_k_psoc_summary$psoc_mean - 1.96*early_aus_k_psoc_summary$se
early_aus_k_psoc_summary$ub = early_aus_k_psoc_summary$psoc_mean + 1.96*early_aus_k_psoc_summary$se
late_aus_k_psoc_summary$lb = late_aus_k_psoc_summary$psoc_mean - 1.96*late_aus_k_psoc_summary$se
late_aus_k_psoc_summary$ub = late_aus_k_psoc_summary$psoc_mean + 1.96*late_aus_k_psoc_summary$se
no_diag_aus_k_psoc_summary$lb = no_diag_aus_k_psoc_summary$psoc_mean - 1.96*no_diag_aus_k_psoc_summary$se
no_diag_aus_k_psoc_summary$ub = no_diag_aus_k_psoc_summary$psoc_mean + 1.96*no_diag_aus_k_psoc_summary$se
aus_k_sdq_psoc_mean_full <- full_join(full_join(early_aus_k_psoc_summary, late_aus_k_psoc_summary),no_diag_aus_k_psoc_summary)
aus_k_sdq_psoc_mean_full


=================================================

# GMM (on diagnosed autistics children)
## Total GMM data prep

aus_k_diag_autism <- dplyr::mutate(aus_k_diag_autism, numericID = row_number())
aus_k_autism_wide_sdq_total <- aus_k_diag_autism[,c("numericID","hicid","zf02m1","diag.age","k1sdqttl","k2sdqttl","k3sdqttl","k4sdqttl","k5sdqttl","k6sdqttl","k7sdqttl")] %>% na.omit
aus_k_autism_long_sdq_total <- melt(setDT(aus_k_autism_wide_sdq_total), id.vars = c("numericID","hicid","zf02m1","diag.age"), variable.name = "sweep")

aus_k_autism_long_sdq_total <- aus_k_autism_long_sdq_total %>%
  mutate(Sweep = case_when(
    sweep == "k1sdqttl" ~ 1,
    sweep == "k2sdqttl" ~ 2,
    sweep == "k3sdqttl" ~ 3,
    sweep == "k4sdqttl" ~ 4,
    sweep == "k5sdqttl" ~ 5,
    sweep == "k6sdqttl" ~ 6,
    sweep == "k7sdqttl" ~ 7)
    )

aus_k_asd_long_sdq_ttl_early <- filter(aus_k_autism_long_sdq_total, hicid %in% aus_k_autism_early$hicid)
aus_k_asd_long_sdq_ttl_late <- filter(aus_k_autism_long_sdq_total, hicid %in% aus_k_autism_late$hicid)



# SDQ total GMM

aus_k_diag_ttl_gmm1 <- hlme(value ~ Sweep, subject = "numericID", random=~1, ng = 1, data =
aus_k_autism_long_sdq_total)
summary(aus_k_diag_ttl_gmm1)


aus_k_diag_ttl_gmm2 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 2, data = aus_k_autism_long_sdq_total, mixture = ~ Sweep,
nwg=T, B = aus_k_diag_ttl_gmm1)
summary(aus_k_diag_ttl_gmm2)


aus_k_diag_ttl_gmm3 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 3, data = aus_k_autism_long_sdq_total, mixture = ~ Sweep, 
nwg=T, B = aus_k_diag_ttl_gmm1)
summary(aus_k_diag_ttl_gmm3)

aus_k_diag_ttl_gmm4 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 4, data = aus_k_autism_long_sdq_total, mixture = ~ Sweep, 
nwg=T, B = aus_k_diag_ttl_gmm1)
summary(aus_k_diag_ttl_gmm4)


# make a table with results for the models:
fit_ind_aus_k_ttl <- summarytable(aus_k_diag_ttl_gmm1, aus_k_diag_ttl_gmm2, aus_k_diag_ttl_gmm3, aus_k_diag_ttl_gmm4,which = c("AIC","BIC","%class","entropy","npm","loglik","SABIC"))


my_colors_gmm <- brewer.pal(12, "Paired")[c(4,10)]
age_k <- c("5","7","9","11","13","15","17")
aus_k_autism_long_sdq_total$numericID <- as.character(aus_k_autism_long_sdq_total$numericID)
aus_k_diag_ttl_people2 <- as.data.frame(aus_k_diag_ttl_gmm2$pprob[,1:2])

aus_k_autism_long_sdq_total_gmm2 <- full_join(aus_k_autism_long_sdq_total, aus_k_diag_ttl_people2, by = "numericID")
aus_k_autism_long_sdq_total_gmm2$numericID <- as.character(aus_k_autism_long_sdq_total_gmm2$numericID)
aus_k_autism_long_sdq_total_gmm2$class <- as.factor(aus_k_autism_long_sdq_total_gmm2$class)
aus_k_autism_long_sdq_total$group_aus_k_diag_ttl_gmm2_s <- factor(aus_k_diag_ttl_people2$class[unlist(sapply(aus_k_autism_long_sdq_total$numericID, function(x) which(aus_k_diag_ttl_people2$numeircID==x)))])


# Emotional symptoms

## emot GMM data prep

aus_k_autism_wide_sdq_emot <- aus_k_diag_autism[,c("numericID","hicid","zf02m1","diag.age","caemot_sum","daemot_sum","eaemot_sum","faemot_sum","gaemot_sum","haemot_sum","iaemot_sum")] %>% na.omit
aus_k_autism_long_sdq_emot <- melt(setDT(aus_k_autism_wide_sdq_emot), id.vars = c("numericID","hicid","zf02m1","diag.age"), variable.name = "sweep")

aus_k_autism_long_sdq_emot <- aus_k_autism_long_sdq_emot %>%
  mutate(Sweep = case_when(
    sweep == "caemot_sum" ~ 1,
    sweep == "daemot_sum" ~ 2,
    sweep == "eaemot_sum" ~ 3,
    sweep == "faemot_sum" ~ 4,
    sweep == "gaemot_sum" ~ 5,
    sweep == "haemot_sum" ~ 6,
    sweep == "iaemot_sum" ~ 7)
    )



## emot GMM

aus_k_diag_emot_gmm1 <- hlme(value ~ Sweep, subject = "numericID", random=~1, ng = 1, data =
aus_k_autism_long_sdq_emot)
summary(aus_k_diag_emot_gmm1)


aus_k_diag_emot_gmm2 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 2, data = aus_k_autism_long_sdq_emot, mixture = ~ Sweep,
nwg=T, B = aus_k_diag_emot_gmm1)
summary(aus_k_diag_emot_gmm2)


aus_k_diag_emot_gmm3 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 3, data = aus_k_autism_long_sdq_emot, mixture = ~ Sweep, 
nwg=T, B = aus_k_diag_emot_gmm1)
summary(aus_k_diag_emot_gmm3)

aus_k_diag_emot_gmm4 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 4, data = aus_k_autism_long_sdq_emot, mixture = ~ Sweep, 
nwg=T, B = aus_k_diag_emot_gmm1)
summary(aus_k_diag_emot_gmm4)

# make a table with results for the models:
fit_ind_aus_k_emot <- summarytable(aus_k_diag_emot_gmm1, aus_k_diag_emot_gmm2, aus_k_diag_emot_gmm3, aus_k_diag_emot_gmm4, which = c("AIC","BIC","SABIC","%class","entropy","npm","loglik"))




age_k <- c("5","7","9","11","13","15","17")
aus_k_autism_long_sdq_emot$numericID <- as.character(aus_k_autism_long_sdq_emot$numericID)
aus_k_diag_emot_people2 <- as.data.frame(aus_k_diag_emot_gmm2$pprob[,1:2])

aus_k_autism_long_sdq_emot_gmm2 <- full_join(aus_k_autism_long_sdq_emot, aus_k_diag_emot_people2, by = "numericID")
aus_k_autism_long_sdq_emot_gmm2$numericID <- as.character(aus_k_autism_long_sdq_emot_gmm2$numericID)
aus_k_autism_long_sdq_emot_gmm2$class <- as.factor(aus_k_autism_long_sdq_emot_gmm2$class)
aus_k_autism_long_sdq_emot$group_aus_k_diag_emot_gmm2_s <- factor(aus_k_diag_emot_people2$class[unlist(sapply(aus_k_autism_long_sdq_emot$numericID, function(x) which(aus_k_diag_emot_people2$numeircID==x)))])


# Conduct problems

## condb GMM data prep
aus_k_autism_wide_sdq_condb <- aus_k_diag_autism[,c("numericID","hicid","zf02m1","diag.age","cacondb_sum","dacondb_sum","eacondb_sum","facondb_sum","gacondb_sum","hacondb_sum","iacondb_sum")] %>% na.omit
aus_k_autism_long_sdq_condb <- melt(setDT(aus_k_autism_wide_sdq_condb), id.vars = c("numericID","hicid","zf02m1","diag.age"), variable.name = "sweep")

aus_k_autism_long_sdq_condb <- aus_k_autism_long_sdq_condb %>%
  mutate(Sweep = case_when(
    sweep == "cacondb_sum" ~ 1,
    sweep == "dacondb_sum" ~ 2,
    sweep == "eacondb_sum" ~ 3,
    sweep == "facondb_sum" ~ 4,
    sweep == "gacondb_sum" ~ 5,
    sweep == "hacondb_sum" ~ 6,
    sweep == "iacondb_sum" ~ 7)
    )



## condb GMM

aus_k_diag_condb_gmm1 <- hlme(value ~ Sweep, subject = "numericID", random=~1, ng = 1, data =
aus_k_autism_long_sdq_condb)
summary(aus_k_diag_condb_gmm1)


aus_k_diag_condb_gmm2 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 2, data = aus_k_autism_long_sdq_condb, mixture = ~ Sweep,
nwg=T, B = aus_k_diag_condb_gmm1)
summary(aus_k_diag_condb_gmm2)


aus_k_diag_condb_gmm3 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 3, data = aus_k_autism_long_sdq_condb, mixture = ~ Sweep, 
nwg=T, B = aus_k_diag_condb_gmm1)
summary(aus_k_diag_condb_gmm3)

aus_k_diag_condb_gmm4 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 4, data = aus_k_autism_long_sdq_condb, mixture = ~ Sweep, 
nwg=T, B = aus_k_diag_condb_gmm1)
summary(aus_k_diag_condb_gmm4)

# make a table with results for the models:
fit_ind_aus_k_condb <- summarytable(aus_k_diag_condb_gmm1, aus_k_diag_condb_gmm2, aus_k_diag_condb_gmm3, aus_k_diag_condb_gmm4, which = c("AIC","BIC","SABIC","%class","entropy","npm","loglik"))


age_k <- c("5","7","9","11","13","15","17")
#aus_k_autism_long_sdq_condb$numericID <- as.character(aus_k_autism_long_sdq_condb$numericID)
aus_k_diag_condb_people2 <- as.data.frame(aus_k_diag_condb_gmm2$pprob[,1:2])

aus_k_autism_long_sdq_condb_gmm2 <- full_join(aus_k_autism_long_sdq_condb, aus_k_diag_condb_people2, by = "numericID")
aus_k_autism_long_sdq_condb_gmm2$numericID <- as.character(aus_k_autism_long_sdq_condb_gmm2$numericID)
aus_k_autism_long_sdq_condb_gmm2$class <- as.factor(aus_k_autism_long_sdq_condb_gmm2$class)
aus_k_autism_long_sdq_condb$group_aus_k_diag_condb_gmm2_s <- factor(aus_k_diag_condb_people2$class[unlist(sapply(aus_k_autism_long_sdq_condb$numericID, function(x) which(aus_k_diag_condb_people2$numeircID==x)))])

# Hyperactivity
## hypr GMM data prep

aus_k_autism_wide_sdq_hypr <- aus_k_diag_autism[,c("numericID","hicid","zf02m1","diag.age","cahypr_sum","dahypr_sum","eahypr_sum","fahypr_sum","gahypr_sum","hahypr_sum","iahypr_sum")] %>% na.omit
aus_k_autism_long_sdq_hypr <- melt(setDT(aus_k_autism_wide_sdq_hypr), id.vars = c("numericID","hicid","zf02m1","diag.age"), variable.name = "sweep")

aus_k_autism_long_sdq_hypr <- aus_k_autism_long_sdq_hypr %>%
  mutate(Sweep = case_when(
    sweep == "cahypr_sum" ~ 1,
    sweep == "dahypr_sum" ~ 2,
    sweep == "eahypr_sum" ~ 3,
    sweep == "fahypr_sum" ~ 4,
    sweep == "gahypr_sum" ~ 5,
    sweep == "hahypr_sum" ~ 6,
    sweep == "iahypr_sum" ~ 7)
    )



## hypr GMM

aus_k_diag_hypr_gmm1 <- hlme(value ~ Sweep, subject = "numericID", random=~1, ng = 1, data =
aus_k_autism_long_sdq_hypr)
summary(aus_k_diag_hypr_gmm1)


aus_k_diag_hypr_gmm2 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 2, data = aus_k_autism_long_sdq_hypr, mixture = ~ Sweep,
nwg=T, B = aus_k_diag_hypr_gmm1)
summary(aus_k_diag_hypr_gmm2)


aus_k_diag_hypr_gmm3 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 3, data = aus_k_autism_long_sdq_hypr, mixture = ~ Sweep, 
nwg=T, B = aus_k_diag_hypr_gmm1)
summary(aus_k_diag_hypr_gmm3)

aus_k_diag_hypr_gmm4 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 4, data = aus_k_autism_long_sdq_hypr, mixture = ~ Sweep, 
nwg=T, B = aus_k_diag_hypr_gmm1)
summary(aus_k_diag_hypr_gmm4)

# make a table with results for the models:
fit_ind_aus_k_hypr <- summarytable(aus_k_diag_hypr_gmm1, aus_k_diag_hypr_gmm2, aus_k_diag_hypr_gmm3, aus_k_diag_hypr_gmm4, which = c("AIC","BIC","SABIC","%class","entropy","npm","loglik"))


age_k <- c("5","7","9","11","13","15","17")
#aus_k_autism_long_sdq_hypr$numericID <- as.character(aus_k_autism_long_sdq_hypr$numericID)
aus_k_diag_hypr_people2 <- as.data.frame(aus_k_diag_hypr_gmm2$pprob[,1:2])

aus_k_autism_long_sdq_hypr_gmm2 <- full_join(aus_k_autism_long_sdq_hypr, aus_k_diag_hypr_people2, by = "numericID")
aus_k_autism_long_sdq_hypr_gmm2$numericID <- as.character(aus_k_autism_long_sdq_hypr_gmm2$numericID)
aus_k_autism_long_sdq_hypr_gmm2$class <- as.factor(aus_k_autism_long_sdq_hypr_gmm2$class)
aus_k_autism_long_sdq_hypr$group_aus_k_diag_hypr_gmm2_s <- factor(aus_k_diag_hypr_people2$class[unlist(sapply(aus_k_autism_long_sdq_hypr$numericID, function(x) which(aus_k_diag_hypr_people2$numeircID==x)))])



# Peer
## Peer GMM data prep

aus_k_autism_wide_sdq_peer <- aus_k_diag_autism[,c("numericID","hicid","zf02m1","diag.age","capeer_sum","dapeer_sum","eapeer_sum","fapeer_sum","gapeer_sum","hapeer_sum","iapeer_sum")] %>% na.omit
aus_k_autism_long_sdq_peer <- melt(setDT(aus_k_autism_wide_sdq_peer), id.vars = c("numericID","hicid","zf02m1","diag.age"), variable.name = "sweep")

aus_k_autism_long_sdq_peer <- aus_k_autism_long_sdq_peer %>%
  mutate(Sweep = case_when(
    sweep == "capeer_sum" ~ 1,
    sweep == "dapeer_sum" ~ 2,
    sweep == "eapeer_sum" ~ 3,
    sweep == "fapeer_sum" ~ 4,
    sweep == "gapeer_sum" ~ 5,
    sweep == "hapeer_sum" ~ 6,
    sweep == "iapeer_sum" ~ 7)
    )



## Peer GMM

aus_k_diag_peer_gmm1 <- hlme(value ~ Sweep, subject = "numericID", random=~1, ng = 1, data =
aus_k_autism_long_sdq_peer)
summary(aus_k_diag_peer_gmm1)


aus_k_diag_peer_gmm2 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 2, data = aus_k_autism_long_sdq_peer, mixture = ~ Sweep,
nwg=T, B = aus_k_diag_peer_gmm1)
summary(aus_k_diag_peer_gmm2)


aus_k_diag_peer_gmm3 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 3, data = aus_k_autism_long_sdq_peer, mixture = ~ Sweep, 
nwg=T, B = aus_k_diag_peer_gmm1)
summary(aus_k_diag_peer_gmm3)

aus_k_diag_peer_gmm4 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 4, data = aus_k_autism_long_sdq_peer, mixture = ~ Sweep, 
nwg=T, B = aus_k_diag_peer_gmm1)
summary(aus_k_diag_peer_gmm4)

# make a table with results for the models:
fit_ind_aus_k_peer <- summarytable(aus_k_diag_peer_gmm1, aus_k_diag_peer_gmm2, aus_k_diag_peer_gmm3, aus_k_diag_peer_gmm4, which = c("AIC","BIC","SABIC","%class","entropy","npm","loglik"))

age_k <- c("5","7","9","11","13","15","17")
#aus_k_autism_long_sdq_peer$numericID <- as.character(aus_k_autism_long_sdq_peer$numericID)
aus_k_diag_peer_people2 <- as.data.frame(aus_k_diag_peer_gmm2$pprob[,1:2])

aus_k_autism_long_sdq_peer_gmm2 <- full_join(aus_k_autism_long_sdq_peer, aus_k_diag_peer_people2, by = "numericID")
aus_k_autism_long_sdq_peer_gmm2$numericID <- as.character(aus_k_autism_long_sdq_peer_gmm2$numericID)
aus_k_autism_long_sdq_peer_gmm2$class <- as.factor(aus_k_autism_long_sdq_peer_gmm2$class)
# aus_k_autism_long_sdq_peer$group_aus_k_diag_peer_gmm2_s <- factor(aus_k_diag_peer_people2$class[unlist(sapply(aus_k_autism_long_sdq_peer$numericID, function(x) which(aus_k_diag_peer_people2$numeircID==x)))])


# Prosocialness

## psoc GMM data prep

aus_k_autism_wide_sdq_psoc <- aus_k_diag_autism[,c("numericID","hicid","zf02m1","diag.age","capsoc_sum","dapsoc_sum","eapsoc_sum","fapsoc_sum","gapsoc_sum","hapsoc_sum","iapsoc_sum")] %>% na.omit
aus_k_autism_long_sdq_psoc <- melt(setDT(aus_k_autism_wide_sdq_psoc), id.vars = c("numericID","hicid","zf02m1","diag.age"), variable.name = "sweep")

aus_k_autism_long_sdq_psoc <- aus_k_autism_long_sdq_psoc %>%
  mutate(Sweep = case_when(
    sweep == "capsoc_sum" ~ 1,
    sweep == "dapsoc_sum" ~ 2,
    sweep == "eapsoc_sum" ~ 3,
    sweep == "fapsoc_sum" ~ 4,
    sweep == "gapsoc_sum" ~ 5,
    sweep == "hapsoc_sum" ~ 6,
    sweep == "iapsoc_sum" ~ 7)
    )



## psoc GMM

aus_k_diag_psoc_gmm1 <- hlme(value ~ Sweep, subject = "numericID", random=~1, ng = 1, data =
aus_k_autism_long_sdq_psoc)
summary(aus_k_diag_psoc_gmm1)


aus_k_diag_psoc_gmm2 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 2, data = aus_k_autism_long_sdq_psoc, mixture = ~ Sweep,
nwg=T, B = aus_k_diag_psoc_gmm1)
summary(aus_k_diag_psoc_gmm2)


aus_k_diag_psoc_gmm3 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 3, data = aus_k_autism_long_sdq_psoc, mixture = ~ Sweep, 
nwg=T, B = aus_k_diag_psoc_gmm1)
summary(aus_k_diag_psoc_gmm3)

aus_k_diag_psoc_gmm4 <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 4, data = aus_k_autism_long_sdq_psoc, mixture = ~ Sweep, 
nwg=T, B = aus_k_diag_psoc_gmm1)
summary(aus_k_diag_psoc_gmm4)

# make a table with results for the models:
fit_ind_aus_k_psoc <- summarytable(aus_k_diag_psoc_gmm1, aus_k_diag_psoc_gmm2, aus_k_diag_psoc_gmm3, aus_k_diag_psoc_gmm4, which = c("AIC","BIC","SABIC","%class","entropy","npm","loglik"))




age_k <- c("5","7","9","11","13","15","17")
#aus_k_autism_long_sdq_psoc$numericID <- as.character(aus_k_autism_long_sdq_psoc$numericID)
aus_k_diag_psoc_people2 <- as.data.frame(aus_k_diag_psoc_gmm2$pprob[,1:2])

aus_k_autism_long_sdq_psoc_gmm2 <- full_join(aus_k_autism_long_sdq_psoc, aus_k_diag_psoc_people2, by = "numericID")
aus_k_autism_long_sdq_psoc_gmm2$numericID <- as.character(aus_k_autism_long_sdq_psoc_gmm2$numericID)
aus_k_autism_long_sdq_psoc_gmm2$class <- as.factor(aus_k_autism_long_sdq_psoc_gmm2$class)
aus_k_autism_long_sdq_psoc$group_aus_k_diag_psoc_gmm2_s <- factor(aus_k_diag_psoc_people2$class[unlist(sapply(aus_k_autism_long_sdq_psoc$numericID, function(x) which(aus_k_diag_psoc_people2$numeircID==x)))])


aus_k_gmm_grp <- cbind(aus_k_autism_long_sdq_total_gmm2,aus_k_autism_long_sdq_emot_gmm2,aus_k_autism_long_sdq_hypr_gmm2,aus_k_autism_long_sdq_psoc_gmm2) 

aus_k_gmm_grp <- aus_k_gmm_grp[,c(1,2,3,4,8,16,24,32)] %>% distinct(hicid, .keep_all = TRUE)    
colnames(aus_k_gmm_grp) <- c("numericID","hicid","sex","diag.age","ttl","emot","hypr","psoc")
aus_k_gmm_grp <- aus_k_gmm_grp %>% unique()
aus_k_grp_table_ttl <- table(aus_k_gmm_grp$diag.age,aus_k_gmm_grp$ttl)
aus_k_grp_table_emo <- table(aus_k_gmm_grp$diag.age,aus_k_gmm_grp$emot)
aus_k_grp_table_hyp <- table(aus_k_gmm_grp$diag.age,aus_k_gmm_grp$hypr)
aus_k_grp_table_pro <- table(aus_k_gmm_grp$diag.age,aus_k_gmm_grp$psoc)
aus_k_grp_table <- rbind(aus_k_grp_table_ttl, aus_k_grp_table_emo,aus_k_grp_table_hyp, aus_k_grp_table_pro)
write.csv(aus_k_grp_table, file = "/Users/aus_k_gmm_grp.csv")

aus_k_autism_tip_regr <- aus_k_autism_tip[,c(1,69,80,77)]
colnames(aus_k_autism_tip_regr) <- c("hicid","maternal_age","eth","ses_PC1")
aus_k_gmm_tip_regression <- merge(aus_k_autism_tip_regr, aus_k_gmm_grp,by = "hicid") %>% distinct()
write.csv(aus_k_gmm_grp, file = "/Users/ausk_gmm_grp_membership.csv")


# regression model

aus_k_fit_all <- lm(diag.age ~ sex + eth + maternal_age + ses_PC1  + ttl+ hypr  + psoc, data= aus_k_gmm_tip_regression)
summary(aus_k_fit_all)

# emotional symptoms group were removed as it is perfectly multicollineary with ttl group

tab_model(aus_k_fit_all)
aus_k_fit_sdq <- lm(diag.age ~  ttl  + hypr  + psoc, data= aus_k_gmm_tip_regression)
summary(aus_k_fit_sdq)



# Multilevel mediation 


library(lavaan)

aus_k_gmm_tip_regression <- as.data.frame(lapply(aus_k_gmm_tip_regression, as.numeric))
aus_k_model_1 <- "diag.age ~ sex  + eth + maternal_age + ses_PC1  + ttl  + hypr  + psoc"
aus_k_fit_1 <- lavaan::sem(aus_k_model_1, data = aus_k_gmm_tip_regression)
ausk_fit_cor <- lavInspect(aus_k_fit_1, what = "cor.all")
misty::dominance.manual(ausk_fit_cor) 



aus_k_model_2 <- "
  # direct effects
  diag.age ~ s*sex  + e*eth + m*maternal_age + se*ses_PC1  + t*ttl + h*hypr  + pr*psoc
  # mediation paths
  
  ttl ~   se1*ses_PC1 + m1*maternal_age  + s1*sex + e1*eth
  
  hypr ~   se4*ses_PC1 + m4*maternal_age  + s4*sex + e4*eth
  
  psoc ~   se6*ses_PC1 + m6*maternal_age  + s6*sex + e6*eth
  
  
indirect_ttl := s1*t + e1*t + m1*t + se1*t
 
 indirect_hypr := s4*h+ e4*h +m4*h+ se4*h

 indirect_psoc := s6*pr + e6*pr +m6*pr+ se6*pr
 
direct := s + e + m + se 
total_indirect := indirect_ttl + indirect_hypr + indirect_psoc 
total_effect := direct + total_indirect
"


set.seed(060524)
aus_k_fit_2 <- lavaan::sem(aus_k_model_2, data = aus_k_gmm_tip_regression,se = "bootstrap", missing = "fiml", bootstrap = 1000)
aus_k_fit_2_sum <- lavaan::summary(aus_k_fit_2, standardized = TRUE, rsq = T,fit = TRUE, ci = TRUE, nd = 7) 
aus_k_fit_2_sum
# Get parameter estimates with specified formatting
aus_k_fit_2_est <- lavaan::parameterEstimates(
  aus_k_fit_2,
  boot.ci.type = "bca.simple",
  standardized = TRUE,
  rsq = T
)

# Display the formatted parameter estimates
print(aus_k_fit_2_est)

write.csv(aus_k_fit_2_est, file = "/Users/k_fit_2.csv")



===================================================================

## Mental health conditions

aus_k14_MH <- aus_k7 %>% dplyr::filter(hicid %in% aus_k_diag_autism$hicid) %>% dplyr::select(hicid,zf02m1,ihs19b20,ihs17v2,ihs17v1,ihs37v2,ihs37v3,ihs54a,ihs54b,ihs54c,ihs54d,ihs54e,ismfq,ismfqc)
aus_k14_MH <- aus_k14_MH %>%
  mutate_all(~ replace(., . < 0, NA))

aus_k14_MH <- aus_k14_MH %>% mutate_at(vars(c("ihs54a","ihs54b","ihs54c","ihs54d")),~(replace(., . == 2, 0)))

ausk_MH <- merge(aus_k14_MH,aus_k_gmm_grp, by = c("hicid"), all.y = T )


ausk_anxiety <- ausk_MH %>% 
  group_by(ttl, zf02m1,ihs17v1)%>%
  dplyr::summarize(count = n())
ausk_anxiety

ausk_depression <- ausk_MH %>% 
  group_by(ttl, zf02m1,ihs17v2)%>%
  dplyr::summarize(count = n())
ausk_depression



ausk_anx_mod <- glm(ihs17v1 ~ ttl + zf02m1, data = ausk_MH, family = binomial)
ausk_anx_modsum <- broom::tidy(ausk_anx_mod)
ausk_anx_mod_int <- glm(ihs17v1 ~ ttl + zf02m1 + ttl:zf02m1, data = ausk_MH, family = binomial)
ausk_anx_mod_intsum <- broom::tidy(ausk_anx_mod_int)

ausk_depre_mod <- glm(ihs17v2 ~ ttl + zf02m1, data = ausk_MH, family = binomial)
ausk_depre_modsum <- broom::tidy(ausk_depre_mod)
ausk_depre_mod_int <- glm(ihs17v2 ~ ttl + zf02m1 + ttl:zf02m1, data = ausk_MH, family = binomial)
ausk_depre_mod_intsum <- broom::tidy(ausk_depre_mod_int)

ausk_diag_mod_sum <- rbind(ausk_anx_modsum,ausk_anx_mod_intsum,ausk_depre_modsum,ausk_depre_mod_intsum)
ausk_diag_mod_sum



ausk_smfq_count <- ausk_MH[!is.na(ausk_MH$ismfq), ] %>% 
  group_by(ttl, zf02m1)%>%
  dplyr::summarize(count = n())
ausk_smfq_count

ausk_smfq_cutoff <- ausk_MH[!is.na(ausk_MH$ismfqc), ] %>% 
  group_by(ttl, zf02m1,ismfqc)%>%
  dplyr::summarize(count = n())
ausk_smfq_cutoff
ausk_smfq <- ausk_MH %>%
  dplyr::group_by(ttl,zf02m1) %>%
  dplyr::summarize(
    smf_Median = median(ismfq, na.rm = TRUE),
    smf_Q1 = quantile(ismfq, probs = 0.25, na.rm = TRUE),
    smf_Q3 = quantile(ismfq, probs = 0.75, na.rm = TRUE)
  )  
ausk_smfq

ausk_smfq_grp <- ausk_MH %>%
  dplyr::group_by(ttl) %>%
  dplyr::summarize(
    smf_Median = median(ismfq, na.rm = TRUE),
    smf_Q1 = quantile(ismfq, probs = 0.25, na.rm = TRUE),
    smf_Q3 = quantile(ismfq, probs = 0.75, na.rm = TRUE)
  )  
ausk_smfq_grp

ausk_smfq_sex <- ausk_MH %>%
  dplyr::group_by(zf02m1) %>%
  dplyr::summarize(
    smf_Median = median(ismfq, na.rm = TRUE),
    smf_Q1 = quantile(ismfq, probs = 0.25, na.rm = TRUE),
    smf_Q3 = quantile(ismfq, probs = 0.75, na.rm = TRUE)
  )  
ausk_smfq_sex

ausk_smfq_ova <- ausk_MH %>%
  dplyr::summarize(
    smf_Median = median(ismfq, na.rm = TRUE),
    smf_Q1 = quantile(ismfq, probs = 0.25, na.rm = TRUE),
    smf_Q3 = quantile(ismfq, probs = 0.75, na.rm = TRUE)
  )  
ausk_smfq_ova




ausk_smfq_model_poisson <- glm(ismfq ~ ttl + zf02m1, family = poisson, data = ausk_MH)
ausk_smfq_model_poissonsum <- broom::tidy(ausk_smfq_model_poisson)
ausk_smfq_model_poisson_int <- glm(ismfq ~ ttl + zf02m1 + ttl:zf02m1, family = poisson, data = ausk_MH)
ausk_smfq_model_poisson_intsum <- broom::tidy(ausk_smfq_model_poisson_int)
ausk_smfq_sum <- rbind(ausk_smfq_model_poissonsum,ausk_smfq_model_poisson_intsum)
ausk_smfq_sum



smf.diff <- wilcox.test(ismfq ~ ttl, data = ausk_MH)
smf.diff

smf.diff.sex <- wilcox.test(ismfq ~ zf02m1, data = ausk_MH)
smf.diff.sex

smf.diff.sex.1 <- wilcox.test(ismfq ~ zf02m1, data = ausk_MH[ausk_MH$ttl == 1,])
smf.diff.sex.1

smf.diff.sex.2 <- wilcox.test(ismfq ~ zf02m1, data = ausk_MH[ausk_MH$ttl == 2,])
smf.diff.sex.2

smf.diff.male <- wilcox.test(ismfq ~ ttl, data = ausk_MH[ausk_MH$zf02m1 == 1,])
smf.diff.male
smf.diff.female <- wilcox.test(ismfq ~ ttl, data = ausk_MH[ausk_MH$zf02m1 == 2,])
smf.diff.female





## self-harm and suicide

ausk_harmthought <- ausk_MH %>% 
  group_by(ttl, zf02m1,ihs54a)%>%
  dplyr::summarize(count = n())
ausk_harmthought

ausk_harmact <- ausk_MH %>% 
  group_by(ttl, zf02m1,ihs54b)%>%
  dplyr::summarize(count = n())
ausk_harmact

ausk_suic_ide<- ausk_MH %>% 
  group_by(ttl, zf02m1,ihs54c)%>%
  dplyr::summarize(count = n())
ausk_suic_ide


ausk_suic_plan <- ausk_MH %>% 
  group_by(ttl, zf02m1,ihs54d)%>%
  dplyr::summarize(count = n())
ausk_suic_plan

ausk_MH$sui_attempt <- ifelse(ausk_MH$ihs54e > 0, 1, ausk_MH$ihs54e)
ausk_suic_attempt <- ausk_MH %>% 
  group_by(ttl, zf02m1,sui_attempt)%>%
  dplyr::summarize(count = n())
ausk_suic_attempt



ausk_MH$self_harm_thought <- ifelse(ausk_MH$ihs54a == 2,0,ausk_MH$ihs54a)
ausk_harmthought_mod <- glm(self_harm_thought ~ ttl + zf02m1, data = ausk_MH, family = binomial)
ausk_harmthought_modsum <- broom::tidy(ausk_harmthought_mod)
ausk_harmthought_mod_int <- glm(self_harm_thought ~ ttl + zf02m1 + ttl:zf02m1, data = ausk_MH, family = binomial)
ausk_harmthought_mod_intsum <- broom::tidy(ausk_harmthought_mod_int)


ausk_harmact_mod <- glm(ihs54b ~ ttl + zf02m1, data = ausk_MH, family = binomial)
ausk_harmact_modsum <- broom::tidy(ausk_harmact_mod)
ausk_harmact_mod_int <- glm(ihs54b ~ ttl + zf02m1 + ttl:zf02m1, data = ausk_MH, family = binomial)
ausk_harmact_mod_intsum <- broom::tidy(ausk_harmact_mod_int)

ausk_suic_ide_mod <- glm(ihs54c ~ ttl + zf02m1, data = ausk_MH, family = binomial)
ausk_suic_ide_modsum <- broom::tidy(ausk_suic_ide_mod)
ausk_suic_ide_mod_int <- glm(ihs54c ~ ttl + zf02m1 + ttl:zf02m1, data = ausk_MH, family = binomial)
ausk_suic_ide_mod_intsum <- broom::tidy(ausk_suic_ide_mod_int)

ausk_suic_plan_mod <- glm(ihs54d ~ ttl + zf02m1, data = ausk_MH, family = binomial)
ausk_suic_plan_modsum <- broom::tidy(ausk_suic_plan_mod)
ausk_suic_plan_mod_int <- glm(ihs54d ~ ttl + zf02m1 + ttl:zf02m1, data = ausk_MH, family = binomial)
ausk_suic_plan_mod_intsum <- broom::tidy(ausk_suic_plan_mod_int)

ausk_suic_attempt_mod <- glm(sui_attempt ~ ttl + zf02m1, data = ausk_MH, family = binomial)
ausk_suic_attempt_modsum <- broom::tidy(ausk_suic_attempt_mod)
ausk_suic_attempt_mod_int <- glm(sui_attempt ~ ttl + zf02m1 + ttl:zf02m1, data = ausk_MH, family = binomial)
ausk_suic_attempt_mod_intsum <- broom::tidy(ausk_suic_attempt_mod_int)

ausk_harmsuic_mod_summary <- rbind(ausk_harmthought_modsum,ausk_harmthought_mod_intsum,ausk_harmact_modsum,ausk_harmact_mod_intsum,ausk_suic_ide_modsum,ausk_suic_ide_mod_intsum,ausk_suic_plan_modsum,ausk_suic_plan_mod_intsum,ausk_suic_attempt_modsum,ausk_suic_attempt_mod_intsum)
ausk_harmsuic_mod_summary

