library(readr)
library(tidyverse)
library(naniar)
library(fastDummies)
library(ggplot2)
library(lavaan)
library(lcmm)


## Load data

mcs2_parent_cm <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5350-tab/tab/mcs2_parent_cm_interview.tab", show_col_types = FALSE)
mcs2_parent_cm$cmid <- paste(mcs2_parent_cm$MCSID,mcs2_parent_cm$BCNUM00, sep = "")
mcs3_parent_cm <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5795-tab/tab/mcs3_parent_cm_interview.tab", show_col_types = FALSE)
mcs3_parent_cm$cmid <- paste(mcs3_parent_cm$MCSID,mcs3_parent_cm$CCNUM00, sep = "")

mcs4_parent_cm <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-6411-tab/tab/mcs4_parent_cm_interview.tab", show_col_types = FALSE)
mcs4_parent_cm$cmid <- paste(mcs4_parent_cm$MCSID,mcs4_parent_cm$DCNUM00, sep = "")

mcs5_parent_cm <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-7464-tab/tab/mcs5_parent_cm_interview.tab", show_col_types = FALSE)
mcs5_parent_cm$cmid <- paste(mcs5_parent_cm$MCSID,mcs5_parent_cm$ECNUM00, sep = "")

mcs6_parent_cm <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-8156-tab/tab/mcs6_parent_cm_interview.tab", show_col_types = FALSE)
mcs6_parent_cm$cmid <- paste(mcs6_parent_cm$MCSID,mcs6_parent_cm$FCNUM00, sep = "")

mcs7_parent_cm <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-8682-tab/tab/mcs7_parent_cm_interview.tab", show_col_types = FALSE)
mcs7_parent_cm$cmid <- paste(mcs7_parent_cm$MCSID,mcs7_parent_cm$GCNUM00, sep = "")



## Identify autism diagnosis

mcs3_asd <- mcs3_parent_cm %>%  dplyr::select(MCSID,cmid,CPNUM00,CPAUTS00)
colnames(mcs3_asd)[3] <- "PNUM"
mcs4_asd <- mcs4_parent_cm%>% dplyr::select(MCSID,cmid,DPNUM00,DPAUTS00)
mcs4_asd$DPAUTS00[mcs4_asd$DPAUTS00 == " "] <- NA
colnames(mcs4_asd)[3] <- "PNUM"
mcs5_asd <- mcs5_parent_cm  %>% dplyr::select(MCSID,cmid,EPNUM00,EPAUTS00)
colnames(mcs5_asd)[3] <- "PNUM"
mcs6_asd <- mcs6_parent_cm  %>% dplyr::select(MCSID,cmid,FPNUM00,FPAUTS00)
colnames(mcs6_asd)[3] <- "PNUM"


asd_list <- list(mcs3_asd,mcs4_asd,mcs5_asd,mcs6_asd)
asd_pattern <- unique(Reduce(function(x, y) merge(x, y, by = c('MCSID', 'cmid',"PNUM"), all = TRUE), asd_list)) %>% mutate_all(., ~ifelse(. %in% c(-1,-2,-8,-9), NA, .)) 

asd_pattern$EPAUTS00 <- ifelse(asd_pattern$DPAUTS00 == 1 & is.na(asd_pattern$EPAUTS00), 1, asd_pattern$EPAUTS00)
asd_pattern$FPAUTS00 <- ifelse(asd_pattern$EPAUTS00 == 1 & is.na(asd_pattern$FPAUTS00), 1, asd_pattern$FPAUTS00)

asd_pattern$pattern <- paste(asd_pattern$CPAUTS00,asd_pattern$DPAUTS00,asd_pattern$EPAUTS00,asd_pattern$FPAUTS00, sep = "-")
# as in sweep5 (Exxxx) and sweep6 (Fxxxx), autism diagnosis was not asked to those who recieved diagnosis, here we automatically add 1 if they reported diagnoses in the prior sweep
mcs_asd <- asd_pattern[grepl("1", asd_pattern$pattern) > 0, ]





# MCS expanded
# no limit on #NA or consecutive reports 
complete_asd_loose <- mcs_asd %>%
  mutate(
    num_diag = rowSums(dplyr::select(.,ends_with("AUTS00")) == 1, na.rm = TRUE),
    num_na = rowSums(is.na(dplyr::select(., ends_with("AUTS00")))))

asd_sample_loose <- complete_asd_loose %>% 
  dplyr::arrange(cmid, desc(num_diag), num_na) %>%
  group_by(cmid) %>% slice(1) %>% 
  ungroup() %>% 
  dplyr::select(-num_diag, - num_na)  

# Create a column for the position of the first one
asd_sample_diag_loose <- asd_sample_loose %>%
  mutate(first_one = sapply(strsplit(pattern, "-"), function(x) which(x == "1")[1])) %>%
  mutate(diag.age = case_when(
    first_one == 1 ~ 5,
    first_one == 2 ~ 7,
    first_one == 3 ~ 11,
    first_one == 4 ~ 14
  ))

# Create a column to identify if it has at least two consecutive 1's
asd_sample_diag_loose <- asd_sample_diag_loose %>%
  mutate(cons.diag = as.integer(grepl("1-1", pattern))) # N = 623
# table(asd_sample_diag_loose_cons$diag.age) 
# N5:7:11:14 = 88:127:209:154 ~ 1:1.44:2.38:1.75
table(asd_sample_diag_loose$diag.age)  # N 5:7:11:14 = 131:127:211:154



MCS_autism <- read.csv("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_SDQ_autism.csv")




mcs1_cm_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-4683-tab/tab/mcs1_cm_derived.tab", show_col_types = F)
mcs1_cm_derived$cmid <- paste(mcs1_cm_derived$MCSID, mcs1_cm_derived$ACNUM00, sep = "")
mcs1_hhgrid <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-4683-tab/tab/mcs1_hhgrid.tab", show_col_types = FALSE)

mcs1_hhgrid$cmid <- paste(mcs1_hhgrid$MCSID, mcs1_hhgrid$ACNUM00, sep = "")
mcs1_parent_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-4683-tab/tab/mcs1_parent_derived.tab", show_col_types = FALSE)
mcs2_hhgrid <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5350-tab/tab/mcs2_hhgrid.tab", show_col_types = FALSE)
mcs2_hhgrid$cmid <- paste(mcs2_hhgrid$MCSID, mcs2_hhgrid$BCNUM00, sep = "")
mcs2_cog <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5350-tab/tab/mcs2_cm_cognitive_assessment.tab", show_col_types = FALSE)
mcs2_cog$cmid <- paste(mcs2_cog$MCSID,mcs2_cog$BCNUM00, sep = "")
mcs2_cm_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5350-tab/tab/mcs2_cm_derived.tab", show_col_types = FALSE)
mcs2_cm_derived$cmid <- paste(mcs2_cm_derived$MCSID,mcs2_cm_derived$BCNUM00, sep = "")
mcs2_parent_interview <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5350-tab/tab/mcs2_parent_interview.tab",show_col_types = FALSE)
mcs2_family_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5350-tab/tab/mcs2_family_derived.tab", show_col_types = FALSE)
mcs2_geo <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5350-tab/tab/mcs2_geographically_linked_data.tab",show_col_types = FALSE)
mcs2_neighb <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5350-tab/tab/mcs2_neighbourhood_observations.tab", show_col_types = F)
mcs2_parent_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5350-tab/tab/mcs2_parent_derived.tab", show_col_types = FALSE)

mcs3_cm_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5795-tab/tab/mcs3_cm_derived.tab", show_col_types = FALSE)
mcs3_cm_derived$cmid <- paste(mcs3_cm_derived$MCSID,mcs3_cm_derived$CCNUM00, sep = "")
mcs3_parent_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5795-tab/tab/mcs3_parent_derived.tab", show_col_types = FALSE)

mcs4_cm_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-6411-tab/tab/mcs4_cm_derived.tab", show_col_types = FALSE)
mcs4_cm_derived$cmid <- paste(mcs4_cm_derived$MCSID,mcs4_cm_derived$DCNUM00, sep = "")

mcs5_cm_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-7464-tab/tab/mcs5_cm_derived.tab", show_col_types = FALSE)
mcs5_cm_derived$cmid <- paste(mcs5_cm_derived$MCSID,mcs5_cm_derived$ECNUM00, sep = "")
mcs5_cm_interview <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-7464-tab/tab/mcs5_cm_interview.tab", show_col_types = FALSE)
mcs5_cm_interview$cmid <- paste(mcs5_cm_interview$MCSID,mcs5_cm_interview$ECNUM00, sep = "")

mcs6_cm_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-8156-tab/tab/mcs6_cm_derived.tab", show_col_types = FALSE)
mcs6_cm_derived$cmid <- paste(mcs6_cm_derived$MCSID,mcs6_cm_derived$FCNUM00, sep = "")

mcs7_cm_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-8682-tab/tab/mcs7_cm_derived.tab", show_col_types = FALSE)
mcs7_cm_derived$cmid <- paste(mcs7_cm_derived$MCSID,mcs7_cm_derived$GCNUM00, sep = "")





# Demographics 
## Sex


mcs1_sex <- mcs1_hhgrid %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID, cmid,AHCSEX00)
mcs2_sex <- mcs2_hhgrid %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID, cmid,BHCSEX00)

mcs_sex <- merge(mcs1_sex,mcs2_sex, by = c("MCSID","cmid"), all = T)

mcs_sex$sex <- ifelse(!is.na(mcs_sex$AHCSEX00) & !is.na(mcs_sex$BHCSEX00),ifelse(mcs_sex$AHCSEX00 == mcs_sex$BHCSEX00, mcs_sex$AHCSEX00, -9),ifelse(!is.na(mcs_sex$AHCSEX00), mcs_sex$AHCSEX00,mcs_sex$BHCSEX00))
table(mcs_sex$sex) # M480,F143


## Maternal age at delivery

mcs1_birth_age <- mcs1_parent_derived %>% filter(MCSID %in% mcs_sex$MCSID & ADDRES00 == 1)  %>% dplyr::select(MCSID, ADDAGB00, ADDGAB00) 
names(mcs1_birth_age) <- c("MCSID","MAD","MAD_grp")

mcs2_birth_age <- mcs2_parent_derived %>% filter(MCSID %in% mcs_sex$MCSID & BDDRES00 == 1)  %>% dplyr::select(MCSID, BDDAGB00, BDDGAB00)
names(mcs2_birth_age) <- c("MCSID","MAD","MAD_grp")
mcs_birth_age <- merge(mcs1_birth_age,mcs2_birth_age,  all = T)
# Natural mother, age at birth of CM
table(mcs_birth_age$MAD_grp)


## Ethnicity

mcs1_eth <- mcs1_cm_derived %>% filter(cmid %in% mcs_sex$cmid) %>%
  dplyr::select(MCSID, cmid, ADC06E00)
mcs2_eth <- mcs2_cm_derived %>% filter(cmid %in% mcs_sex$cmid) %>% dplyr::select(MCSID, cmid, BDC06E00)
mcs3_eth <- mcs3_cm_derived %>% filter(cmid %in% mcs_sex$cmid) %>% dplyr::select(MCSID, cmid, CDC06E00)
mcs_eth <- merge(mcs1_eth, merge(mcs2_eth, mcs3_eth, by = c("MCSID","cmid"), all = T),by = c("MCSID","cmid"), all = T)


mcs_eth$eth <-  coalesce(mcs_eth$ADC06E00, mcs_eth$BDC06E00, mcs_eth$CDC06E00)
mcs_eth[mcs_eth < 0] <- NA # 618 available ethnicity
table(mcs_eth$eth) # 1White=550; 2Mixed = 19; 3Indian = 3; 4Pakistani and Bangladeshi= 18; 5Black or Black British= 20; 6Other Ethnic group (inc Chinese,Other)= 8 
mcs_eth_mad <- merge(mcs_eth, mcs_birth_age, by = "MCSID", all = T)


## Extract SDQs (parent-repor) aacross sweeps

mcs2_SDQ <- mcs2_cm_derived %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID, cmid, BEMOTION,BCONDUCT,BHYPER,BPEER,BPROSOC,BEBDTOT) %>% mutate_all(., ~ifelse(. %in% c(-1,-2,-8,-9), NA, .)) 
mcs3_SDQ <- mcs3_cm_derived %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID, cmid, CEMOTION,CCONDUCT,CHYPER,CPEER,CPROSOC,CEBDTOT)%>% mutate_all(., ~ifelse(. %in% c(-1,-2,-8,-9), NA, .)) 
mcs4_SDQ <- mcs4_cm_derived %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID, cmid, DDEMOTION,DDCONDUCT,DDHYPER,DDPEER,DDPROSOC,DDDEBDTOT)%>% mutate_all(., ~ifelse(. %in% c(-1,-2,-8,-9), NA, .)) 
mcs5_SDQ_raw <- mcs5_cm_interview %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid,EPSDPF00,EPSDRO00,EPSDHS00,EPSDSR00,EPSDTT00,
EPSDSP00,EPSDOR00,EPSDMW00,EPSDHU00,EPSDFS00,
EPSDGF00,EPSDFB00,EPSDUD00,EPSDLC00,EPSDDC00,
EPSDNC00,EPSDKY00,EPSDOA00,EPSDPB00,EPSDVH00,
EPSDST00,EPSDCS00,EPSDGB00,EPSDFE00,EPSDTE00) 
mcs5_SDQ_raw_rc <- mcs5_SDQ_raw %>% dplyr::mutate(across(EPSDPF00:EPSDTE00, ~as.numeric(case_when(
    . == 1 ~ 0,
    . == 2 ~ 1,
    . == 3 ~ 2,
    . %in% c(4,-1,-9) ~ NA
  ))))
mcs5_SDQ <- mcs5_SDQ_raw_rc %>%
  dplyr::mutate(
    EEMOTION = rowSums(dplyr::select(., EPSDHS00,EPSDMW00,EPSDUD00,EPSDNC00,EPSDFE00)),
    ECONDUCT = rowSums(dplyr::select(.,EPSDTT00,EPSDFB00,EPSDOA00,EPSDCS00,EPSDOR00)),
    EHYPER = rowSums(dplyr::select(., EPSDRO00,EPSDFS00,EPSDDC00,EPSDST00,EPSDTE00)),
    EPEER = rowSums(dplyr::select(.,EPSDSP00,EPSDPB00,EPSDGB00,EPSDGF00,EPSDLC00)),
    EPROSOC = rowSums(dplyr::select(.,EPSDPF00,EPSDSR00,EPSDHU00,EPSDKY00,EPSDVH00)),
    EEBDTOT = rowSums(across(c(EEMOTION, ECONDUCT, EHYPER, EPEER))))
mcs5_SDQ <- mcs5_SDQ %>% dplyr::select(MCSID,cmid, EEMOTION, ECONDUCT,EHYPER,EPEER,EPROSOC,EEBDTOT)
mcs6_SDQ <- mcs6_cm_derived %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID, cmid, FEMOTION,FCONDUCT,FHYPER,FPEER,FPROSOC,FEBDTOT)%>% mutate_all(., ~ifelse(. %in% c(-1,-2,-8,-9), NA, .)) 
mcs7_SDQ <- mcs7_cm_derived %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID, cmid, GEMOTION,GCONDUCT,GHYPER,GPEER,GPROSOC,GEBDTOT)%>% mutate_all(., ~ifelse(. %in% c(-1,-2,-8,-9), NA, .)) 



asd_loose_SDQ_list <- list(mcs2_SDQ,mcs3_SDQ,mcs4_SDQ,mcs5_SDQ,mcs6_SDQ,mcs7_SDQ)
asd_loose_SDQ <- unique(Reduce(function(x, y) merge(x, y, by = c('MCSID', 'cmid'), all = TRUE), asd_loose_SDQ_list))
asd_loose_SDQ_complete<- asd_loose_SDQ %>% na.omit()



mcar_test(asd_loose_SDQ) # missing completely at random
asd_loose_SDQ <- merge(mcs_sex[c(1:2,5)], asd_loose_SDQ, by = c("MCSID","cmid"))
#asd_loose_SDQ <- asd_loose_SDQ[rowSums(is.na(asd_loose_SDQ[, 4:39])) < 35, ] # remove all NA rows
asd_loose_SDQ <- merge(asd_loose_SDQ, asd_sample_diag_loose[c(1:2,10)],  by = c("MCSID","cmid")) %>% dplyr::mutate(group = case_when(
  diag.age %in% c(5,7,11) ~ "Early",
  diag.age == 14 ~ "Late"
))

asd_loose_SDQ_complete <- merge(mcs_sex[c(1:2,5)], asd_loose_SDQ_complete,  by = c("MCSID","cmid"), all.x = F, all.y = T)
asd_loose_SDQ_complete <- merge(asd_loose_SDQ_complete, asd_sample_diag_loose[c(1:2,10)],  by = c("MCSID","cmid")) %>% dplyr::mutate(group = case_when(
  diag.age %in% c(5,7,11) ~ "Early",
  diag.age == 14 ~ "Late"
))





sex_ratio_diag_age <- asd_loose_SDQ %>%
  group_by(diag.age, sex) %>%
  dplyr::summarize(count = n())
sex_ratio_diag_age

sex_ratio_diag_age <-  sex_ratio_diag_age%>%
  dplyr::mutate(percentage = count / sum(count) * 100)
sex_ratio_diag_age$diag.age <- as.factor(sex_ratio_diag_age$diag.age)
sex_ratio_diag_age$sex <- as.factor(sex_ratio_diag_age$sex)
# Create the stacked bar chart using ggplot2
viridis_colors <- viridis::viridis_pal(option = "rocket")(length(unique(sex_ratio_diag_age$sex)))

ggplot(sex_ratio_diag_age, aes(x = diag.age, y = percentage, fill = sex)) +
  geom_col(position = "stack") +
  labs(title = "Diagnosed Autism by Age Group and Sex",
       x = "diagnosis age",
       y = "percentage",
       fill = "Sex") + scale_fill_manual(values = setNames(viridis_colors, unique(sex_ratio_diag_age$sex)), 
                    labels = c("Male", "Female"),
                    guide = guide_legend(title = "Sex")) +theme_classic()

## LGCM

mcs_loose_agestr_ttl <- "
int =~ 1*BEBDTOT + 1*CEBDTOT + 1*DDDEBDTOT + 1*EEBDTOT + 1*FEBDTOT + 1*GEBDTOT
slp =~ 3*BEBDTOT + 5*CEBDTOT + 7*DDDEBDTOT + 11*EEBDTOT + 14*FEBDTOT + 17*GEBDTOT

# the parametres for slope reflect the designed ages at corresponding sweeps
"


fit_mcs_loose_agestr_ttl <- growth(mcs_loose_agestr_ttl, data = asd_loose_SDQ, group = "group", missing = "fiml", estimator = "ml", fixed.x = F)
fit_mcs_loose_agestr_ttl_r <- growth(mcs_loose_agestr_ttl, data = asd_loose_SDQ, group = "group", missing = "fiml", estimator = "mlr", fixed.x = F)

summary(fit_mcs_loose_agestr_ttl)
summary(fit_mcs_loose_agestr_ttl_r)




mcs_loose_agestr_ttl_adj_2 <- "
int =~ 1*BEBDTOT + 1*CEBDTOT + 1*DDDEBDTOT + 1*EEBDTOT + 1*FEBDTOT + 1*GEBDTOT
slp =~ 3*BEBDTOT + 5*CEBDTOT + 7*DDDEBDTOT + 11*EEBDTOT + 14*FEBDTOT + 17*GEBDTOT
qua =~ 9*BEBDTOT + 25*CEBDTOT + 49*DDDEBDTOT + 121*EEBDTOT + 196*FEBDTOT + 289*GEBDTOT
# GEBDTOT ~~ 1*GEBDTOT
# the parametres for slope reflect the designed ages at corresponding sweeps
"

fit_mcs_loose_agestr_ttl_adj_2 <- growth(mcs_loose_agestr_ttl_adj_2, data = asd_loose_SDQ, group = "group", missing = "fiml", estimator = "ml", fixed.x = F)
summary(fit_mcs_loose_agestr_ttl_adj_2)
# removed group = "grp_num" , 


## cubic 


mcs_loose_agestr_ttl_adj_3 <- "
int =~ 1*BEBDTOT + 1*CEBDTOT + 1*DDDEBDTOT + 1*EEBDTOT + 1*FEBDTOT + 1*GEBDTOT
slp =~ .3*BEBDTOT + .5*CEBDTOT + .7*DDDEBDTOT + 1.1*EEBDTOT + 1.4*FEBDTOT + 1.7*GEBDTOT
qua =~ .09*BEBDTOT + .25*CEBDTOT + .49*DDDEBDTOT + 1.21*EEBDTOT + 1.96*FEBDTOT + 2.89*GEBDTOT
cub =~ .027*BEBDTOT + .125*CEBDTOT + .343*DDDEBDTOT + 1.331*EEBDTOT + 2.744*FEBDTOT + 4.913*GEBDTOT
# the parametres for slope reflect the designed ages at corresponding sweeps
"


fit_mcs_loose_agestr_ttl_adj_3 <- growth(mcs_loose_agestr_ttl_adj_3, data = asd_loose_SDQ, group = "group", missing = "fiml", estimator = "ml", fixed.x = F)
summary(fit_mcs_loose_agestr_ttl_adj_2)



fitMeasures(mcs_ttl_fit_adj,c("rmsea","chisq","pvalue","cfi","tli","aic","bic"))
fitMeasures(mcs_agestr_ttl_fit_adj,c("rmsea","chisq","pvalue","cfi","tli","aic","bic"))
fitMeasures(mcs_agestr_ttl_fit_adj_2, c("rmsea","chisq","pvalue","cfi","tli","aic","bic"))
fitMeasures(mcs_agestr_ttl_fit_adj_3, c("rmsea","chisq","pvalue","cfi","tli","aic","bic"))




fitMeasures(fit_mcs_loose_agestr_ttl_adj,c("rmsea","chisq","pvalue","cfi","tli","aic","bic"))
fitMeasures(fit_mcs_loose_agestr_ttl_adj_2, c("rmsea","chisq","pvalue","cfi","tli","aic","bic"))
fitMeasures(fit_mcs_loose_agestr_ttl_adj_3, c("rmsea","chisq","pvalue","cfi","tli","aic","bic"))



pred_lgm_qua_loose <- as.data.frame(predict(fit_mcs_loose_agestr_ttl_adj_2))
# create long data for each individual

pred_lgm_long_qua_loose <- map(c(3,5,7,11,14,17), # loop over time
                     function(x) pred_lgm_qua[, 1] + x * pred_lgm_qua[, 2] + x^2 * pred_lgm_qua_loose[,3]) %>% 
  reduce(cbind) %>% # bring together the wave predictions 
  as.data.frame() %>% # make data frame
  setNames(c(3,5,7,11,14,17)) %>% # give names to variables
  mutate(id = row_number()) %>% # make unique id
  gather(-id, key = Sweep, value = pred) # make long format

pred_lgm_lin_loose <- as.data.frame(predict(fit_mcs_loose_agestr_ttl_adj))
pred_lgm_long_lin_loose <-  map(c(3,5,7,11,14,17), # loop over time
                     function(x) pred_lgm_lin_loose[, 1] + x * pred_lgm_lin_loose[, 2]) %>% 
  reduce(cbind) %>% # bring together the wave predictions 
  as.data.frame() %>% # make data frame
  setNames(c(3,5,7,11,14,17)) %>% # give names to variables
  mutate(id = row_number()) %>% # make unique id
  gather(-id, key = Sweep, value = pred) # make long format




# Plot
ggplot() +
  stat_summary(
    data = pred_lgm_long_lin_loose,
    aes(x = as.numeric(Sweep), y = pred, group = 1, linetype = "linear"),
    fun = mean,
    geom = "line",
    size = 1.5
  ) +
  stat_summary(
    data = pred_lgm_long_qua_loose,
    aes(x = as.numeric(Sweep), y = pred, group = 1, linetype = "quadratic"),
    fun = mean,
    geom = "line",
    size = 1.5
  ) +
  theme_bw() +
  labs(y = "SDQ total", x = "Sweep") 






library(data.table)
# Early 
mcs_asd_loose_early <- asd_loose_SDQ[asd_loose_SDQ$group == "Early",]
mcs_asd_loose_late <- asd_loose_SDQ[asd_loose_SDQ$group == "Late",]
mcs_asd_loose_early_ttl <- mcs_asd_loose_early[,c(2,3,9,15,21,27,33,39)]

mcs_asd_loose_early_ttl_long <- data.table::melt(setDT(mcs_asd_loose_early_ttl), id.vars = c("cmid","sex"), variable.name = "sweep")

mcs_asd_loose_early_ttl_summary <- mcs_asd_loose_early_ttl_long %>%
  dplyr::group_by(sweep) %>%
  dplyr::summarise(
    sd = sd(value, na.rm = TRUE),
    ttl_mean = mean(value, na.rm = TRUE)
  )
mcs_asd_loose_early_ttl_summary$group <- "early"

# Late

mcs_asd_loose_late_ttl <- mcs_asd_loose_late[,c(2,3,9,15,21,27,33,39)]

mcs_asd_loose_late_ttl_long <- melt(setDT(mcs_asd_loose_late_ttl), id.vars = c("cmid","sex"), variable.name = "sweep")

mcs_asd_loose_late_ttl_summary <- mcs_asd_loose_late_ttl_long %>%
   dplyr::group_by(sweep) %>%
   dplyr::summarise(
    sd = sd(value, na.rm = TRUE),
    ttl_mean = mean(value, na.rm = TRUE)
  )
mcs_asd_loose_late_ttl_summary$group <- "late"

# No diagnosis
MCS_no_diag <- read.csv("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_SDQ_control.csv") # 6047 in total
MCS_no_diag$sex_num <- ifelse(MCS_no_diag$Sex == "Male", 1,2)
MCS_no_diag$grp <- "no_diag"
MCS_no_diag$grp_num <- 3
MCS_sdq_no_diag <- MCS_no_diag[,c(1:21,34:39,22:33,40:45)]
MCS_no_diag_sdq_ttl <- MCS_sdq_no_diag[,c(1,9,15,21,27,33,39,42)]

MCS_no_diag_sdq_ttl_long <- melt(setDT(MCS_no_diag_sdq_ttl), id.vars = c("MCSID","Sex"), variable.name = "sweep")

MCS_no_diag_ttl_summary <- MCS_no_diag_sdq_ttl_long %>%
   dplyr::group_by(sweep) %>%
   dplyr::summarise(
    sd = sd(value),
    ttl_mean = mean(value)
  )
MCS_no_diag_ttl_summary$group <- "no diag"


mcs_asd_loose_early_ttl_summary$lb = mcs_asd_loose_early_ttl_summary$ttl_mean - mcs_asd_loose_early_ttl_summary$sd
mcs_asd_loose_early_ttl_summary$ub = mcs_asd_loose_early_ttl_summary$ttl_mean + mcs_asd_loose_early_ttl_summary$sd
mcs_asd_loose_late_ttl_summary$lb = mcs_asd_loose_late_ttl_summary$ttl_mean - mcs_asd_loose_late_ttl_summary$sd
mcs_asd_loose_late_ttl_summary$ub = mcs_asd_loose_late_ttl_summary$ttl_mean + mcs_asd_loose_late_ttl_summary$sd

mcs_loose_sdq_total_mean_full <- full_join(mcs_asd_loose_early_ttl_summary, mcs_asd_loose_late_ttl_summary)
mcs_loose_sdq_total_mean_full <- mcs_loose_sdq_total_mean_full %>% dplyr::mutate(sweep.age = case_when(
  sweep == "BEBDTOT" ~ 3,
  sweep == "CEBDTOT" ~ 5,
  sweep == "DDDEBDTOT" ~ 7,
   sweep == "EEBDTOT" ~ 11,
   sweep == "FEBDTOT" ~ 14,
   sweep == "GEBDTOT" ~ 17,
))





pred_lgm_qua_early_loose <- as.data.frame(predict(fit_mcs_loose_agestr_ttl_adj_2)$"Early")

pred_lgm_qua_late_loose <- as.data.frame(predict(fit_mcs_loose_agestr_ttl_adj_2)$"Late")


pred_lgm_long_qua_early_loose <- map(c(3,5,7,11,14,17), # loop over time
                     function(x) pred_lgm_qua_early_loose[, 1] + x * pred_lgm_qua_early_loose[, 2] + x^2 * pred_lgm_qua_early_loose[,3]) %>% 
  reduce(cbind) %>% # bring together the wave predictions 
  as.data.frame() %>% # make data frame
  setNames(c(3,5,7,11,14,17)) %>% # give names to variables
  dplyr::mutate(id = row_number()) %>% # make unique id
  gather(-id, key = Sweep, value = pred) %>% dplyr::mutate(group = "early")

pred_lgm_long_qua_late_loose <- map(c(3,5,7,11,14,17), # loop over time
                     function(x) pred_lgm_qua_late_loose[, 1] + x * pred_lgm_qua_late_loose[, 2] + x^2 * pred_lgm_qua_late_loose[,3]) %>% 
  reduce(cbind) %>% # bring together the wave predictions 
  as.data.frame() %>% # make data frame
  setNames(c(3,5,7,11,14,17)) %>% # give names to variables
  dplyr::mutate(id = row_number()) %>% # make unique id
  gather(-id, key = Sweep, value = pred) %>% dplyr::mutate(group = "late")


## load the linear coefficients
pred_lgm_lin_early_loose <- as.data.frame(predict(fit_mcs_loose_agestr_ttl)$"Early")
pred_lgm_lin_late_loose <- as.data.frame(predict(fit_mcs_loose_agestr_ttl)$"Late")

pred_lgm_long_lin_early_loose <- map(c(3,5,7,11,14,17), # loop over time
                     function(x) pred_lgm_lin_early_loose[, 1] + x * pred_lgm_lin_early_loose[, 2] ) %>% 
  reduce(cbind) %>% # bring together the wave predictions 
  as.data.frame() %>% # make data frame
  setNames(c(3,5,7,11,14,17)) %>% # give names to variables
  dplyr::mutate(id = row_number()) %>% # make unique id
  gather(-id, key = Sweep, value = pred) %>% dplyr::mutate(group = "early")

pred_lgm_long_lin_late_loose <- map(c(3,5,7,11,14,17), # loop over time
                     function(x) pred_lgm_lin_late_loose[, 1] + x * pred_lgm_lin_late_loose[, 2]) %>% 
  reduce(cbind) %>% # bring together the wave predictions 
  as.data.frame() %>% # make data frame
  setNames(c(3,5,7,11,14,17)) %>% # give names to variables
  dplyr::mutate(id = row_number()) %>% # make unique id
  gather(-id, key = Sweep, value = pred) %>% dplyr::mutate(group = "late")



colnames(mcs_loose_sdq_total_mean_full)[7] <- "Sweep"
# Plot

custom_viridis_palette <- viridis::viridis(2)

ggplot(mcs_loose_sdq_total_mean_full, aes(x = as.numeric(Sweep), y = ttl_mean, colour = group)) + geom_line(data = mcs_loose_sdq_total_mean_full, aes(x = as.numeric(Sweep), y = ttl_mean, colour = group)) + geom_point()  + geom_ribbon(data = mcs_loose_sdq_total_mean_full, aes(x = as.numeric(Sweep),ymin = lb, ymax = ub), linetype = 4, alpha = 0.2) + scale_color_viridis_d(option = "magma") +
  stat_summary(
    data = pred_lgm_long_lin_early_loose,
    aes(x = as.numeric(Sweep), y = pred,  linetype = "linear", colour = "early"),
    fun = mean,
    geom = "line",
    size = 1
  ) +
  stat_summary(
    data = pred_lgm_long_lin_late_loose,
    aes(x = as.numeric(Sweep), y = pred,  linetype = "linear", colour = "late"),
    fun = mean,
    geom = "line",
    size = 1
  ) +
stat_summary(
    data = pred_lgm_long_qua_early_loose,
    aes(x = as.numeric(Sweep), y = pred,  linetype = "quadratic", colour = "early"),
    fun = mean,
    geom = "line",
    size = 1
  ) +
stat_summary(
    data = pred_lgm_long_qua_late_loose,
    aes(x = as.numeric(Sweep), y = pred,  linetype = "quadratic", colour = "late"),
    fun = mean,
    geom = "line",
    size = 1
  ) +
  theme_classic() +
  labs(y = "SDQ total", x = "Age")  





asd_loose_SDQ_gmm <- dplyr::mutate(asd_loose_SDQ, numericID = row_number())

asd_loose_wide_sdq_ttl <- asd_loose_SDQ_gmm[,c("numericID","cmid","sex","diag.age","BEBDTOT","CEBDTOT", "DDDEBDTOT" ,"EEBDTOT","FEBDTOT","GEBDTOT")]
asd_loose_long_sdq_ttl <- melt(setDT(asd_loose_wide_sdq_ttl), id.vars = c("numericID","cmid","sex","diag.age"), variable.name = "sweep")
asd_loose_long_sdq_ttl <- asd_loose_long_sdq_ttl %>%
  mutate(Sweep = case_when(
    sweep == "BEBDTOT" ~ 2,
    sweep == "CEBDTOT" ~ 3,
    sweep == "DDDEBDTOT" ~ 4,
    sweep == "EEBDTOT" ~ 5,
    sweep == "FEBDTOT" ~ 6,
    sweep == "GEBDTOT" ~ 7)
    )



## Growth Mixture Modelling


library(lcmm)
age <- c("3","5","7","11","14","17")
mcs_ttl_gmm1_loose <- hlme(value ~ Sweep, subject = "numericID", random=~1, ng = 1, data =asd_loose_long_sdq_ttl)
summary(mcs_ttl_gmm1_loose)


mcs_ttl_gmm2_loose <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 2, data = asd_loose_long_sdq_ttl, mixture = ~ Sweep,
nwg=T, B = mcs_ttl_gmm1_loose)
summary(mcs_ttl_gmm2_loose)



mcs_ttl_gmm3_loose <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 3, data = asd_loose_long_sdq_ttl, mixture = ~ Sweep,
nwg=T, B = mcs_ttl_gmm1_loose)
summary(mcs_ttl_gmm3_loose)

mcs_ttl_gmm4_loose <- hlme(value ~ Sweep, subject = "numericID", random=~1,
ng = 4, data = asd_loose_long_sdq_ttl, mixture = ~ Sweep,
nwg=T, B = mcs_ttl_gmm1_loose)
summary(mcs_ttl_gmm4_loose)

# make a table with results for the 3 models:
fit_ind <- summarytable(mcs_ttl_gmm1_loose, mcs_ttl_gmm2_loose,mcs_ttl_gmm3_loose,mcs_ttl_gmm4_loose,which = c("AIC","BIC","SABIC","%class","entropy","npm","loglik"))





mcs_loose_ttl_people2 <- as.data.frame(mcs_ttl_gmm2_loose$pprob[,1:2])
asd_loose_long_sdq_ttl <- merge(asd_loose_long_sdq_ttl,mcs_loose_ttl_people2, by = "numericID")

asd_loose_long_sdq_ttl <- asd_loose_long_sdq_ttl %>% dplyr::mutate(Sweep.age = case_when(Sweep == 2 ~ 3,Sweep == 3 ~ 5, Sweep == 4 ~ 7, Sweep == 5 ~ 11, Sweep == 6 ~ 14, Sweep == 7 ~ 17 ))

asd_loose_long_sdq_ttl$Sweep.age <- as.numeric(asd_loose_long_sdq_ttl$Sweep.age)
asd_loose_long_sdq_ttl$class <- as.factor(asd_loose_long_sdq_ttl$class)
p_mcs_loose_ttl_gmm2_s <- ggplot(asd_loose_long_sdq_ttl, aes(Sweep.age, value, group=numericID, colour= class)) + geom_smooth(aes(group=numericID, colour=class),size=0.1, se=F) + geom_smooth(aes(group=class), method="loess", size=2, se=T)  + scale_y_continuous(limits = c(0,40)) + scale_x_continuous(breaks = as.numeric(age),labels = age) + labs(x="Age(years)",y="SDQ_ttl",colour="Latent Class") + theme_classic()


my_colors <- brewer.pal(12, "Paired")[c(4,10)]
p_mcs_loose_ttl_gmm2 <- ggplot(asd_loose_long_sdq_ttl, aes(x = Sweep.age, y = value, group = numericID, colour = class)) +
  geom_line(size = 0.1) +
  geom_smooth(aes(group = class), method = "loess", size = 2, se = TRUE) +
  scale_y_continuous(limits = c(0, 40)) +
  scale_x_continuous(breaks = as.numeric(age), labels = age) +
  labs(x = "Age (years)", y = "MCS SDQ Total Score", colour = "Latent Class") +
  scale_colour_nejm()+
  theme_classic()


suppressWarnings(print(p_mcs_loose_ttl_gmm2))
suppressWarnings(print(p_mcs_loose_ttl_gmm2_s))



my_colors_stack <- brewer.pal(12, "Paired")[c(6,5,10,9)]
legend_labels <- c("Class 1-Male", "Class 1-Female", "Class 2-Male", "Class 2-Female")

loose_ttl_stack <- ggplot(asd_loose_long_sdq_ttl,  aes(x = factor(diag.age), fill = interaction(sex,class))) +
  geom_bar(position="fill") + scale_y_continuous(labels = scales::percent) +
  labs(x = "diagnosis age", y = "percentage") + scale_fill_manual(values = my_colors_stack, labels = legend_labels, name = "Class - Sex")+
  theme_minimal()

loose_ttl_stack


# Imputation prep: cover as wide as possible related variables, test for missing completely at random
## MCS2 age 3

# behavioural data
mcs2_item_level <- mcs2_parent_cm %>% filter(cmid %in% mcs_sex$cmid & BELIG00 == 1) %>% dplyr::select(MCSID,cmid,BPDRDA00,BPCLDA00,BPSPLM0A,BPSPLM0B,BPSPLM0C,BPSPLM0D,BPSPLM0E,BPSPLM0F,BPSPLM0G,BPSPLM0H,BPSPLM0I,BPSPLM0J,BPSPLM0K,BPSPLM0L,BPWOHD00,BPWOHC0A,BPWOHC0B,BPWOHC0C,BPSDPF00,BPSDRO00,BPSDHS00,BPSDSR00,BPSDTT00,BPSDSP00,BPSDOR00,BPSDMW00,BPSDHU00,BPSDFS00,BPSDGF00,BPSDFB00,BPSDUD00,BPSDLC00,BPSDDC00,BPSDNC00,BPSDKY00,BPSDOA00,BPSDPB00,BPSDVH00,BPSDST00,BPSDCS00,BPSDGB00,BPSDFE00,BPSDTE00,BPSDEM00,BPSDLD00,BPSDDD00,BPSDHL00,BPSDFR00,BPSDCL00,BPSDLA00,BPSDDB00,BPSEWS00,BPSEMS00,BPSEHT00,BPSEOE00,BPSEAO00,BPSEEF00,BPSEUQ00,BPSEDT00,BPSENA00,BPSEIA00,BPPIAW00,BPPIST00,BPPICO00,BPPIPT00,BPPIVA00,BPPIBP00,BPPISI00,BPPIAN00,BPPIET00,BPPIAR00,BPPIDE00,BPPIBD00,BPPIUC00,BPPISM00,BPPISE00)
mcs2_item_4na <- c("BPDRDA00","BPCLDA00","BPSEWS00","BPSEMS00","BPSEHT00","BPSEOE00","BPSEAO00","BPSEEF00","BPSEUQ00","BPSEDT00","BPSENA00","BPSEIA00","BPSDPF00","BPSDRO00","BPSDHS00","BPSDSR00","BPSDTT00","BPSDSP00","BPSDOR00","BPSDMW00","BPSDHU00","BPSDFS00","BPSDGF00","BPSDFB00","BPSDUD00","BPSDLC00","BPSDDC00","BPSDNC00","BPSDKY00","BPSDOA00","BPSDPB00","BPSDVH00","BPSDST00","BPSDCS00","BPSDGB00","BPSDFE00","BPSDTE00")
mcs2_item_5na <- c("BPSDEM00","BPSDLD00","BPSDDD00","BPSDHL00","BPSDFR00","BPSDCL00","BPSDLA00","BPSDDB00")

mcs2_item_6na <- c("BPPIAW00","BPPIST00","BPPICO00","BPPIPT00","BPPIVA00","BPPIBP00","BPPISI00","BPPIAN00","BPPIET00","BPPIAR00","BPPIDE00","BPPIBD00","BPPIUC00","BPPISM00","BPPISE00")
mcs2_item_86na <- c("BPWOHC0A","BPWOHC0B","BPWOHC0C")
mcs2_item_level <- mcs2_item_level %>% 
  dplyr::mutate(across(all_of(mcs2_item_4na), ~ ifelse(. == 4 , NA,.))) %>%                     dplyr::mutate(across(all_of(mcs2_item_5na), ~ ifelse(. == 5 , NA,.))) %>%
  dplyr::mutate(across(all_of(mcs2_item_6na), ~ ifelse(. == 6 , NA,.))) %>%
  dplyr::mutate(across(all_of(mcs2_item_86na), ~ ifelse(. == 86 , NA,.))) %>%
  dplyr::mutate(across(everything(), ~ ifelse(. < 0 , NA, .)))
mcs2_item_level_dummy <-  dummy_cols(
mcs2_item_level,select_columns = c("BPWOHC0A","BPWOHC0B","BPWOHC0C"), remove_first_dummy = FALSE, ignore_na = TRUE,
remove_selected_columns = TRUE)
mcs2_item_level <- dplyr::select(mcs2_item_level_dummy, -contains("NA"))



mcs2_cm_derived_var <- mcs2_cm_derived %>% filter(cmid %in% mcs_sex$cmid) %>% dplyr::select(MCSID,cmid, BDCSBI00,BDCSBE00,BDMPIA00,BDMVLD00,BEMOTION, BCONDUCT,BHYPER,BPEER,BPROSOC,BEBDTOT,BIMPACT,BEBDDIFF)
mcs2_cm_derived_var[mcs2_cm_derived_var<0] <- NA
mcs2_cm_derived_var$BEBDDIFF[mcs2_cm_derived_var$BEBDDIFF == 4] <- NA

# CSBI = Child Social Behaviour Questionnaire (Independence-Dysregulation)  
# CSBE = Child Social Behaviour Questionnaire (Emotional-Dysregulation)  
# MPIA = child-parent relationship scale (CPRS)
# MVLD = CPRS number of valid responses
# SDQ total and subscale scores
# IMPACT = SDQ impact
# DIFF = Has difficulties in one or more areas

mcs2_cm_vars <- merge(mcs2_item_level,mcs2_cm_derived_var, by = c("MCSID","cmid"), all = T)
# 549 individuals on 92 variables


{r eval = FALSE}
parent_concern <- mcs2_cm_vars %>% filter(BPWOHC0A == 11|BPWOHC0B == 11| BPWOHC0C ==11) %>% dplyr::select(MCSID,cmid) # N = 14
asd_pattern_par_concern <- asd_sample_diag_loose[asd_sample_diag_loose$cmid %in% parent_concern$cmid,] # those whose main parents had "Concerns about Autism-Aspergers etc" all got a diagnosis before or at age 7.


{r eval=FALSE}
asd_not_in_mcs2 <- asd_sample_diag_loose[!asd_sample_diag_loose$cmid %in% mcs2_cm_vars$cmid, c(1,2,8,10)]

### Cognitive ability (those included in ID identifier)

mcs2_cog_item <- mcs2_cog %>% dplyr::filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid,BCASAG00,BCRKNAGE,BDCOSC00,BDLESC00,BDNOSC00,BDSZSC00,BDCMSC00,BDSHSC00,BDBSRC00,BDCMAS00,BDLMAS00,BDNMAS00,BDSMAS00,BDOMAS00,BDHMAS00,BDSRCM00,BDSRCS00,BDSRCP00,BDSRCN00,BDBASR00,BDBASA00,BDBASP00,BDBAST00,BDHODC00,BCENVI00,BCTOYS00,BCSEEC00,BCCOMF00,BCDARK00,BCRCLE00,BCUNCL00,BCTVNS00,BCCONV00,BCENTH00,BCINTC00,BCINTA00,BCPTIV00,BCNEGA00,BCBEHA00,BCINTE00,BCFOCU00,BCFEAR00,BCREAC00,BCIMPU00,BCBREA00,BCHARM00,BCSPEA00,BCMCON00,BCANSW00,BCPRAI00,BCKISS00,BCINTI00,BCSCOL00,BCPHYS00,BCSLAP00)

mcs2_cog_item[mcs2_cog_item < 0] <- NA
mcs2_cog_3na <- c("BCENVI00","BCTOYS00","BCDARK00","BCRCLE00","BCSPEA00","BCMCON00","BCANSW00","BCPRAI00","BCINTI00","BCSCOL00")
mcs2_cog_item <- mcs2_cog_item %>% dplyr::mutate(across(all_of(mcs2_cog_3na), ~ ifelse(. == 3 , NA,.)))




### Sociodemographics-family level

mcs2_parent_derived_vars <- mcs2_parent_derived %>% filter(MCSID %in% asd_sample_diag_loose$MCSID & BELIG00 == 1) %>% dplyr::select(MCSID,BDD05S00,BDKESS00,BDDACT00,BDDRLG00,BDDNVQ00,BDACAQ00)
mcs2_parent_derived_vars[mcs2_parent_derived_vars < 0]<- NA
# 96 = none of the qualification, coded as 0 so that vars become ordinal, larger values indicating higher qualifications
mcs2_parent_derived_vars <- mcs2_parent_derived_vars %>% dplyr::mutate(across(BDDNVQ00:BDACAQ00, ~ ifelse(. == 96, 0,.))) 
# 95 = overseas qualifications only, created dummy variables for this specifically, then code 95 to NA in original data.
mcs2_parent_derived_vars$Bos_NVQ_qual <- ifelse(is.na(mcs2_parent_derived_vars$BDDNVQ00), NA, ifelse(mcs2_parent_derived_vars$BDDNVQ00 == 95, 1, 0))
mcs2_parent_derived_vars$Bos_aca_qual <- ifelse(is.na(mcs2_parent_derived_vars$BDACAQ00), NA, ifelse(mcs2_parent_derived_vars$BDACAQ00 == 95, 1, 0))
mcs2_parent_derived_vars <- mcs2_parent_derived_vars %>% dplyr::mutate(across(BDDNVQ00:BDACAQ00, ~ ifelse(. == 95, NA,.)))

# transformed economic activity and religions to dummy variables
mcs2_parent_derived_dummy <-  dummy_cols(
mcs2_parent_derived_vars, select_columns =  c("BDDACT00","BDDRLG00"), remove_first_dummy = FALSE, ignore_na = TRUE,
remove_selected_columns = TRUE)
mcs2_parent_derived_dummy <- dplyr::select(mcs2_parent_derived_dummy, -contains("NA"))


# Main carer qualification
mcs2_parent_interview_item <- mcs2_parent_interview %>% filter(MCSID %in% asd_sample_diag_loose$MCSID & BELIG00 == 1) %>% dplyr::select(MCSID, BPLOSA00,BPDEAN00,BPTRDE00,BPPARC00,BPDIIG00,BPDISM00,BPDISH00,BPDIBN00,BPDITR00,BPDITE00,BPDIBR00,BPPHDE00,BPPHHO00,BPPHRF00,BPPHEE00,BPPHWO00,BPPHNE00,BPPESH00,BPPEFP00,BPRESE00,BPRELS00,BPRELO00,BPRESN00,BPCOOK00,BPLKIL00,BPGECA00,BPARGD00,BPREIS00,BPHARE00,BPFORC00,BPCOLT00,BPWALI00,BPHOSA00,BPAREA00,BPARAR00,BPHODI00,BPHOTH00,BPHOCA00) 
mcs2_parent_interview_item <- mcs2_parent_interview_item %>% dplyr::mutate(across(BPPARC00:BPARGD00, ~ ifelse(. == 6, NA,.))) # 6 = can't say
mcs2_parent_interview_item$BPHARE00[mcs2_parent_interview_item$BPHARE00 == 8] <-NA
mcs2_parent_interview_item$BPFORC00[mcs2_parent_interview_item$BPFORC00 == 3] <- NA
mcs2_parent_interview_item$BPCOLT00[mcs2_parent_interview_item$BPCOLT00 == 5] <- NA
mcs2_parent_interview_item$BPWALI00[mcs2_parent_interview_item$BPWALI00 == 11] <- NA
mcs2_parent_interview_item[mcs2_parent_interview_item < 0] <- NA



mcs2_other_tip <- mcs2_family_derived %>% filter(MCSID %in% asd_sample_diag_loose$MCSID) %>% dplyr::select(MCSID, BACTRY00,BAREGN00,BDOEDS00,BDOEDE00,BDOEDP00,BDMCSC00,BDMCEQ00,BDMCPO00,BDSTRA00,BDROOW00,BDHINC00,BOEDEX00,BOECDUK0,BOECDSC0,BDRSMB12,BDMBMI00)

mcs2_other_tip$BAREGN00[mcs2_other_tip$BAREGN00==13] <- NA
mcs2_other_tip[mcs2_other_tip < 0] <- NA # 547 in sample # only 1 with no valid data
# https://doc.ukdataservice.ac.uk/doc/5795/mrdoc/pdf/mcs1-5_user_guide_ed9_2020-08-07.pdf Stratum, in england, there were advantaged, disadvantaged, AND ethnic minority stratum, but not in other countries
mcs2_other_tip$eth_dis <- ifelse(is.na(mcs2_other_tip$BDSTRA00), NA,ifelse(mcs2_other_tip$BDSTRA00 == 3,1,0))
# code the rest advantaged disadvantaged as 0/1 across countries
mcs2_other_tip$stratum <- ifelse(is.na(mcs2_other_tip$BDSTRA00)| mcs2_other_tip$BDSTRA00 == 3, NA, ifelse(mcs2_other_tip$BDSTRA00 %in% c(1,4,6,8),0,1))
# remove the original column
mcs2_other_tip$BDSTRA00 <- NULL
mcs2_other_tip_dummy <-  dummy_cols(
mcs2_other_tip,select_columns = "BDROOW00", remove_first_dummy = FALSE, ignore_na = TRUE,
remove_selected_columns = TRUE)
mcs2_other_tip <- dplyr::select(mcs2_other_tip_dummy, -contains("NA"))

########## region, country##########


### Deprivation (geographical linked data, deprivation of living area)


mcs2_england <- mcs2_geo %>% filter(bactry00 == "1")
mcs2_wales   <- mcs2_geo %>% filter(bactry00 == "2")
mcs2_scotland<- mcs2_geo %>% filter(bactry00 == "3")
mcs2_norire  <- mcs2_geo %>% filter(bactry00 == "4")

mcs2_england_dep <- dplyr::select(mcs2_england, mcsid, bactry00,bmorpcde, BIMDSCOE,BIMDINCE,BIMDEMPE,BIMDHDDE,BIMDESTE) 
colnames(mcs2_england_dep) <- c("MCSID","bcountry","brural","BOverall","BIncome","BEmployment","BHealthDisability","BEduSkillTrain")
mcs2_wales_dep <- dplyr::select(mcs2_wales, mcsid, bactry00,bmorpcde, BIWIMDSC,BIWIMDIN,BIWIMDEM,BIWIMDHD,BIWIMDES)
colnames(mcs2_wales_dep) <- c("MCSID","bcountry","brural","BOverall","BIncome","BEmployment","BHealthDisability","BEduSkillTrain")
mcs2_scotland_dep <- dplyr::select(mcs2_scotland, mcsid, bactry00,bsixfold, BISIMDSC,BISIMDIN,BISIMDEM,BISIMDHD,BISIMDES)
colnames(mcs2_scotland_dep) <- c("MCSID","bcountry","brural","BOverall","BIncome","BEmployment","BHealthDisability","BEduSkillTrain")
# recode scotland sixfold scale to threefold so that later can be combined with other countries' scales
mcs2_scotland_dep <- mcs2_scotland_dep %>% dplyr::mutate(
    brural = case_when(
      brural %in% c(1, 2) ~ 1,
      brural %in% c(3, 4) ~ 2,
      brural %in% c(5, 6) ~ 3,
    ))
    
mcs2_norire_dep <- dplyr::select(mcs2_norire, mcsid, bactry00,bnirus, BIMDSCON, BIMDINCN,BIMDEMPN,BIMDHDDN,BIMDESTN)
colnames(mcs2_norire_dep) <- c("MCSID","bcountry","brural","BOverall","BIncome","BEmployment","BHealthDisability","BEduSkillTrain")
mcs2_dep <- rbind(mcs2_england_dep, mcs2_wales_dep, mcs2_scotland_dep, mcs2_norire_dep) 
mcs2_dep <- subset(mcs2_dep,MCSID != "M12575F")
mcs2_dep_asd <- mcs2_dep %>% filter(MCSID %in% asd_sample_diag_loose$MCSID) # N = 547




### Neighbourhood level

mcs2_neighb_item <- mcs2_neighb %>% filter(MCSID %in% asd_sample_diag_loose$MCSID) %>% dplyr:: select(MCSID,BACTRY00,BAREGN00,BNGCND00,BNBSEC00,BNTCLM00,BNVTRF00,BNBOCR00,BNLITR00,BNDFCS00,BNGRFT00,BNVAND00,BNRWDY00,BNSFTY00)
mcs2_neighb_item$BAREGN00[mcs2_neighb_item$BAREGN00 == 13] <- NA

replace_blank_with_na <- function(column) {
  return(ifelse(trimws(column) == "", NA, column))
}
mcs2_neighb_item[4:ncol(mcs2_neighb_item)] <- lapply(mcs2_neighb_item[4:ncol(mcs2_neighb_item)], replace_blank_with_na)



merge_dataframes <- function(df1, df2) {
  merged_df <- merge(df1, df2, by = c("MCSID", "cmid"), all = TRUE)
  return(merged_df[!duplicated(merged_df[c("MCSID", "cmid")]), ])
}
 

merge_dataframes_fam <- function(df1, df2) {
  merged_df <- merge(df1, df2, by = "MCSID", all = TRUE)
  return(merged_df[!duplicated(merged_df["MCSID"]), ])
 
}



mcs2_indi_list <- list(mcs_sex,mcs_eth_mad,mcs2_cog_item,mcs2_cm_vars)
names(mcs2_indi_list) <- c("mcs_sex","mcs_eth_mad","mcs2_cog_item","mcs2_cm_vars")
mcs2_fam_list <- list(mcs2_parent_derived_vars,mcs2_parent_interview_item,mcs2_other_tip,mcs2_dep_asd,mcs2_neighb_item)
names(mcs2_fam_list) <- c("mcs2_parent_derived_vars","mcs2_parent_interview_item","mcs2_other_tip","mcs2_dep_asd","mcs2_neighb_item")


mcs2_indi <- Reduce(merge_dataframes, mcs2_indi_list)
mcs2_fam <- Reduce(merge_dataframes_fam,mcs2_fam_list)
mcs2_voi  <-  merge(mcs2_indi, mcs2_fam, by = "MCSID", all.x = TRUE)

 

remove_cols_with_na = function(df){
    vari_delete = colnames(df)[which(colSums(is.na(df)) >= 0.10*nrow(df))]
    df[, vari_delete] = NA
  df = janitor::remove_empty(df, which = "cols")
  
  return(df)
}

remove_low_signal_cols = function(df){
  vari_delete = sapply(df, function(x) {
    is_numeric <- is.numeric(x)
    is_integer <- is.integer(x)
  
    if (is_numeric || (is_integer)) {
      # If numeric, or integer (not ordered factor), check variance
      return(var(x, na.rm = TRUE) < 0.01)
    } else {
      return(FALSE)
    }
  })
  df[, names(which(vari_delete))] = NA
  df = janitor::remove_empty(df, which = "cols")
  return(df)
}

for (col in names(mcs2_voi)) {
  if (is.ordered(mcs2_voi[[col]]) || (is.factor(mcs2_voi[[col]]) || is.character(mcs2_voi[[col]]))) {
    mcs2_voi[[col]] <- as.integer(mcs2_voi[[col]])
  }
}

mcs2_corr_data = mcs2_voi[,9:ncol(mcs2_voi)]
#corr_data <- remove_cols_with_na(corr_data)
mcs2_corr_data <- remove_low_signal_cols(mcs2_corr_data)
mcs2_corrs <- qgraph::cor_auto(mcs2_corr_data)
# remove multicollinearity
mcs2_corr_featuers = caret::findCorrelation(mcs2_corrs, cutoff = .9, exact = T, names = T, verbose = T)

mcs2_corr_data[,mcs2_corr_featuers] = NULL # N = 127 varaibles # does not include those demographic info like sex, ethnicity, or maternal age at delivery

mcar_test(mcs2_corr_data)
# did not reject H0 that missingness is completely at random.


## MCS3 age 5
### Load data

mcs3_cog <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5795-tab/tab/mcs3_cm_cognitive_assessment.tab",show_col_types = FALSE)
mcs3_cog$cmid <- paste(mcs3_cog$MCSID, mcs3_cog$CCNUM00, sep = "")

mcs3_teacher <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5795-tab/tab/mcs3_cm_teacher_survey.tab", show_col_types = F)
mcs3_teacher$cmid <- paste(mcs3_teacher$MCSID, mcs3_teacher$CCNUM00, sep = "")

mcs3_parent_interview <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5795-tab/tab/mcs3_parent_interview.tab", show_col_types = F)

mcs3_family_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5795-tab/tab/mcs3_family_derived.tab", show_col_types = FALSE)



### Cognitive ability (appeared in ID identifier)

mcs3_cog_item <- mcs3_cog %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid,CHCAGE00,CCYAGE00,CCPSCO00,CCPSABIL,CCPSTSCORE,CCNSCO00,CCNVABIL,CCNVTSCORE,CCNERR00,CCCSCO00,CCPCABIL,CCPCTSCORE,CCCPAS00,CCCERR00,CCCTOM00,CCCBAS00,CCCCEI00)
mcs3_cog_item[mcs3_cog_item <0]<- NA

### Behvioural data

mcs3_cm_vars <- mcs3_parent_cm %>% filter(cmid %in% asd_sample_diag_loose$cmid & CELIG00 == 1) %>% dplyr::select(MCSID,cmid,CPSPLO0A,CPSPLO0B,CPSPLO0C,CPSPLO0D,CPSPLO0E,CPSPLX0A,CPSPLX0B,CPSPLX0C,CPSECE00,CPSEWS00,CPSEMS00,CPSEWP00,CPSEHT00,CPSEOE00,CPSEPT00,CPSEAO00,CPSEEF00,CPSEUQ00,CPSEDT00,CPSEGA00,CPSECR00,CPSENA00,CPSEIA00,CPSDPF00,CPSDRO00,CPSDHS00,CPSDSR00,CPSDTT00,CPSDSP00,CPSDOR00,CPSDMW00,CPSDHU00,CPSDFS00,CPSDGF00,CPSDFB00,CPSDUD00,CPSDLC00,CPSDDC00,CPSDNC00,CPSDKY00,CPSDOA00,CPSDPB00,CPSDVH00,CPSDST00,CPSDCS00,CPSDGB00,CPSDFE00,CPSDTE00,CPSDEM00,CPSDLD00,CPSDDD00,CPSDHL00,CPSDFR00,CPSDCL00,CPSDLA00,CPSDDB00,CPSCHC00,CPPRAC00,CPDIIG00,CPDISM00,CPDISH00,CPDIBN00,CPDITR00,CPDITE00,CPDIBR00,CPDIRE00,CPPBRE00)
mcs3_cm_vars_4na <- c("CPSECE00","CPSEWS00","CPSEMS00","CPSEWP00","CPSEHT00","CPSEOE00","CPSEPT00","CPSEAO00","CPSEEF00","CPSEUQ00","CPSEDT00","CPSEGA00","CPSECR00","CPSENA00","CPSEIA00","CPSDPF00","CPSDRO00","CPSDHS00","CPSDSR00","CPSDTT00","CPSDSP00","CPSDOR00","CPSDMW00","CPSDHU00","CPSDFS00","CPSDGF00","CPSDFB00","CPSDUD00","CPSDLC00","CPSDDC00","CPSDNC00","CPSDKY00","CPSDOA00","CPSDPB00","CPSDVH00","CPSDST00","CPSDCS00","CPSDGB00","CPSDFE00","CPSDTE00")
mcs3_cm_vars_5na <- c("CPSDEM00","CPSDLD00","CPSDDD00","CPSDHL00","CPSDFR00","CPSDCL00","CPSDLA00","CPSDDB00","CPSCHC00")
mcs3_cm_vars_6na <- c("CPPRAC00","CPDIIG00","CPDISM00","CPDISH00","CPDIBN00","CPDITR00","CPDITE00","CPDIBR00","CPDIRE00","CPPBRE00")

mcs3_cm_vars <- mcs3_cm_vars %>% 
  dplyr::mutate(across(all_of(mcs3_cm_vars_4na), ~ ifelse(. == 4 , NA,.))) %>%                     dplyr::mutate(across(all_of(mcs3_cm_vars_5na), ~ ifelse(. == 5 , NA,.))) %>%
  dplyr::mutate(across(all_of(mcs3_cm_vars_6na), ~ ifelse(. == 6 , NA,.))) %>%
  dplyr::mutate(across(everything(), ~ ifelse(. < 0 , NA, .)))

# code parental concerns as dummy variables
mcs3_cm_vars_dummy <-  dummy_cols(
mcs3_cm_vars, select_columns =  c("CPSPLO0A","CPSPLO0B","CPSPLO0C","CPSPLO0D","CPSPLO0E","CPSPLX0A","CPSPLX0B","CPSPLX0C"), remove_first_dummy = FALSE, ignore_na = TRUE,
remove_selected_columns = TRUE)
mcs3_cm_vars_dummy <- dplyr::select(mcs3_cm_vars_dummy, -contains("NA"))

mcs3_cm_derived_vars <- mcs3_cm_derived %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID, cmid,CDCSBI00,CDCSBE00,CEMOTION,CCONDUCT,CHYPER,CPEER,CPROSOC,CEBDTOT,CIMPACT,CEBDDIFF)
mcs3_cm_derived_vars$CEBDDIFF[mcs3_cm_derived_vars$CEBDDIFF == 4] <- NA
mcs3_cm_derived_vars[mcs3_cm_derived_vars < 0]<- NA



mcs3_cm_interview <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5795-tab/tab/mcs3_cm_interview.tab", show_col_types = FALSE)
mcs3_cm_interview$cmid <- paste(mcs3_cm_interview$MCSID,mcs3_cm_interview$CCNUM00, sep = "")
mcs3_cm_interview_item <- mcs3_cm_interview %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID, cmid,CCTVNS00,CCCONV00,CCBACC00,CCENTR00,CCENTH00,CCINTC00,CCINTA00,CCTIRC00,CCASSC00) %>% dplyr::mutate(across(CCTVNS00:CCTIRC00, ~ ifelse(. == 4,NA,.)))
mcs3_cm_interview_item[mcs3_cm_interview_item <0]<- NA





### Teacher survey data

mcs3_teacher_item <- mcs3_teacher %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid,Q1A_1,Q1A_2,Q1A_3,Q1A_4,Q1A_5,Q1A_6,Q1A_7,Q1A_8,Q1A_9,RAWDA,Q1B_1,Q1B_2,Q1B_3,Q1B_4,Q1B_5,Q1B_6,Q1B_7,Q1B_8,Q1B_9,RAWSD,Q1C_1,Q1C_2,Q1C_3,Q1C_4,Q1C_5,Q1C_6,Q1C_7,Q1C_8,Q1C_9,RAWED,RAWPSE,Q2A_1,Q2A_2,Q2A_3,Q2A_4,Q2A_5,Q2A_6,Q2A_7,Q2A_8,Q2A_9,RAWLCT,Q2B_1,Q2B_2,Q2B_3,Q2B_4,Q2B_5,Q2B_6,Q2B_7,Q2B_8,Q2B_9,RAWLSL,Q2C_1,Q2C_2,Q2C_3,Q2C_4,Q2C_5,Q2C_6,Q2C_7,Q2C_8,Q2C_9,RAWREAD,Q2D_1,Q2D_2,Q2D_3,Q2D_4,Q2D_5,Q2D_6,Q2D_7,Q2D_8,Q2D_9,RAWWRITE,RAWLIT,Q3A_1,Q3A_2,Q3A_3,Q3A_4,Q3A_5,Q3A_6,Q3A_7,Q3A_8,Q3A_9,RAWNLC,Q3B_1,Q3B_2,Q3B_3,Q3B_4,Q3B_5,Q3B_6,Q3B_7,Q3B_8,Q3B_9,RAWCALC,Q3C_1,Q3C_2,Q3C_3,Q3C_4,Q3C_5,Q3C_6,Q3C_7,Q3C_8,Q3C_9,RAWSSM,RAWMATH,Q4_1,Q4_2,Q4_3,Q4_4,Q4_5,Q4_6,Q4_7,Q4_8,Q4_9,RAWKUW,Q5_1,Q5_2,Q5_3,Q5_4,Q5_5,Q5_6,Q5_7,Q5_8,Q5_9,RAWPD,Q6_1,Q6_2,Q6_3,Q6_4,Q6_5,Q6_6,Q6_7,Q6_8,Q6_9,RAWCD,RAWTOT)
mcs3_teacher_item[mcs3_teacher_item <0]<- NA


### Sociodemographic factors

mcs3_parent_derived_vars <- mcs3_parent_derived %>% filter(MCSID %in% asd_sample_diag_loose$MCSID & CELIG00 == 1) %>% dplyr::select(MCSID,CDDSAM00,CDKESS00,CDDRLG00,CDDACT00,CDDNVQ00,CDACAQ00)
# removed CDD05S00, as no one has valid answer to this question.
mcs3_parent_derived_vars <- mcs3_parent_derived_vars %>% mutate_at(vars(CDDNVQ00:CDACAQ00), function(x) ifelse(x == 96, 0, x))
mcs3_parent_derived_vars$Cos_NVQ_qual <- ifelse(is.na(mcs3_parent_derived_vars$CDDNVQ00), NA,ifelse(mcs3_parent_derived_vars$CDDNVQ00 == 95, 1,0))
mcs3_parent_derived_vars$Cos_aca_qual <- ifelse(is.na(mcs3_parent_derived_vars$CDACAQ00), NA,ifelse(mcs3_parent_derived_vars$CDACAQ00 == 95, 1,0))
mcs3_parent_derived_vars <- mcs3_parent_derived_vars %>% dplyr::mutate(across(CDDNVQ00:CDACAQ00, ~ ifelse(. == 95, NA,.)))
mcs3_parent_derived_vars[mcs3_parent_derived_vars < 0]<- NA
mcs3_parent_derived_dummy <-  dummy_cols(
mcs3_parent_derived_vars, select_columns =  c("CDDACT00","CDDRLG00"), remove_first_dummy = FALSE, ignore_na = TRUE,
remove_selected_columns = TRUE)
mcs3_parent_derived_dummy <- dplyr::select(mcs3_parent_derived_dummy, -contains("NA"))


mcs3_parent_interview_vars <- mcs3_parent_interview %>% filter(MCSID %in% asd_sample_diag_loose$MCSID & CELIG00 == 1) %>% dplyr::select(MCSID,CPSFPE00,CPSFEM00,CPSFEP00,CPLOSA00,CPDEAN00,CPTRDE00,CPARGD00,CPARPR00,CPARFR00,CPARAR00,CPARRC00,CPARSR00,CPCHTI00,CPPHDE00,CPPHHO00,CPPHRF00,CPPHEE00,CPPHWO00,CPPHNE00,CPRESE00,CPRELS00,CPRELO00,CPRESN00,CPREIS00,CPCOLT00,CPHARE00,CPFORC00,CPWALI00) 
mcs3_parent_interview_vars[mcs3_parent_interview_vars <0] <- NA
mcs3_parent_interview_6na <- c("CPCHTI00","CPPHDE00","CPPHHO00","CPPHRF00","CPPHEE00","CPPHWO00","CPPHNE00","CPRESE00","CPRELS00","CPRELO00","CPRESN00")
mcs3_parent_interview_vars <- mcs3_parent_interview_vars %>% dplyr::mutate(across(all_of(mcs3_parent_interview_6na), ~ ifelse(. == 6, NA,.)))
mcs3_parent_interview_vars$CPREIS00[mcs3_parent_interview_vars$CPREIS00 == 7] <- NA
mcs3_parent_interview_vars$CPCOLT00[mcs3_parent_interview_vars$CPCOLT00 == 5] <- NA
mcs3_parent_interview_vars$CPHARE00[mcs3_parent_interview_vars$CPHARE00 == 8] <- NA
mcs3_parent_interview_vars$CPFORC00[mcs3_parent_interview_vars$CPFORC00 == 3] <- NA
mcs3_parent_interview_vars$CPWALI00[mcs3_parent_interview_vars$CPWALI00== 11] <- NA


mcs3_family_derived_vars <- mcs3_family_derived %>% filter(MCSID %in% asd_sample_diag_loose$MCSID) %>% dplyr::select(MCSID,CACTRY00,CAREGN00,CDOEDS00,CDOEDE00,CDOEDP00,CDMBMI00,CDROOW00,CDROOW00,COECDUK0,COECDSC0,CDRSMB23,CDRSMB13) 
# removed CHINCC00,CHINCS00,CTOTINC0, due to no valid answer at all
mcs3_family_derived_vars$CAREGN00[mcs3_family_derived_vars$CAREGN00==13] <- NA
mcs3_family_derived_vars[mcs3_family_derived_vars < 0]<- NA
mcs3_other_tip_dummy <- fastDummies::dummy_cols(mcs3_family_derived_vars, select_columns = "CDROOW00",remove_first_dummy = FALSE, ignore_na = TRUE,remove_selected_columns = TRUE)
mcs3_other_tip <- dplyr::select(mcs3_other_tip_dummy, -contains("NA"))
############# how to handle region and country?######


### Deprivation + urbanicity (Geographically linked data)

mcs3_geo <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-5795-tab/tab/mcs3_geographically_linked_data.tab", show_col_types = F)
mcs3_england <- mcs3_geo %>% filter(cactry00 == "1")
mcs3_wales   <- mcs3_geo %>% filter(cactry00 == "2")
mcs3_scotland<- mcs3_geo %>% filter(cactry00 == "3")
mcs3_norire  <- mcs3_geo %>% filter(cactry00 == "4")

mcs3_england_dep <- dplyr::select(mcs3_england, mcsid, cactry00,cmorpcde, CIMDSCOE,CIMDINCE,CIMDEMPE,CIMDHDDE,CIMDESTE) 
colnames(mcs3_england_dep) <- c("MCSID","ccountry","crural","COverall","CIncome","CEmployment","CHealthDisability","CEduSkillTrain")
mcs3_wales_dep <- dplyr::select(mcs3_wales, mcsid, cactry00,cmorpcde, CIWIMDSC,CIWIMDIN,CIWIMDEM,CIWIMDHD,CIWIMDES)
colnames(mcs3_wales_dep) <- c("MCSID","ccountry","crural","COverall","CIncome","CEmployment","CHealthDisability","CEduSkillTrain")
mcs3_scotland_dep <- dplyr::select(mcs3_scotland, mcsid, cactry00,csixfold, CISIMDSC,CISIMDIN,CISIMDEM,CISIMDHD,CISIMDES)
colnames(mcs3_scotland_dep) <- c("MCSID","ccountry","crural","COverall","CIncome","CEmployment","CHealthDisability","CEduSkillTrain")
mcs3_scotland_dep <- mcs3_scotland_dep %>% dplyr::mutate(
    rural = case_when(
      rural %in% c(1, 2) ~ 1,
      rural %in% c(3, 4) ~ 2,
      rural %in% c(5, 6) ~ 3,
    ))
    
mcs3_norire_dep <- dplyr::select(mcs3_norire, mcsid, cactry00,cnirus, CIMDSCON, CIMDINCN,CIMDEMPN,CIMDHDDN,CIMDESTN)
colnames(mcs3_norire_dep) <- c("MCSID","ccountry","crural","COverall","CIncome","CEmployment","CHealthDisability","CEduSkillTrain")
mcs3_dep <- rbind(mcs3_england_dep, mcs3_wales_dep, mcs3_scotland_dep, mcs3_norire_dep) 

mcs3_dep_asd <- mcs3_dep %>% filter(MCSID %in% asd_sample_diag_loose$MCSID) 


### Combining

mcs3_indi_list <- list(mcs3_cog_item,mcs3_cm_vars_dummy,mcs3_cm_derived_vars,mcs3_teacher_item,mcs3_cm_interview_item)
names(mcs3_indi_list) <- c("mcs3_cog_item","mcs3_cm_vars_dummy","mcs3_cm_derived_vars","mcs3_teacher_item","mcs3_cm_interview_item")
mcs3_fam_list <- list(mcs3_parent_derived_dummy,mcs3_parent_interview_vars,mcs3_other_tip,mcs3_dep_asd)
names(mcs3_fam_list) <- c("mcs3_parent_derived_dummy","mcs3_parent_interview_vars","mcs3_other_tip","mcs3_dep_asd")

mcs3_indi <- Reduce(merge_dataframes, mcs3_indi_list)
mcs3_fam <- Reduce(merge_dataframes_fam,mcs3_fam_list)
mcs3_voi  <-  merge(mcs3_indi, mcs3_fam, by = "MCSID", all.x = TRUE)


### remove highly colinear items, test for MCAR

for (col in names(mcs3_voi)) {
  if (is.ordered(mcs3_voi[[col]]) || (is.factor(mcs3_voi[[col]]) || is.character(mcs3_voi[[col]]))) {
    mcs3_voi[[col]] <- as.integer(mcs3_voi[[col]])
  }
}

mcs3_corr_data = mcs3_voi[,3:ncol(mcs3_voi)]
#corr_data <- remove_cols_with_na(corr_data)
mcs3_corr_data <- remove_low_signal_cols(mcs3_corr_data)
mcs3_corrs <- qgraph::cor_auto(mcs3_corr_data)
# remove multicollinearity
mcs3_corr_featuers = caret::findCorrelation(mcs3_corrs, cutoff = .9, exact = T, names = T, verbose = T)

mcs3_corr_data[,mcs3_corr_featuers] = NULL # N = 139 varaibles 

mcar_test(mcs3_corr_data)
# did not reject H0 that missingness is completely at random.



## MCS4 age 7

### Cognitive ability

mcs4_cog <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-6411-tab/tab/mcs4_cm_cognitive_assessment.tab", show_col_types = FALSE)
mcs4_cog$cmid <- paste(mcs4_cog$MCSID,mcs4_cog$DCNUM00, sep = "")
mcs4_cog_item <- mcs4_cog %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid,DAGE,DAGEDY000,DCAGEY00,DCAGEG00,DCWRSC00,DCWRER00,DCWRCO00,DCNSCO00,DCSCA0000,DCWRAB00,DCWRSD00,DCMTOTSCOR,DCMATHS7SC,DCMATHS7SA)
mcs4_cog_item[mcs4_cog_item < 0]<- NA


### Cm level data


mcs4_cm_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-6411-tab/tab/mcs4_cm_derived.tab", show_col_types = FALSE)
mcs4_cm_derived$cmid <- paste(mcs4_cm_derived$MCSID,mcs4_cm_derived$DCNUM00, sep = "")
mcs4_cm_derived_var <- mcs4_cm_derived %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid,DDEMOTION,DDCONDUCT,DDHYPER,DDPEER,DDPROSOC,DDDEBDTOT,DDIMPACT,DDDEBDDIFF,DDCSBI00,DDCSBE00,DDCSBC00,DDEMOTI_T,DDCOND_T,DDHYPER_T,DDPEER_T,DDPROSO_T,DDDEBDTO_T,DDDIMPACT_T,DDDEBDIF_T)
mcs4_cm_derived_var$DDDEBDDIFF[mcs4_cm_derived_var$DDDEBDDIFF == 4] <- NA
mcs4_cm_derived_var[mcs4_cm_derived_var < 0 ]<- NA



mcs4_cm_interview <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-6411-tab/tab/mcs4_cm_interview.tab", show_col_types = FALSE)
mcs4_cm_interview$cmid <- paste(mcs4_cm_interview$MCSID,mcs4_cm_interview$DCNUM00, sep = "")
mcs4_cm_interview_item <- mcs4_cm_interview %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid,DPCONV00,DPBACC00,DPENTR00,DPENTH00,DPINTC00,DPINTA00,DPTIRC00,DCSC0001,DCSC0002,DCSC0003,DCSC0004,DCSC0005,DCSC0006,DCSC0007,DCSC0008,DCSC0009,DCSC0010,DCSC0011,DCSC0012,DCSC0013,DCSC0014,DCSC0015,DCSC0016,DCSC0017,DCSC0018,DCSC0019,DCSC020A,DCSC020B,DCSC020C,DCSC020D,DCSC020E,DCSC0021,DCSC0022,DCSC0023,DCSC0024,DCSC0025,DCSC0026,DCSC0027,DCSC0028,DCSC0029,DCSC0030,DCSC0031,DCSC0032,DCSC0033,DCSC0034,DCSC0035,DCSC0036,DCSC0037,DCSC0038) %>% dplyr::mutate(across(DPCONV00:DPTIRC00, ~ifelse(. == 4,NA,.))) %>% dplyr::mutate_at(vars(DCSC020A,DCSC020B,DCSC020C,DCSC020D), ~ ifelse(DCSC020E == 1, 1,.)) %>% dplyr::mutate(across(everything(), ~ ifelse(. < 0 , NA,.)))  %>% dplyr::select(-DCSC020E) # DCSC020E= all of these, already coded to reflect this in previous column, so removed here
mcs4_cm_interview_item_dummy <- dummy_cols(
mcs4_cm_interview_item,select_columns = "DCSC0008", remove_first_dummy = FALSE, ignore_na = TRUE,
remove_selected_columns = TRUE)
mcs4_cm_interview_item <- dplyr::select(mcs4_cm_interview_item_dummy, -contains("NA"))




mcs4_parent_cm_item <- mcs4_parent_cm %>% filter(cmid %in% asd_sample_diag_loose$cmid & DELIG00 ==1) %>% dplyr::select(MCSID,cmid,DPAMTH00,DPARED00,DPAWRT00,DPAPED00,DPSECE00,DPSEWS00,DPSEMS00,DPSEWP00,DPSEHT00,DPSEOE00,DPSEPT00,DPSEAO00,DPSEEF00,DPSEUQ00,DPSEDT00,DPSEGA00,DPSECR00,DPSENA00,DPSEIA00,DPSDPF00,DPSDRO00,DPSDHS00,DPSDSR00,DPSDTT00,DPSDSP00,DPSDOR00,DPSDMW00,DPSDHU00,DPSDFS00,DPSDGF00,DPSDFB00,DPSDUD00,DPSDLC00,DPSDDC00,DPSDNC00,DPSDKY00,DPSDOA00,DPSDPB00,DPSDVH00,DPSDST00,DPSDCS00,DPSDGB00,DPSDFE00,DPSDTE00,DPSDEM00,DPSDLD00,DPSDDD00,DPSDHL00,DPSDFR00,DPSDCL00,DPSDLA00,DPSDDB00,DPDIIG00,DPDISM00,DPDISH00,DPDIBN00,DPDITR00,DPDITE00,DPDIBR00,DPDIRE00,DPSCHC00,DPENLI00,DPEXAF00,DPCHIR00,DPCHWL00) %>% dplyr:: mutate(across(DPSECE00:DPSDTE00, ~ ifelse(. == 4,NA,.)))  %>% dplyr::mutate(across(c(DPSDEM00:DPSDDB00,DPSCHC00), ~ifelse(. == 5, NA,.))) %>% dplyr::mutate(across(c(DPDIIG00:DPDIRE00), ~ifelse(. == 6, NA,.))) %>% dplyr::mutate(across(everything(), ~ ifelse(. < 0, NA,.)))



mcs4_teacher <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-6411-tab/tab/mcs4_cm_teacher_survey.tab", show_col_types = FALSE)
mcs4_teacher$cmid <- paste(mcs4_teacher$MCSID, mcs4_teacher$DCNUM00, sep ="")
mcs4_teacher_item <- mcs4_teacher %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid,DQ2171,DQ2172,DQ2173,DQ2174,DQ2175,DQ2176,DQ2177,DQ2178,DQ2179,DQ2180,DQ2181,DQ2182,DQ2183,DQ2184,DQ2185,DQ2186,DQ2187,DQ2188,DQ2189,DQ2190,DQ2191,DQ2192,DQ2193,DQ2194,DQ2195,DQ2196,DQ2198,DQ2199,DQ2200,DQ2201,DQ2202,DQ2203,DQ2479,STREAM,STREAMG,LITSET,NUMSET,LITMATH,WICAG,WICAGL,WICAGN,DQ2160,DQ2161,DQ2162,DQ2163,DQ2164,DQ2165,DQ2166,DQ2167,DQ2168,DQ2169,DQ2170) %>% dplyr::mutate(across(c(STREAM,LITSET,NUMSET,WICAGL,WICAGN), ~ ifelse(. == 0, NA,.)))  %>% dplyr::mutate(across(DQ2160:DQ2170, ~ifelse(. == 6., NA,.)))
mcs4_teacher_item[mcs4_teacher_item < 0]<- NA
mcs4_teacher_item <-dummy_cols(mcs4_teacher_item, select_columns = "LITMATH", remove_first_dummy = F, remove_selected_columns = T, ignore_na = T)




### Family level

mcs4_parent_interview <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-6411-tab/tab/mcs4_parent_interview.tab", show_col_types = F)

mcs4_parent_interview_vars <- mcs4_parent_interview %>% filter(MCSID %in% asd_sample_diag_loose$MCSID & DELIG00 == 1) %>% dplyr::select(MCSID,DPSFEP00,DPHEYR00,DPLOSA00,DPDEAN00,DPTRDE00,DPCHTI00,DPPACR00,DPPHDE00,DPPHHO00,DPPHRF00,DPPHEE00,DPPHWO00,DPPHNE00,DPOCCH00,DPOCST00,DPOCTA00,DPOCAN00,DPOCTP00,DPOCBO00,DPOCTH00,DPOCEA00,DPOCEM00,DPOCPP00,DPOCOF00,DPOCLD00,DPOCPR00,DPOCSK00,DPOCGR00,DPREGN00,DPCOLT00,DPHARE00,DPFORC00,DPWALI00)
mcs4_parent_interview_vars$DPREGN00[mcs4_parent_interview_vars$DPREGN00 == 7] <- NA
mcs4_parent_interview_vars$DPCOLT00[mcs4_parent_interview_vars$DPCOLT00 == 5] <- NA
mcs4_parent_interview_vars$DPHARE00[mcs4_parent_interview_vars$DPHARE00 == 8] <- NA
mcs4_parent_interview_vars$DPFORC00[mcs4_parent_interview_vars$DPFORC00 == 3] <- NA
mcs4_parent_interview_vars <- mcs4_parent_interview_vars %>% dplyr::mutate(across(DPCHTI00:DPREGN00, ~ifelse(. ==6, NA,.)))
mcs4_parent_interview_vars[mcs4_parent_interview_vars <0] <- NA




mcs4_parent_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-6411-tab/tab/mcs4_parent_derived.tab", show_col_types = F)
mcs4_parent_derived_item <- mcs4_parent_derived %>% filter(MCSID %in% asd_sample_diag_loose$MCSID & DELIG00 == 1) %>% dplyr:: select(MCSID,DDDNVQ00,DDKESSLER,DDOCEAN,DDDACT00,DDACAQ00) %>% dplyr::mutate(across(everything(), ~ifelse(. <0 , NA,.)))%>% dplyr::mutate(across(c(DDDNVQ00,DDACAQ00), ~ifelse(. == 96, NA,.)))%>%  dplyr::mutate(Dos_NVQ_qual = case_when(DDDNVQ00 == 95 ~ 1, is.na(DDDNVQ00) ~ NA, DDDNVQ00 %in% c(1,2,3,4,5) ~ 0)) %>% dplyr::mutate(Dos_aca_qual = case_when(DDACAQ00 == 95 ~ 1, is.na(DDACAQ00) ~ NA, DDACAQ00 %in% c(1,2,3,4,5) ~ 0)) %>% dplyr::mutate(across(c(DDDNVQ00,DDACAQ00), ~ifelse(. == 95, NA,.)))

mcs4_parent_derived_item_dummy <- dummy_cols(mcs4_parent_derived_item, select_columns = "DDDACT00", remove_first_dummy = F, ignore_na = T, remove_selected_columns = T)
                                                                          
mcs4_parent_derived_item <- dplyr::select(mcs4_parent_derived_item_dummy, -contains("NA"))
                




mcs4_family_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-6411-tab/tab/mcs4_family_derived.tab", show_col_types = F)

mcs4_family_derived_item <-  mcs4_family_derived %>% filter(MCSID %in% asd_sample_diag_loose$MCSID) %>% dplyr::select(MCSID,DACTRY00,DAREGN00,DDOEDS00,DDOEDE00,DDOEDP00,DDMCSC00,DDMCEQ00,DDMCPO00,DDMBMI00,DDROOW00,DDOEDEX00,DOECDUK0,DOECDSC0) 
mcs4_family_derived_item$DAREGN00[mcs4_family_derived_item$DAREGN00 == 13] <- NA
mcs4_family_derived_item[mcs4_family_derived_item < 0]<- NA
mcs4_family_derived_item_dummy <- dummy_cols(mcs4_family_derived_item, select_columns = "DDROOW00",remove_first_dummy = F,remove_selected_columns = T,ignore_na = T)
mcs4_family_derived_item <- dplyr::select(mcs4_family_derived_item_dummy, -contains("NA"))


### Deprivation + urbanicity (Geographically linked data)

mcs4_geo <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-6411-tab/tab/mcs4_geographically_linked_data.tab", show_col_types = F)
mcs4_england <- mcs4_geo %>% filter(dactry00 == "1")
mcs4_wales   <- mcs4_geo %>% filter(dactry00 == "2")
mcs4_scotland<- mcs4_geo %>% filter(dactry00 == "3")
mcs4_norire  <- mcs4_geo %>% filter(dactry00 == "4")

mcs4_england_dep <- dplyr::select(mcs4_england, mcsid, dactry00,dmorpcde, DIMDSCOE,DIMDINCE,DIMDEMPE,DIMDHDDE,DIMDESTE) 
colnames(mcs4_england_dep) <- c("MCSID","dcountry","drural","DOverall","DIncome","DEmployment","DHealthDisability","DEduSkillTrain")
mcs4_wales_dep <- dplyr::select(mcs4_wales, mcsid, dactry00,dmorpcde, DIWIMDSC,DIWIMDIN,DIWIMDEM,DIWIMDHD,DIWIMDES)
colnames(mcs4_wales_dep) <- c("MCSID","dcountry","drural","DOverall","DIncome","DEmployment","DHealthDisability","DEduSkillTrain")
mcs4_scotland_dep <- dplyr::select(mcs4_scotland, mcsid, dactry00,dsixfold, DISIMDSC,DISIMDIN,DISIMDEM,DISIMDHD,DISIMDES)
colnames(mcs4_scotland_dep) <- c("MCSID","dcountry","drural","DOverall","DIncome","DEmployment","DHealthDisability","DEduSkillTrain")
mcs4_scotland_dep <- mcs4_scotland_dep %>% dplyr::mutate(
    drural = case_when(
      drural %in% c(1, 2) ~ 1,
      drural %in% c(3, 4) ~ 2,
      drural %in% c(5, 6) ~ 3,
    ))
    
mcs4_norire_dep <- dplyr::select(mcs4_norire, mcsid, dactry00,dnirus, DIMDSCON, DIMDINCN,DIMDEMPN,DIMDHDDN,DIMDESTN)
colnames(mcs4_norire_dep) <- c("MCSID","dcountry","drural","DOverall","DIncome","DEmployment","DHealthDisability","DEduSkillTrain")
mcs4_dep <- rbind(mcs4_england_dep, mcs4_wales_dep, mcs4_scotland_dep, mcs4_norire_dep) 

mcs4_dep_asd <- mcs4_dep %>% filter(MCSID %in% asd_sample_diag_loose$MCSID) 



### Combining


mcs4_indi_list <- list(mcs4_cog_item,mcs4_cm_derived_var,mcs4_teacher_item,mcs4_cm_interview_item,mcs4_parent_cm_item)
names(mcs4_indi_list) <- c("mcs4_cog_item","mcs4_cm_derived_var","mcs4_teacher_item","mcs4_cm_interview_item","mcs4_parent_cm_item")
mcs4_fam_list <- list(mcs4_parent_derived_item,mcs4_parent_interview_vars,mcs4_family_derived_item,mcs4_dep_asd)
names(mcs4_fam_list) <- c("mcs4_parent_derived_item","mcs4_parent_interview_vars","mcs4_family_derived_item","mcs4_dep_asd")

mcs4_indi <- Reduce(merge_dataframes, mcs4_indi_list)
mcs4_fam <- Reduce(merge_dataframes_fam,mcs4_fam_list)
mcs4_voi  <-  merge(mcs4_indi, mcs4_fam, by = "MCSID", all.x = TRUE)


### remove highly colinear items, test for MCAR

for (col in names(mcs4_voi)) {
  if (is.ordered(mcs4_voi[[col]]) || (is.factor(mcs4_voi[[col]]) || is.character(mcs4_voi[[col]]))) {
    mcs4_voi[[col]] <- as.integer(mcs4_voi[[col]])
  }
}

mcs4_corr_data = mcs4_voi[,3:ncol(mcs4_voi)]
#corr_data <- remove_cols_with_na(corr_data)
mcs4_corr_data <- remove_low_signal_cols(mcs4_corr_data)
mcs4_corrs <- qgraph::cor_auto(mcs4_corr_data)
# remove multicollinearity
mcs4_corr_featuers = caret::findCorrelation(mcs4_corrs, cutoff = .9, exact = T, names = T, verbose = T)

mcs4_corr_data[,mcs4_corr_featuers] = NULL # N = 139 varaibles 

mcar_test(mcs4_corr_data)
# did not reject H0 that missingness is completely at random.





## MCS5 age 11
### Cognitive ability

mcs5_cog <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-7464-tab/tab/mcs5_cm_cognitive_assessment.tab", show_col_types = FALSE)
mcs5_cog$cmid <- paste(mcs5_cog$MCSID,mcs5_cog$ECNUM00, sep = "")
mcs5_cog_item <- mcs5_cog %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid,EITVNS00,EICONV00,EIBACC00,EIENTR00,EIENTH00,EIINTC00,EIINTA00,EITIRC00,EIASSC00,ECASSX0A,ECASSX0B,ECASSX0C,ECASSX0D,ECASSX0E,ECASSX0F,ECASSX0G,ECASSX0H,ECASSX0I,ECASSX0J,ECASSX0K,ECASSX0L,ECASSX0M,ECASSX0N,ECASSX0O,ECASSX0P,ECASSX0Q,ECASSX0R) %>% dplyr::mutate(across(EITVNS00:EITIRC00, ~ifelse(. == 4,NA,.))) %>% dplyr::mutate(across(everything(), ~ifelse(. < 0, NA,.)))




mcs5_cm_interview_item <- mcs5_cm_interview %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid,EPSDPF00,EPSDRO00,EPSDHS00,EPSDSR00,EPSDTT00,EPSDSP00,EPSDOR00,EPSDMW00,EPSDHU00,EPSDFS00,EPSDGF00,EPSDFB00,EPSDUD00,EPSDLC00,EPSDDC00,EPSDNC00,EPSDKY00,EPSDOA00,EPSDPB00,EPSDVH00,EPSDST00,EPSDCS00,EPSDGB00,EPSDFE00,EPSDTE00,EPDIBN00,EPDITR00,EPDIRE00,EPSCHC00,EPCHWL00,EPPUHG00,EPPUBH00,EPPUSK00,EPPUVC00,EPPUFH00,EPPUBR00,EPPUMN00,EPAGMN00,ECQ01X00,ECQ02X00,ECQ03X00,ECQ04X00,ECQ05X00,ECQ06X00,ECQ07X00,ECQ08X00,ECQ09X00,ECQ10A00,ECQ10B00,ECQ10C00,ECQ10D00,ECQ10E00,ECQ10F00,ECQ11A00,ECQ11B00,ECQ11C00,ECQ11D00,ECQ11E00,ECQ22A00,ECQ22B00,ECQ22C00,ECQ23X00,ECQ24X00,ECQ25X00,ECQ26X00,ECQ27X00,ECQ28X00,ECQ29X00,ECQ30X00,ECQ31X00,ECQ32X00,ECQ33X00,ECQ34X00,ECQ35X00,ECQ36X00,ECQ37X00,ECQ38X00,ECQ39X00,ECQ40X00,ECQ41X00,ECQ42X00,ECQ43X00,ECQ44X00,ECQ45X00,ECQ46A00,ECQ46B00,ECQ46C00,ECQ46D00,ECQ49X00,ECQ50X00,ECQ51X00,ECQ52X00,ECQ53A00,ECQ53B00,ECQ54X00,ECQ55X00,ECQ56X00,ECQ57X00,ECQ58X00,ECQ59X00,ECQ74X00,ECQ75X00,ECQ76X00,ECQ77X00,ECQ78X00,ECQ79X00,ECQ80X0A,ECQ80X0B,ECQ80X0C,ECQ80X0D,ECQ80X0E,ECQ80X0F,ECQ81A00,ECQ81B00,ECQ81C00,ECQ81D00) %>%
  dplyr::mutate(across(everything(), ~ ifelse(.< 0,NA,.))) 

# code no brothers or sisters as a dummy variable, and recode such answers in hurt by or hurt siblings as NA so that ordinal scales are left
mcs5_cm_interview_item$no_sib <- ifelse(is.na(mcs5_cm_interview_item$ECQ54X00)&is.na(mcs5_cm_interview_item$ECQ55X00),NA, ifelse(mcs5_cm_interview_item$ECQ54X00 == 7 | mcs5_cm_interview_item$ECQ55X00 == 7, 1,0))
mcs5_cm_interview_item <- mcs5_cm_interview_item %>% dplyr::mutate(across(starts_with("EPSD"), ~ ifelse(. == 4,NA,.))) %>% dplyr::mutate(across(starts_with("EPDI"), ~ ifelse(. == 6,NA,.))) %>%
  dplyr::mutate(across(c(EPSCHC00,ECQ58X00), ~ ifelse(. == 5,NA,.))) %>%
  dplyr::mutate(across(c(ECQ54X00,ECQ55X00), ~ ifelse(. == 7,NA,.))) %>%
  dplyr::mutate(across(c(EPCHWL00,EPPUMN00), ~ ifelse(. == 3,NA,.))) %>%
  dplyr::mutate(across(EPPUHG00:EPPUBR00, ~ ifelse(.%in% c(4,5),NA,.))) %>%
dplyr::mutate(across(ECQ49X00:ECQ52X00, ~ ifelse(. == 4,NA,.))) %>%
  dplyr::mutate(across(EPAGMN00, ~ ifelse(. == 0,NA,.))) 



mcs5_cm_derived_item <- mcs5_cm_derived %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid, EVSRAW,EVSABIL,EVSTSCO,CGTOUTCM,CGTDELAY,CGTDTIME,CGTOPBET,CGTQOFDM,CGTRISKA,CGTRISKT) %>% dplyr::mutate(across(everything(), ~ ifelse(. <0,NA,.)))



mcs5_teacher <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-7464-tab/tab/mcs5_cm_teacher_survey.tab", show_col_types = FALSE)
mcs5_teacher$cmid <- paste(mcs5_teacher$MCSID, mcs5_teacher$ECNUM00, sep = "")
mcs5_teacher_item <- mcs5_teacher %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID, cmid,EQ3A,EQ3B,EQ3C,EQ3D,EQ3E,EQ4,EQ5A,EQ5B,EQ5C,EQ5D,EQ5E,EQ5F,EQ5G,EQ5H,EQ5I,EQ5J,EQ5K,EQ5L,EQ5M,EQ5N,EQ5O,EQ5P,EQ5Q,EQ5R,EQ5S,EQ5T,EQ5U,EQ5V,EQ5W,EQ5X,EQ5Y,EQ6,EQ15,EQ16,EQ17A,EQ17B,EQ44,STREAMG,LITSETG,LITSETGW,NUMSETG,SCISETG,EEMOTI_T,ECOND_T,EHYPER_T,EPEER_T,EPROSO_T,EEBDTO_T,EEBDIF_T,EQ2A,EQ2B,EQ2C,EQ2D,EQ2E,EQ2F,EQ2G,EQ2H) %>% dplyr::mutate(across(everything(), ~ifelse(. <0, NA,.)))





### Family level

mcs5_parent_interview <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-7464-tab/tab/mcs5_parent_interview.tab", show_col_types = F)
mcs5_parent_interview_vars <- mcs5_parent_interview %>% filter(MCSID %in% asd_sample_diag_loose$MCSID & EELIG00 == 1) %>% dplyr::select(MCSID,EPLOLR0F,EPLOLR0H,EPLOLR0J,EPLOLX0E,EPLOLX0G,EPLOLX0I,EPLOLX0P,EPLOLX0X,EPLOLX1L,EPLOLX2F,EPHOTH00,EPARGD00,EPARFR00,EPCHTI00,EPPHDE00,EPPHHO00,EPPHRF00,EPPHEE00,EPPHWO00,EPPHNE00,EPDEAN00,EPTRDE00,EPHARE00,EPFORC00,EPWALI00)
mcs5_parent_interview_vars <- mcs5_parent_interview_vars %>% dplyr::mutate(across(c(EPHOTH00,EPARGD00,EPCHTI00), ~ifelse(. %in% c(6,7), NA,.)))
mcs5_parent_interview_vars$EPARFR00[mcs5_parent_interview_vars$EPARFR00 %in% c(5,6)] <- NA
mcs5_parent_interview_vars <- mcs5_parent_interview_vars %>% dplyr::mutate(across(EPPHDE00:EPPHNE00, ~ifelse(. == 6, NA,.)))
mcs5_parent_interview_vars <- mcs5_parent_interview_vars %>% dplyr::mutate(across(c(EPTRDE00,EPFORC00), ~ifelse(. == 3, NA,.)))
mcs5_parent_interview_vars[mcs5_parent_interview_vars < 0]<- NA




mcs5_parent_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-7464-tab/tab/mcs5_parent_derived.tab", show_col_types = F)
mcs5_parent_derived_item <- mcs5_parent_derived %>% filter(MCSID %in% asd_sample_diag_loose$MCSID& EELIG00 == 1) %>% dplyr::select(MCSID,EDNVQ00,EACAQ00,EDACT00,EDSAM00) %>% dplyr::mutate(across(everything(), ~ifelse(. <0 , NA,.)))%>% dplyr::mutate(across(c(EDNVQ00,EACAQ00), ~ifelse(. == 96, NA,.)))%>%  dplyr::mutate(Eos_NVQ_qual = case_when(EDNVQ00 == 95 ~ 1, is.na(EDNVQ00) ~ NA, EDNVQ00 %in% c(1,2,3,4,5) ~ 0)) %>% dplyr::mutate(Eos_aca_qual = case_when(EACAQ00 == 95 ~ 1, is.na(EACAQ00) ~ NA, EACAQ00 %in% c(1,2,3,4,5) ~ 0)) %>% dplyr::mutate(across(c(EDNVQ00,EACAQ00), ~ifelse(. == 95, NA,.)))

mcs5_parent_derived_item_dummy <- dummy_cols(mcs5_parent_derived_item, select_columns = "EDACT00", remove_first_dummy = F, ignore_na = T, remove_selected_columns = T)
mcs5_parent_derived_item <- dplyr::select(mcs5_parent_derived_item_dummy, -contains("NA"))




mcs5_family_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-7464-tab/tab/mcs5_family_derived.tab", show_col_types = F)
mcs5_family_derived_item <- mcs5_family_derived %>% filter(MCSID %in% asd_sample_diag_loose$MCSID) %>% dplyr::select(MCSID,EACTRY00,EAREGN00,EROOW00,EOEDE000,EOEDP000,EOECDUK0,EOECDSC0) 
mcs5_family_derived_item$EAREGN00[mcs5_family_derived_item$EAREGN00 == 13]<- NA
mcs5_family_derived_item[mcs5_family_derived_item < 0]<- NA
mcs5_family_derived_item <- dummy_cols(mcs5_family_derived_item , select_columns = "EROOW00", remove_first_dummy = F,remove_selected_columns = T,ignore_na = T)




### Deprivation + urbanicity (Geographically linked data)

mcs5_geo <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-7464-tab/tab/mcs5_geographically_linked_data.tab", show_col_types = F)

mcs5_england <- mcs5_geo %>% filter(EACTRY00 == "1")
mcs5_wales   <- mcs5_geo %>% filter(EACTRY00 == "2")
mcs5_scotland<- mcs5_geo %>% filter(EACTRY00 == "3")
mcs5_norire  <- mcs5_geo %>% filter(EACTRY00 == "4")

mcs5_england_dep <- dplyr::select(mcs5_england, MCSID, EACTRY00,EMORPCDE, EIMDSCOE,EIMDINCE,EIMDEMPE,EIMDHDDE,EIMDESTE) 
colnames(mcs5_england_dep) <- c("MCSID","ecountry","erural","EOverall","EIncome","EEmployment","EHealthDisability","EEduSkillTrain")
mcs5_wales_dep <- dplyr::select(mcs5_wales, MCSID, EACTRY00,EMORPCDE, EIWIMDSC,EIWIMDIN,EIWIMDEM,EIWIMDHD,EIWIMDES)
colnames(mcs5_wales_dep) <- c("MCSID","ecountry","erural","EOverall","EIncome","EEmployment","EHealthDisability","EEduSkillTrain")
mcs5_scotland_dep <- dplyr::select(mcs5_scotland, MCSID, EACTRY00,ESIXFOLD, EISIMDSC,EISIMDIN,EISIMDEM,EISIMDHD,EISIMDES)
colnames(mcs5_scotland_dep) <- c("MCSID","ecountry","erural","EOverall","EIncome","EEmployment","EHealthDisability","EEduSkillTrain")
mcs5_scotland_dep <- mcs5_scotland_dep %>% dplyr::mutate(
    erural = case_when(
      erural %in% c(1, 2) ~ 1,
      erural %in% c(3, 4) ~ 2,
      erural %in% c(5, 6) ~ 3,
    ))
    
mcs5_norire_dep <- dplyr::select(mcs5_norire, MCSID, EACTRY00,ENIRUS, EIMDSCON, EIMDINCN,EIMDEMPN,EIMDHDDN,EIMDESTN)
colnames(mcs5_norire_dep) <- c("MCSID","ecountry","erural","EOverall","EIncome","EEmployment","EHealthDisability","EEduSkillTrain")
mcs5_dep <- rbind(mcs5_england_dep, mcs5_wales_dep, mcs5_scotland_dep, mcs5_norire_dep) 

mcs5_dep_asd <- mcs5_dep %>% filter(MCSID %in% asd_sample_diag_loose$MCSID) 



### Combining


mcs5_indi_list <- list(mcs5_cog_item,mcs5_cm_derived_item,mcs5_SDQ,mcs5_teacher_item,mcs5_cm_interview_item)
names(mcs5_indi_list) <- c("mcs5_cog_item","mcs5_cm_derived_item","mcs5_SDQ","mcs5_teacher_item","mcs5_cm_interview_item")
mcs5_fam_list <- list(mcs5_parent_derived_item,mcs5_parent_interview_vars,mcs5_family_derived_item,mcs5_dep_asd)
names(mcs5_fam_list) <- c("mcs5_parent_derived_item","mcs5_parent_interview_vars","mcs5_family_derived_item","mcs5_dep_asd")

mcs5_indi <- Reduce(merge_dataframes, mcs5_indi_list)
mcs5_fam <- Reduce(merge_dataframes_fam,mcs5_fam_list)
mcs5_voi  <-  merge(mcs5_indi, mcs5_fam, by = "MCSID", all.x = TRUE)


### remove highly colinear items, test for MCAR

for (col in names(mcs5_voi)) {
  if (is.ordered(mcs5_voi[[col]]) || (is.factor(mcs5_voi[[col]]) || is.character(mcs5_voi[[col]]))) {
    mcs5_voi[[col]] <- as.integer(mcs5_voi[[col]])
  }
}

mcs5_corr_data = mcs5_voi[,3:ncol(mcs5_voi)]
#corr_data <- remove_cols_with_na(corr_data)
mcs5_corr_data <- remove_low_signal_cols(mcs5_corr_data)
mcs5_corrs <- qgraph::cor_auto(mcs5_corr_data)
# remove multicollinearity
mcs5_corr_featuers = caret::findCorrelation(mcs5_corrs, cutoff = .9, exact = T, names = T, verbose = T)

mcs5_corr_data[,mcs5_corr_featuers] = NULL # N = 139 varaibles 

mcar_test(mcs5_corr_data)
# did not reject H0 that missingness is completely at random.



## MCS6 age 14
### Cognitive ability

mcs6_cog <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-8156-tab/tab/mcs6_cm_cognitive_assessment.tab", show_col_types = FALSE)
mcs6_cog$cmid <- paste(mcs6_cog$MCSID,mcs6_cog$FCNUM00, sep = "")
mcs6_cog_item <- mcs6_cog %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID, cmid,FCCAGE00,FCTVNS00,FCCONV00,FCBACC00,FCENTR00,FCENTH00,FCINTC00,FCINTA00,FCTIRC00,FCASSC0A,FCASSC0B,FCASSC0C,FCASSC0D,FCASSC0E,FCASSC0F,FCASSC0G,FCASSC0H,FCASSC0I,FCASSC0J,FCASSC0K,FCASSC0L,FCASSC0M,FCASSC0N,FCASSC0O,FCASSC0P,FCASSC0Q,FCASSC0R,FCASSC0S,FCASSC0T,FCASSC0U,FCASSC0V,FCWRDSC) %>% dplyr::mutate(across(everything(), ~ifelse(. < 0, NA,.)))



### Cm level

mcs6_parent_cm_item <- mcs6_parent_cm %>% filter(cmid %in% asd_sample_diag_loose$cmid & FELIG00 ==1) %>% dplyr::select(MCSID,cmid,FPSCHC00,FPQARP00,FPEMOT00,FPCHTI00,FPSDPF00,FPSDRO00,FPSDHS00,FPSDSR00,FPSDTT00,FPSDSP00,FPSDOR00,FPSDMW00,FPSDHU00,FPSDFS00,FPSDGF00,FPSDFB00,FPSDUD00,FPSDLC00,FPSDDC00,FPSDNC00,FPSDKY00,FPSDOA00,FPSDPB00,FPSDVH00,FPSDST00,FPSDCS00,FPSDGB00,FPSDFE00,FPSDTE00) %>% dplyr::mutate(across(FPSCHC00:FPQARP00, ~ifelse(. == 5,NA,.)))

mcs6_parent_cm_item$FPEMOT00[mcs6_parent_cm_item$FPEMOT00 == 6] <- NA
mcs6_parent_cm_item[mcs6_parent_cm_item < 0]<- NA




mcs6_cm_interview <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-8156-tab/tab/mcs6_cm_interview.tab", show_col_types = FALSE)
mcs6_cm_interview$cmid <- paste(mcs6_cm_interview$MCSID, mcs6_cm_interview$FCNUM00, sep = "")
mcs6_cm_interview_item <- mcs6_cm_interview %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid,FCCINE00,FCSPOR00,FCBAND00,FCRJOY00,FCORGA00,FCMUSM00,FCRLSV00,FCSAFD00,FCROLE00,FCIMWK00,FCPLAB00,FCBTNG00,FCWELK00,FCWHRD00,FCFGHT00,FCSPNT00,FCSTEL00,FCCOPY00,FCENGL00,FCWLSH00,FCMTHS00,FCSCIE00,FCGDPE00,FCQTRM00,FCSCBE00,FCSINT00,FCSUNH00,FCSTIR00,FCSCWA00,FCMNWO00,FCRLQM00,FCRLQF00,FCQUAM00,FCQUAF00,FCOUTW00,FCOTWI00,FCOTWD00,FCDIST00,FCDISG00,FCDISP00,FCFRBY00,FCFRGL00,FCSAFF00,FCTRSS00,FCNCLS00,FCBGFR00,FCGAMA00,FCGMBL00,FCGAEM00,FCGAMJ00,FCBULB00,FCBULP00,FCHURT00,FCPCKP00,FCCYBU00,FCCYBO00,FCVICG00,FCVICA00,FCVICC00,FCVICE00,FCVICF0A,FCPUHG00,FCPUBH00,FCPUSK00,FCPUVC00,FCPUFH00,FCPUBR00,FCPUMN00,FCAGMN0A,FCSCWK00,FCWYLK00,FCFMLY00,FCFRNS00,FCSCHL00,FCLIFE00,FCSATI00,FCGDQL00,FCDOWL00,FCVALU00,FCGDSF00,FCMDSA00,FCMDSB00,FCMDSC00,FCMDSD00,FCMDSE00,FCMDSF00,FCMDSG00,FCMDSH00,FCMDSI00,FCMDSJ00,FCMDSK00,FCMDSL00,FCMDSM00,FCHARM00,FCRISK00,FCPTNT00,FCTRST0A) 
mcs6_cm_interview_item$nofather <- ifelse(is.na(mcs6_cm_interview_item$FCRLQF00 ), NA,ifelse(mcs6_cm_interview_item$FCRLQF00 == 5,1,0))
mcs6_cm_interview_item$nomother <- ifelse(is.na(mcs6_cm_interview_item$FCRLQM00 ), NA,ifelse(mcs6_cm_interview_item$FCRLQM00 == 5,1,0))
mcs6_cm_interview_item$nosibling <- ifelse(is.na(mcs6_cm_interview_item$FCBULB00)& is.na(mcs6_cm_interview_item$FCBULP00), NA, ifelse(mcs6_cm_interview_item$FCBULB00 == 7 |mcs6_cm_interview_item$FCBULP00 == 7, 1,0))

mcs6_cm_interview_item <- mcs6_cm_interview_item %>% dplyr::mutate(across(FCRLQM00:FCRLQF00, ~ ifelse(.==5,NA,.))) %>% dplyr::mutate(across(FCBULB00:FCBULP00, ~ ifelse(.==7,NA,.))) %>% dplyr::mutate(across(everything(), ~ ifelse(. < 0, NA,.))) 






mcs6_cm_derived_item <- mcs6_cm_derived %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid,FCGTDELAY,FCGTDTIME,FCGTOPBET,FCGTQOFDM,FCGTRISKA,FCGTRISKT,FEMOTION,FCONDUCT,FHYPER,FPEER,FPROSOC,FEBDTOT) %>% dplyr::mutate(across(everything(), ~ifelse(. <0, NA,.)))




### Family level


mcs6_parent_interview <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-8156-tab/tab/mcs6_parent_interview.tab", show_col_types = F)
mcs6_parent_interview$resid <- paste(mcs6_parent_interview$MCSID,mcs6_parent_interview$FPNUM00, sep ="")
mcs6_parent_interview_vars <- mcs6_parent_interview %>% filter(MCSID %in% asd_sample_diag_loose$MCSID & FELIG00 == 1) %>% dplyr::select(MCSID,resid,FPLOLR0E,FPLOLR0G,FPLOLR0I,FPBIGA00,FPBIGB00,FPBIGC00,FPBIGD00,FPBIGE00,FPBIGF00,FPBIGG00,FPBIGH00,FPBIGI00,FPBIGJ00,FPBIGK00,FPBIGL00,FPBIGM00,FPBIGN00,FPBIGO00,FPRISK00,FPPHDE00,FPPHHO00,FPPHRF00,FPPHEE00,FPPHWO00,FPPHNE00,FPDEAN00,FPTRDE00,FPHARE00,FPFORC00,FPSATN00)

mcs6_parent_interview_vars <- mcs6_parent_interview_vars %>% dplyr::mutate(across(starts_with("FPBIG"), ~ ifelse(. == 8, NA,.)))
mcs6_parent_interview_vars$FPRISK00[mcs6_parent_interview_vars$FPRISK00 == 11] <- NA
mcs6_parent_interview_vars <- mcs6_parent_interview_vars %>% dplyr::mutate(across(FPPHDE00:FPPHNE00, ~ ifelse(. == 6, NA,.)))
mcs6_parent_interview_vars <- mcs6_parent_interview_vars %>% dplyr::mutate(across(c(FPDEAN00,FPTRDE00,FPFORC00), ~ ifelse(. ==3, NA,.)))
mcs6_parent_interview_vars$FPSATN00[mcs6_parent_interview_vars$FPSATN00 == 11] <- NA
mcs6_parent_interview_vars$FPHARE00[mcs6_parent_interview_vars$FPHARE00 == 8] <- NA
mcs6_parent_interview_vars[mcs6_parent_interview_vars<0]<- NA



mcs6_parent_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-8156-tab/tab/mcs6_parent_derived.tab", show_col_types = F)
mcs6_parent_derived_item <- mcs6_parent_derived %>% filter(MCSID %in% asd_sample_diag_loose$MCSID & FELIG00 == 1) %>% dplyr::select(MCSID,FDSAM00,FDKESSL,FDOPEN,FDCONSC,FDEXTRAV,FDAGREE,FDNEUROT,FDAUDIT,FPWRDSCM,FPWRDSCP,FDACT00,FDNVQ00,FDACAQ00) %>% dplyr::mutate(across(everything(), ~ifelse(. <0, NA,.))) %>% dplyr::mutate(across(c(FDNVQ00,FDACAQ00), ~ ifelse(. == 96, NA,.))) %>% dplyr::mutate(Fos_NVQ_qual = case_when(FDNVQ00 == 95 ~ 1, is.na(FDNVQ00) ~ NA, FDNVQ00 %in% c(1,2,3,4,5) ~ 0))  %>% dplyr::mutate(Fos_aca_qual = case_when(FDACAQ00 == 95 ~ 1, is.na(FDACAQ00) ~ NA, FDACAQ00 %in% c(1,2,3,4,5) ~ 0)) %>% dplyr::mutate(across(c(FDNVQ00,FDACAQ00), ~ ifelse(. == 95, NA,.)))

mcs6_parent_derived_item_dummy <- dummy_cols(mcs6_parent_derived_item, select_columns = "FDACT00", remove_first_dummy = F,remove_selected_columns = T, ignore_na = T)
mcs6_parent_derived_item <- dplyr::select(mcs6_parent_derived_item_dummy, -contains("NA"))




mcs6_family_derived <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-8156-tab/tab/mcs6_family_derived.tab", show_col_types = F)
mcs6_family_derived_item <- mcs6_family_derived %>% filter(MCSID %in% asd_sample_diag_loose$MCSID) %>% dplyr::select(MCSID,FACTRY00,FAREGN00,FDROOW00,FOEDE000,FOEDP000) 
mcs6_family_derived_item[mcs6_family_derived_item < 0]<- NA
mcs6_family_derived_item <- dummy_cols(mcs6_family_derived_item, select_columns = "FDROOW00", remove_first_dummy = F,remove_selected_columns = T, ignore_na = T)


### Combining


mcs6_indi_list <- list(mcs6_cog_item,mcs6_cm_derived_item,mcs6_cm_interview_item,mcs6_parent_cm_item)
names(mcs6_indi_list) <- c("mcs6_cog_item","mcs6_cm_derived_item","mcs6_cm_interview_item","mcs6_parent_cm_item")
mcs6_fam_list <- list(mcs6_parent_derived_item,mcs6_parent_interview_vars,mcs6_family_derived_item)
names(mcs6_fam_list) <- c("mcs6_parent_derived_item","mcs6_parent_interview_vars","mcs6_family_derived_item")

mcs6_indi <- Reduce(merge_dataframes, mcs6_indi_list)
mcs6_fam <- Reduce(merge_dataframes_fam,mcs6_fam_list)
mcs6_voi  <-  merge(mcs6_indi, mcs6_fam, by = "MCSID", all.x = TRUE)


### remove highly colinear items, test for MCAR

for (col in names(mcs6_voi)) {
  if (is.ordered(mcs6_voi[[col]]) || (is.factor(mcs6_voi[[col]]) || is.character(mcs6_voi[[col]]))) {
    mcs6_voi[[col]] <- as.integer(mcs6_voi[[col]])
  }
}

mcs6_corr_data = mcs6_voi[,3:ncol(mcs6_voi)]
#corr_data <- remove_cols_with_na(corr_data)
mcs6_corr_data <- remove_low_signal_cols(mcs6_corr_data)
mcs6_corrs <- qgraph::cor_auto(mcs6_corr_data)
# remove multicollinearity
mcs6_corr_featuers = caret::findCorrelation(mcs6_corrs, cutoff = .9, exact = T, names = T, verbose = T)

mcs6_corr_data[,mcs6_corr_featuers] = NULL # N = 139 varaibles 

mcar_test(mcs6_corr_data)
# did not reject H0 that missingness is completely at random.



## MCS7 age 17

### Cm level

mcs6_parent_cm$resid <- paste(mcs6_parent_cm$MCSID,mcs6_parent_cm$FPNUM00, sep = "")
mcs6_main_carer <- mcs6_parent_cm %>% filter(FELIG00 == 1) %>% dplyr::select(MCSID,resid)

mcs7_parent_cm$resid <- paste(mcs7_parent_cm$MCSID,mcs7_parent_cm$GPNUM00, sep = "")
mcs7_parent_cm_item <- mcs7_parent_cm %>% filter(cmid %in% asd_sample_diag_loose$cmid & resid %in% mcs6_main_carer$resid) %>%dplyr::select(MCSID,cmid,GPSCHL00,GPTAIM00,GPWHET00,GPWHUT00,GPSCHC00,GPSDPF00,GPSDRO00,GPSDHS00,GPSDSR00,GPSDTT00,GPSDSP00,GPSDOR00,GPSDMW00,GPSDHU00,GPSDFS00,GPSDGF00,GPSDFB00,GPSDUD00,GPSDLC00,GPSDDC00,GPSDNC00,GPSDKY00,GPSDOA00,GPSDPB00,GPSDVH00,GPSDST00,GPSDCS00,GPSDGB00,GPSDFE00,GPSDTE00) %>% dplyr::mutate(across(GPWHET00:GPSCHC00, ~ ifelse(. %in% c(5,6,7), NA,.))) %>% dplyr::mutate(across(starts_with("GPSD"), ~ ifelse(. == 4, NA,.))) %>% dplyr::mutate(across(everything(), ~ ifelse(. < 0, NA,.)))
mcs7_parent_cm_item$GPSCHL00[mcs7_parent_cm_item$GPSCHL00 %in% c(5,6)] <- NA
mcs7_parent_cm_item$GPTAIM00[mcs7_parent_cm_item$GPTAIM00 %in% c(7,8,9)] <- NA





mcs7_cm_interview <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-8682-tab/tab/mcs7_cm_interview.tab", show_col_types = F)
mcs7_cm_interview$cmid <- paste(mcs7_cm_interview$MCSID,mcs7_cm_interview$GCNUM00, sep = "")
mcs7_cm_interview_item <- mcs7_cm_interview %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid,GCCLSM0G,GCCLSM0I,GCCLSM0O,GCRLQM00,GCRLQF00,GCSDQA00,GCSDQB00,GCSDQC00,GCSDQD00,GCSDQE00,GCSDQF00,GCSDQG00,GCSDQH00,GCSDQI00,GCSDQJ00,GCSDQK00,GCSDQL00,GCSDQM00,GCSDQN00,GCSDQO00,GCSDQP00,GCSDQQ00,GCSDQR00,GCSDQS00,GCSDQT00,GCSDQU00,GCSDQV00,GCSDQW00,GCSDQX00,GCSDQY00,GCBIGA00,GCBIGB00,GCBIGC00,GCBIGD00,GCBIGE00,GCBIGF00,GCBIGG00,GCBIGH00,GCBIGI00,GCBIGJ00,GCBIGK00,GCBIGL00,GCBIGM00,GCBIGN00,GCBIGO00,GCPUMN00,GCAGMN00,GCPHDE00,GCPHHO00,GCPHRF00,GCPHEE00,GCPHWO00,GCPHNE00,GCWWOP00,GCWWUS00,GCWWRE00,GCWWDE00,GCWWTH00,GCWWCL00,GCWWMN00,GCSATI00,GCGDQL00,GCDOWL00,GCVALU00,GCGDSF00,GCDAGE00,GCDEAN00,GCTRDE00,GCTRDV00,GCSHCU00,GCSHBU00,GCSHBR00,GCSHOD00,GCSHPU00,GCSHRM00,GCSHRZ0A,GCSHRZ0B,GCSHRZ0C,GCSHRZ0D,GCSHRZ0E,GCSHRZ0F,GCSHRZ0N,GCSHRZ0O,GCSHRZ0P,GCSHRZ0Q,GCSHRZ0R,GCSUIC00,GCBGFR00,GCSXID00,GCGNID00,GCBSCA00,GCBSCB00,GCBSCC00,GCBSCD00,GCOPPO00,GCOPJO00,GCOPCH00,GCOPAB00,GCOPRA00,GCOPRE00,GCOPEN00,GCDISC00,GCTHEA00,GCSPOR00,GCBAND00,GCMGIG00,GCRJOY00,GCORGA00,GCLIBR00,GCMUSM00,GCVOLW00,GCPOLM00,GCRLSV00,GCSPFD00,GCTVHO00,GCCOMH00,GCSOME00,GCSOCM00,GCSOCH00,GCGANG00,GCWEGT00,GCSQLT00,GCSAFF00,GCTRSS00,GCNCLS00,GCOUTW00) %>% dplyr::mutate(across(c(GCRLQM00:GCRLQF00,GCSOCM00,GCSOCH00,GCWEGT00,GCSQLT00),~ifelse(. %in% c(5,6,7), NA,.)))  %>% dplyr::mutate(across(starts_with("GCPH"), ~ ifelse(. %in% c(6,7,8),NA,.))) %>% dplyr::mutate(across(starts_with("GCWW"), ~ ifelse(. %in% c(6,7,8),NA,.))) %>% dplyr::mutate(across(starts_with("GCBS"), ~ ifelse(. %in% c(6,7,8),NA,.))) %>% dplyr::mutate(across(starts_with("GCOP"), ~ ifelse(. %in% c(6,7,8),NA,.))) %>% dplyr::mutate(across(c(GCSATI00:GCGDSF00,GCOUTW00), ~ ifelse(. %in% c(5,6,7),NA,.))) %>% dplyr::mutate(across(c(GCPUMN00,GCDEAN00:GCSHRM00,GCSUIC00,GCBGFR00),~ ifelse(. %in% c(3,4,5),NA,.))) %>% dplyr::mutate(across(c(GCGANG00,GCSAFF00,GCTRSS00,GCNCLS00), ~ifelse(. %in% c(4,5,6), NA,.))) %>% dplyr::mutate(across(GCDISC00:GCSPFD00 ,~ ifelse(. %in% c(7,8,9),NA,.))) %>% dplyr::mutate(across(GCTVHO00:GCSOME00,~ ifelse(. %in% c(10,11,12),NA,.)))

mcs7_cm_interview_item$GCSXID00[mcs7_cm_interview_item$GCSXID00 %in% c(7,8)] <- NA # sexual orientation, please dummy 1-6
mcs7_cm_interview_item$GCGNID00[mcs7_cm_interview_item$GCGNID00 == 7] <- NA # gender identity, please dummy 1-6
mcs7_cm_interview_item[mcs7_cm_interview_item < 0]<-NA
mcs7_cm_interview_item_dummy <- dummy_cols(
mcs7_cm_interview_item,select_columns = c("GCSXID00","GCGNID00"), remove_first_dummy = FALSE, ignore_na = TRUE,remove_selected_columns = TRUE)
mcs7_cm_interview_item <- dplyr::select(mcs7_cm_interview_item_dummy, -contains("NA"))




mcs7_cm_derived_item <- mcs7_cm_derived %>% filter(cmid %in% asd_sample_diag_loose$cmid) %>% dplyr::select(MCSID,cmid,GEMOTION_C,GCONDUCT_C,GHYPER_C,GPEER_C,GPROSOC_C,GEBDTOT_C,GEMOTION,GCONDUCT,GHYPER,GPEER,GPROSOC,GEBDTOT,GDCKESSL,GDCOPEN,GDCCONSC,GDCEXTRAV,GDCAGREE,GDCNEUROT,GDWEMWBS,GDRESTR) %>% dplyr::mutate(across(everything(), ~ ifelse(. <0 ,NA,.)))



### Family level

mcs7_parent_interview <- read_delim("/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/MCS_data/UKDA-8682-tab/tab/mcs7_parent_interview.tab", show_col_types = F)
mcs7_parent_interview$resid <- paste(mcs7_parent_interview$MCSID,mcs7_parent_interview$GPNUM00, sep = "")
mcs7_parent_interview_vars <- mcs7_parent_interview %>% filter(MCSID %in% asd_sample_diag_loose$MCSID & resid %in% mcs6_parent_interview_vars$resid) %>% dplyr::select(MCSID,GPPDHE00,GPPHHO00,GPPHRF00,GPPHEE00,GPPHWO00,GPPHNE00,GPDEAN00,GPTRDE00)
mcs7_parent_interview_vars <- mcs7_parent_interview_vars %>% dplyr::mutate(across(GPPDHE00:GPPHNE00,~ ifelse(. %in% c(6,7,8),NA,.))) %>% dplyr::mutate(across(c(GPDEAN00,GPTRDE00),~ ifelse(. %in% c(3,4,5),NA,.)))
mcs7_parent_interview_vars[mcs7_parent_interview_vars < 0]<- NA


### Combining


mcs7_indi_list <- list(mcs7_cm_derived_item,mcs7_cm_interview_item,mcs7_parent_cm_item)
names(mcs7_indi_list) <- c("mcs7_cm_derived_item","mcs7_cm_interview_item","mcs7_parent_cm_item")


mcs7_indi <- Reduce(merge_dataframes, mcs7_indi_list)

mcs7_voi  <-  merge(mcs7_indi, mcs7_parent_interview_vars, by = "MCSID", all.x = TRUE)


### remove highly colinear items, test for MCAR

for (col in names(mcs7_voi)) {
  if (is.ordered(mcs7_voi[[col]]) || (is.factor(mcs7_voi[[col]]) || is.character(mcs7_voi[[col]]))) {
    mcs7_voi[[col]] <- as.integer(mcs7_voi[[col]])
  }
}

mcs7_corr_data = mcs7_voi[,3:ncol(mcs7_voi)]
#corr_data <- remove_cols_with_na(corr_data)
mcs7_corr_data <- remove_low_signal_cols(mcs7_corr_data)
mcs7_corrs <- qgraph::cor_auto(mcs7_corr_data)
# remove multicollinearity
mcs7_corr_featuers = caret::findCorrelation(mcs7_corrs, cutoff = .9, exact = T, names = T, verbose = T)

mcs7_corr_data[,mcs7_corr_featuers] = NULL # N = 139 varaibles 

mcar_test(mcs7_corr_data)
# did not reject H0 that missingness is completely at random.



## Combining across sweeps

#######Only run once!!!!
mcs2_corr_data <- cbind(mcs2_voi[1:2], mcs2_corr_data)
mcs3_corr_data <- cbind(mcs3_voi[1:2], mcs3_corr_data)
mcs4_corr_data <- cbind(mcs4_voi[1:2], mcs4_corr_data) 
mcs5_corr_data <- cbind(mcs5_voi[1:2], mcs5_corr_data)
mcs6_corr_data <- cbind(mcs6_voi[1:2], mcs6_corr_data)
mcs7_corr_data <- cbind(mcs7_voi[1:2], mcs7_corr_data)



mcs_voi_list <- list(mcs2_voi,mcs3_voi,mcs4_voi,mcs5_voi,mcs6_voi,mcs7_voi) # raw data without removing highly correlated items

mcs_voi_list_s <- list(mcs2_corr_data,mcs3_corr_data,mcs4_corr_data,mcs5_corr_data,mcs6_corr_data,mcs7_corr_data) # after removing highly correlated items sweep wise
mcs_asd_voi <-  Reduce(merge_dataframes, mcs_voi_list)

for (col in names(mcs_asd_voi)) {
  if (is.ordered(mcs_asd_voi[[col]]) || (is.factor(mcs_asd_voi[[col]]) || is.character(mcs_asd_voi[[col]]))) {
    mcs_asd_voi[[col]] <- as.integer(mcs_asd_voi[[col]])
  }
}
# 1566 vars (including 2 ID columns)



mcs_voi_corr_data = mcs_asd_voi[,3:ncol(mcs_asd_voi)]
#corr_data <- remove_cols_with_na(corr_data)
mcs_voi_corr_data <- remove_low_signal_cols(mcs_voi_corr_data)
mcs_voi_corrs <- qgraph::cor_auto(mcs_voi_corr_data)
saveRDS(mcs_voi_corrs, file = "/Users/zhangxinhe/Documents/who recieves a diagnosis/MCS/mcs_voi_corrs.rds")
# remove multicollinearity
mcs_voi_corr_featuers = caret::findCorrelation(mcs_voi_corrs, cutoff = .9, exact = T, names = T, verbose = T)

mcs_voi_corr_data[,mcs_voi_corr_featuers] = NULL 

mcs_voi_range <-  sapply(mcs_voi_corr_data, range, na.rm = T)

cols_to_scale_voi <-  names(which(mcs_voi_range[2,]-mcs_voi_range[1,] > 1)) 
cols_to_scale_voi_z <-  paste0(cols_to_scale_voi, "_z")

mcs_voi_corr_data[,cols_to_scale_voi_z] <-  scale(mcs_voi_corr_data[,cols_to_scale_voi])
mcs_voi_corr_data[,cols_to_scale_voi] = NULL


mcar_test(mcs_voi_corr_data[2:1008])
# did not reject H0 that missingness is completely at random.





vis_miss(mcs_voi_corr_data)
datasets_list <- list(mcs_voi_corr_data)
names_dataset <- c("mcs_voi")

devtools::source_url('https://raw.githubusercontent.com/R-miss-tastic/website/master/static/how-to/generate/amputation.R')

MSE <- function(X, Xtrue, mask) {
  return(sqrt(sum((as.matrix(X) * mask - as.matrix(Xtrue) * mask) ^ 2) / sum(mask)))
}

HowToImpute <- function(X , perc.list , mecha.list , nbsim){
  
  perc_mecha.matrix <- matrix(perc.list, nrow = length(mecha.list) * length(perc.list), ncol = 2)
  perc_mecha.matrix[, 2] <- as.vector(sapply(mecha.list, rep, length(perc.list)))
  results.all <- apply(perc_mecha.matrix, 1, function(perc_mecha) { 
    
    perc <- as.numeric(perc_mecha[1])
    mecha <- perc_mecha[2]
    
    results.couple <- lapply(1:nbsim, function(iter){
      XproduceNA <- produce_NA(as.matrix(X), mechanism = mecha, perc.missing = perc)
      
      XNA <- as.matrix(as.data.frame(XproduceNA$data.incomp))
      
      ## Mean
      X.mean <- imputeMean(XNA)
      
      ## MICE
      temp <- mice(XNA, printFlag = FALSE, method = "pmm", remove.collinear = FALSE) # for the predictive mean matching method
      IMP <- 0
      for (i in 1:5) { IMP <- IMP + mice::complete(temp, i)}
      X.mice  <-  IMP/5  #5 is the default number of multiple imputations
      
      ## PCA
      ncp.pca <- estim_ncpPCA(XNA)$ncp
      pca <- imputePCA(XNA, ncp = ncp.pca)
      X.pca <- pca$comp
      
      ## SoftImpute
      lambda_sft <- cv_sft(XNA)
      sft <- softImpute(x = XNA, lambda = lambda_sft, rank.max = min(10,ncol(XNA)-1))
      X.sft <- sft$u %*% diag(sft$d) %*% t(sft$v)
      X.sft[which(!is.na(XNA))] <- XNA[which(!is.na(XNA))]
      
      ## RandomForest
      forest <- missForest(XNA, verbose = FALSE)
      X.forest<- forest$ximp
      
      
      mse <- sapply(list( X.pca, X.forest,  X.mice, X.sft,  X.mean), MSE, Xtrue = as.data.frame(X), mask = is.na(XNA))
      
      cbind.data.frame(mse)
      
    })
    
    results <- Reduce("+", results.couple) / length(results.couple)
    rownames(results) <- c("X.pca", "X.forest",  "X.mice", "X.soft", "X.mean")
    return(results)
  })
  names(results.all) <- paste0(perc_mecha.matrix[,1], " ", perc_mecha.matrix[,2])
  
  resdf <- as.data.frame(results.all)
  colnames(resdf) <- paste0(perc_mecha.matrix[,1], " ", perc_mecha.matrix[,2])
  
  return(resdf)
}
HowToImpute_real_here <- function(datasets_list, perc , mecha , nbsim, names_dataset){
  plotdf_fin <- NULL
  for (dat in 1:length(datasets_list)){
      res = HowToImpute(datasets_list[[dat]],perc,mecha,nbsim)
      names(res) = names_dataset[[dat]]
      if (dat==1){
        resdf = res
      }else{
        resdf = cbind.data.frame(resdf,res)
      }
      plotdf <- do.call(c,res)
      plotdf <- as.data.frame(plotdf)
      names(plotdf) <- 'mse'
      Methods <- rep(c("PCA", "RandomForest",  "Mice", "SoftImpute",  "Mean"))
      plotdf <- cbind(plotdf, Methods)
      Datasets <- rep(names_dataset[dat],5)
      plotdf <- cbind(plotdf, Datasets)
      if (is.null(plotdf_fin)){
        plotdf_fin <- plotdf
      }else{
        plotdf_fin <- rbind(plotdf_fin,plotdf)
      }
  }
  return(list(plot=plotdf_fin,res=resdf))
}

 HowToImpute_real_here(
                  datasets_list = datasets_list,
                  perc = 0.288,
                  mech = "MCAR",
                  nbsim = 2, names_dataset = names_dataset
                  )
                
plotdf_fin <- howimp_real$plot
res <- howimp_real$res
plotdf_fin

